// lib/comparison/dev-seed.ts
// DEV-ONLY fallback data, mirroring supabase/migrations/20260627121000_seed_business_banking_us.sql.
// Lets `npm run dev` render /[market]/[category]/best BEFORE the migration is
// applied to Supabase. The loader uses this ONLY when NODE_ENV !== 'production'
// and the product_attributes query is empty/unavailable — it can never affect
// production. Once the migration + seed are live, real DB rows take over.

/* eslint-disable @typescript-eslint/no-explicit-any */
const BUSINESS_BANKING_US: any[] = [
    {
      slug: 'mercury', market: 'us', category: 'business-banking', display_name: 'Mercury',
      tagline: 'Best business banking for VC-backed startups', logo_url: null, verified: true,
      score: 9.4, rating: 4.5, review_count: 1240, monthly_fee: 0, signup_bonus: 0, fx_fee_pct: 1, atm_fee: 0, apy: 0, clicks: 1240,
      badges: [{ type: 'gold', label: 'Top pick' }, { type: 'sky', label: 'Most clicked' }],
      chips: ['FDIC up to $5M', 'Opens in ~10 min', 'US LLCs & C-Corps'],
      pros: ['No monthly fees, no minimums', '$5M FDIC via sweep network', 'Free USD wires + treasury option'],
      cons: ['No cash deposits', 'US-registered businesses only'],
      sub_scores: { fees: 9.6, features: 9.3, ux: 9.2, support: 8.9 },
      effective_apr: 'n/a (debit)', cashback: '—', card_network: 'Mastercard', wire_transfers: 'Free USD wires', fdic_coverage: '$5M (sweep)', apps: ['apple', 'android', 'web'],
      verdict: 'The best all-rounder for funded startups',
      has_no_monthly_fee: true, has_free_atm: false, has_no_fx_fee: false, has_cashback: false, has_bonus: false, has_sub_accounts: true, has_interest: false, has_apple_pay: true,
      entity_types: ['llc', 's-corp', 'c-corp'], supports_cash_deposits: false, supports_intl_wires: true, has_bookkeeping: false, has_lending: false, integrations: ['quickbooks', 'stripe', 'xero'],
      is_affiliate: true, review_slug: 'mercury-review', external_url: 'https://mercury.com', is_top_pick: true, best_for: 'Funded startups', display_order: 1,
    },
    {
      slug: 'novo', market: 'us', category: 'business-banking', display_name: 'Novo',
      tagline: 'Best for freelancers and solopreneurs', logo_url: null, verified: true,
      score: 8.8, rating: 4.0, review_count: 910, monthly_fee: 0, signup_bonus: 0, fx_fee_pct: 0, atm_fee: 0, apy: 0, clicks: 1050,
      badges: [{ type: 'green', label: 'Best for freelancers' }],
      chips: ['FDIC standard', 'Refunds ATM fees', 'US sole props & LLCs'],
      pros: ['Truly $0 monthly fee', 'Refunds all ATM fees', 'Stripe & Shopify integrations'],
      cons: ['No interest on balances', 'No international wires'],
      sub_scores: { fees: 9.4, features: 8.6, ux: 8.8, support: 8.4 },
      effective_apr: 'n/a (debit)', cashback: '—', card_network: 'Mastercard', wire_transfers: 'Domestic only', fdic_coverage: 'Standard ($250k)', apps: ['apple', 'android', 'web'],
      verdict: 'The strongest truly-free pick for freelancers',
      has_no_monthly_fee: true, has_free_atm: true, has_no_fx_fee: true, has_cashback: false, has_bonus: false, has_sub_accounts: false, has_interest: false, has_apple_pay: true,
      entity_types: ['sole-prop', 'llc', 's-corp'], supports_cash_deposits: false, supports_intl_wires: false, has_bookkeeping: false, has_lending: false, integrations: ['stripe', 'shopify', 'quickbooks'],
      is_affiliate: true, review_slug: 'novo-review', external_url: 'https://www.novo.co', is_top_pick: false, best_for: 'Freelancers', display_order: 2,
    },
    {
      slug: 'relay', market: 'us', category: 'business-banking', display_name: 'Relay',
      tagline: 'Best for teams and Profit First', logo_url: null, verified: true,
      score: 9.0, rating: 4.2, review_count: 780, monthly_fee: 0, signup_bonus: 0, fx_fee_pct: 1, atm_fee: 0, apy: 0, clicks: 760,
      badges: [{ type: 'green', label: 'Best for teams' }],
      chips: ['FDIC up to $3M', 'Up to 20 accounts', 'US businesses'],
      pros: ['Up to 20 checking accounts', 'Roles & permissions for teams', 'No-fee Allpoint ATMs'],
      cons: ['Wires $5 on free plan (free on Grow)', 'No lending'],
      sub_scores: { fees: 9.2, features: 9.0, ux: 8.6, support: 8.5 },
      effective_apr: 'n/a (debit)', cashback: '—', card_network: 'Visa', wire_transfers: 'Outgoing $5 (free on Grow)', fdic_coverage: '$3M (sweep)', apps: ['apple', 'android', 'web'],
      verdict: 'Built for teams and Profit-First budgeting',
      has_no_monthly_fee: true, has_free_atm: true, has_no_fx_fee: false, has_cashback: false, has_bonus: false, has_sub_accounts: true, has_interest: false, has_apple_pay: true,
      entity_types: ['llc', 's-corp', 'c-corp', 'sole-prop'], supports_cash_deposits: true, supports_intl_wires: true, has_bookkeeping: false, has_lending: false, integrations: ['quickbooks', 'xero'],
      is_affiliate: true, review_slug: 'relay-review', external_url: 'https://relayfi.com', is_top_pick: false, best_for: 'Teams', display_order: 3,
    },
    {
      slug: 'bluevine', market: 'us', category: 'business-banking', display_name: 'Bluevine',
      tagline: 'Best APY if you keep a balance', logo_url: null, verified: true,
      score: 8.7, rating: 4.0, review_count: 1520, monthly_fee: 0, signup_bonus: 500, fx_fee_pct: 2.9, atm_fee: 2.5, apy: 1.3, clicks: 900,
      badges: [{ type: 'green', label: 'Highest APY' }],
      chips: ['FDIC up to $3M', '1.3% APY (Standard)', 'US businesses'],
      pros: ['1.3% APY on balances up to $250k', '$500 signup bonus (terms apply)', 'Lines of credit available'],
      cons: ['$2.50 out-of-network ATM fee', '2.9% foreign transaction fee'],
      sub_scores: { fees: 7.8, features: 8.8, ux: 8.2, support: 8.2 },
      effective_apr: 'n/a (debit)', cashback: '—', card_network: 'Mastercard', wire_transfers: 'Outgoing wires (fee)', fdic_coverage: '$3M (sweep)', apps: ['apple', 'android', 'web'],
      verdict: 'The pick if you park a higher balance',
      has_no_monthly_fee: true, has_free_atm: false, has_no_fx_fee: false, has_cashback: false, has_bonus: true, has_sub_accounts: false, has_interest: true, has_apple_pay: true,
      entity_types: ['llc', 's-corp', 'c-corp', 'sole-prop'], supports_cash_deposits: true, supports_intl_wires: false, has_bookkeeping: false, has_lending: true, integrations: ['quickbooks'],
      is_affiliate: false, review_slug: 'bluevine-review', external_url: 'https://www.bluevine.com', is_top_pick: false, best_for: 'High balances', display_order: 4,
    },
    {
      slug: 'lili', market: 'us', category: 'business-banking', display_name: 'Lili',
      tagline: 'Best built-in tax tools for freelancers', logo_url: null, verified: true,
      score: 8.2, rating: 4.0, review_count: 640, monthly_fee: 15, signup_bonus: 0, fx_fee_pct: 3, atm_fee: 0, apy: 0, clicks: 540,
      badges: [{ type: 'green', label: 'Best tax tools' }],
      chips: ['FDIC standard', 'Free MoneyPass ATMs', 'US sole props'],
      pros: ['Built-in tax buckets (Pro)', '1% cashback (Pro)', 'Free MoneyPass ATMs'],
      cons: ['$15/mo for Pro features', '3% foreign transaction fee'],
      sub_scores: { fees: 8.0, features: 8.2, ux: 8.4, support: 7.8 },
      effective_apr: 'n/a (debit)', cashback: '1% (Pro)', card_network: 'Visa', wire_transfers: 'Not supported', fdic_coverage: 'Standard ($250k)', apps: ['apple', 'android', 'web'],
      verdict: 'Best for tax-conscious freelancers',
      has_no_monthly_fee: false, has_free_atm: true, has_no_fx_fee: false, has_cashback: true, has_bonus: false, has_sub_accounts: false, has_interest: false, has_apple_pay: true,
      entity_types: ['sole-prop', 'llc'], supports_cash_deposits: true, supports_intl_wires: false, has_bookkeeping: true, has_lending: false, integrations: [],
      is_affiliate: false, review_slug: null, external_url: 'https://lili.co/', is_top_pick: false, best_for: 'Tax tools', display_order: 5,
    },
];

export const DEV_SEED_ROWS: Record<string, any[]> = {
  // Legacy 2-segment engine key (unchanged).
  'us/business-banking': BUSINESS_BANKING_US,
  // Cockpit 3-segment key — same rows, tagged with the topic the loader queries by.
  'us/business-banking/business-bank-accounts': BUSINESS_BANKING_US.map((r) => ({
    ...r,
    topic: 'business-bank-accounts',
  })),

  'us/personal-finance/robo-advisors': [
    {
      slug: 'wealthfront', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'Wealthfront',
      tagline: 'Best overall for hands-off investors', logo_url: null, verified: true,
      score: 9.4, rating: 4.6, review_count: 3210, clicks: 3210, management_fee: 0.25, account_minimum: 500,
      attributes: { tlh: true, human_advisor: false, account_types: ['taxable', 'ira', 'roth', 'sep'], sipc: true, frac: true, sri: true, crypto: false },
      source_type: 'official', confidence: 'high', source_url: 'https://www.wealthfront.com/pricing', data_verified_at: '2026-06-28',
      badges: [{ type: 'gold', label: 'Top pick' }, { type: 'sky', label: 'Most clicked' }],
      chips: ['Auto tax-loss harvesting', '0.25% flat fee', '$500 minimum'],
      pros: ['Best-in-class tax-loss harvesting', 'Huge range of account types incl. 529', '4.5% APY on uninvested cash'],
      cons: ['No human advisor option', '$500 minimum to start'],
      sub_scores: { fees: 9.3, features: 9.5, ux: 9.4, support: 8.8 },
      verdict: 'The best all-round automated investing platform',
      deep_dive: 'Wealthfront pairs a low 0.25% flat fee with the most aggressive tax-loss harvesting in the category and an unusually wide set of account types, making it the default pick for hands-off investors who want automation without paying for an advisor.',
      is_affiliate: true, review_slug: 'wealthfront-review', external_url: 'https://www.wealthfront.com', is_top_pick: true, best_for: 'Most investors', display_order: 1,
    },
    {
      slug: 'betterment', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'Betterment',
      tagline: 'Best for goal-based investing', logo_url: null, verified: true,
      score: 9.2, rating: 4.5, review_count: 4120, clicks: 4120, management_fee: 0.25, account_minimum: 0,
      attributes: { tlh: true, human_advisor: true, account_types: ['taxable', 'ira', 'roth'], sipc: true, frac: true, sri: true, crypto: true },
      source_type: 'official', confidence: 'high', source_url: 'https://www.betterment.com/pricing', data_verified_at: '2026-06-28',
      badges: [{ type: 'green', label: 'Best for goals' }],
      chips: ['Start from $0', 'Goal-based portfolios', 'SRI & crypto options'],
      pros: ['No minimum to start', 'Goal-based planning tools', 'SRI, ESG and crypto portfolios'],
      cons: ['0.25% adds up on small balances', 'Human advice needs Premium'],
      sub_scores: { fees: 8.9, features: 9.2, ux: 9.5, support: 9.0 },
      verdict: 'The best choice for goal-based investing',
      deep_dive: 'Betterment lets you start with $0 and organizes everything around goals, with optional human advisors on its Premium tier and a broad menu of SRI, ESG and crypto portfolios — ideal for investors who want guidance baked into the experience.',
      is_affiliate: true, review_slug: 'betterment-review', external_url: 'https://www.betterment.com', is_top_pick: false, best_for: 'Goal planning', display_order: 2,
    },
    {
      slug: 'fidelity-go', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'Fidelity Go',
      tagline: 'Best for cost-conscious beginners', logo_url: null, verified: true,
      score: 9.0, rating: 4.7, review_count: 2680, clicks: 2680, management_fee: 0, account_minimum: 10,
      attributes: { tlh: false, human_advisor: true, account_types: ['taxable', 'ira', 'hsa'], sipc: true, frac: true, sri: false, crypto: false },
      source_type: 'official', confidence: 'high', source_url: 'https://www.fidelity.com/go', data_verified_at: '2026-06-28',
      badges: [{ type: 'green', label: 'Lowest cost' }],
      chips: ['Free under $25,000', 'No real minimum', 'Backed by Fidelity'],
      pros: ['Completely free under $25,000', 'No practical minimum to start', 'Fidelity research and support'],
      cons: ['No tax-loss harvesting', '0.35% above $25,000'],
      sub_scores: { fees: 9.9, features: 7.8, ux: 8.4, support: 8.8 },
      verdict: 'The best free starter for cost-conscious investors',
      deep_dive: 'Fidelity Go is free under $25,000 and has effectively no minimum, making it the cheapest way to start automated investing — the trade-off is no tax-loss harvesting and a 0.35% fee once balances grow past $25k.',
      is_affiliate: false, review_slug: 'fidelity-go-review', external_url: 'https://www.fidelity.com', is_top_pick: false, best_for: 'Beginners', display_order: 3,
    },
    {
      slug: 'schwab-intelligent', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'Schwab Intelligent',
      tagline: 'Best zero-fee option for larger balances', logo_url: null, verified: true,
      score: 8.8, rating: 4.5, review_count: 1540, clicks: 1540, management_fee: 0, account_minimum: 5000,
      attributes: { tlh: true, human_advisor: false, account_types: ['taxable', 'ira', 'roth'], sipc: true, frac: false, sri: true, crypto: false },
      source_type: 'official', confidence: 'high', source_url: 'https://www.schwab.com/intelligent-portfolios', data_verified_at: '2026-06-28',
      badges: [{ type: 'green', label: 'Best $0 fee' }],
      chips: ['0% advisory fee', 'Tax-loss harvesting $50k+', '24/7 live support'],
      pros: ['No advisory fee at all', 'Tax-loss harvesting above $50k', '24/7 phone and chat support'],
      cons: ['High $5,000 minimum', 'Holds a cash allocation (cash drag)'],
      sub_scores: { fees: 9.6, features: 8.5, ux: 8.0, support: 9.0 },
      verdict: 'The best zero-fee option for larger balances',
      deep_dive: 'Schwab Intelligent Portfolios charges no advisory fee and adds tax-loss harvesting above $50k, but requires a $5,000 minimum and keeps a mandatory cash allocation that can drag on returns.',
      is_affiliate: false, review_slug: 'schwab-intelligent-review', external_url: 'https://www.schwab.com', is_top_pick: false, best_for: '$50k+ balances', display_order: 4,
    },
    {
      slug: 'vanguard-digital', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'Vanguard Digital',
      tagline: 'Best for buy-and-hold index investors', logo_url: null, verified: true,
      score: 8.9, rating: 4.6, review_count: 2010, clicks: 2010, management_fee: 0.15, account_minimum: 100,
      attributes: { tlh: false, human_advisor: false, account_types: ['taxable', 'ira'], sipc: true, frac: false, sri: false, crypto: false },
      source_type: 'official', confidence: 'high', source_url: 'https://investor.vanguard.com/advice/digital-advisor', data_verified_at: '2026-06-28',
      badges: [{ type: 'green', label: 'Long-term index' }],
      chips: ['Very low 0.15% fee', 'Real Vanguard index funds', 'Trusted long-term'],
      pros: ['Among the lowest fees at 0.15%', 'Genuine Vanguard index funds', 'Built for long-term holders'],
      cons: ['$100 minimum', 'No tax-loss harvesting'],
      sub_scores: { fees: 9.4, features: 7.4, ux: 7.6, support: 8.2 },
      verdict: 'The best pick for buy-and-hold index investors',
      deep_dive: 'Vanguard Digital Advisor wraps genuine Vanguard index funds in a very low 0.15% all-in fee, making it the natural home for long-term, buy-and-hold investors who do not need tax-loss harvesting.',
      is_affiliate: false, review_slug: 'vanguard-digital-advisor-review', external_url: 'https://investor.vanguard.com', is_top_pick: false, best_for: 'Long-term index', display_order: 5,
    },
    {
      slug: 'sofi-robo', market: 'us', category: 'personal-finance', topic: 'robo-advisors', display_name: 'SoFi Robo',
      tagline: 'Best free starter robo for beginners', logo_url: null, verified: true,
      score: 8.5, rating: 4.3, review_count: 1180, clicks: 1180, management_fee: 0, account_minimum: 50,
      attributes: { tlh: false, human_advisor: true, account_types: ['taxable', 'ira', 'roth'], sipc: true, frac: true, sri: false, crypto: false },
      source_type: 'official', confidence: 'medium', source_url: 'https://www.sofi.com/invest/automated', data_verified_at: '2026-06-28',
      badges: [{ type: 'green', label: 'Beginner-friendly' }],
      chips: ['Free management', 'Free access to advisors', 'Beginner-friendly app'],
      pros: ['No management fee', 'Free access to human advisors', 'Polished beginner app'],
      cons: ['Smaller fund selection', 'No tax-loss harvesting'],
      sub_scores: { fees: 9.5, features: 7.2, ux: 9.0, support: 8.4 },
      verdict: 'The best free starter robo for beginners',
      deep_dive: 'SoFi’s automated investing is free to manage and includes complimentary access to human financial planners, which — combined with a $50 minimum and a polished app — makes it a friendly on-ramp for first-time investors.',
      is_affiliate: true, review_slug: 'sofi-robo-review', external_url: 'https://www.sofi.com', is_top_pick: false, best_for: 'Beginners', display_order: 6,
    },
  ],
};
/* eslint-enable @typescript-eslint/no-explicit-any */
