// components/research/logo-dims.ts
// AUTO-GENERATED by scripts/research/normalize-logos.mjs — do not edit by hand.
// Intrinsic pixel dimensions of each TRIMMED broker logo asset (transparent
// margin removed), fed to next/image so a logo with any aspect ratio renders
// undistorted. Display size is set by the CSS slot in BrokerLogo, not here.

export interface LogoDim {
  w: number;
  h: number;
}

export const LOGO_DIMS: Record<string, LogoDim> = {
  "charles-schwab": { w: 140, h: 72 },
  "etoro": { w: 233, h: 72 },
  "etrade": { w: 311, h: 72 },
  "fidelity": { w: 320, h: 69 },
  "interactive-brokers": { w: 320, h: 45 },
  "merrill-edge": { w: 249, h: 72 },
  "robinhood": { w: 320, h: 61 },
  "tastytrade": { w: 320, h: 58 },
  "webull": { w: 320, h: 56 },
};
