// e2e/research-raw-html.spec.ts
// unified-research-discovery-pr2-hubs plan, Task 8 — proves spec invariant 12
// ("100% der Review-Hrefs stehen im Raw HTML", spec §15) and the operator's
// no-JS merge-blocker requirement: a crawler that never runs JavaScript must
// see the REAL catalog — genuine, navigable review links with real titles —
// not merely a container/wrapper element.
//
// JavaScript is deliberately left OFF: the repo's Playwright config
// (playwright.config.ts) defaults `javaScriptEnabled: false`, and unlike
// research-shell/-tracking/-a11y (which each opt back into
// `test.use({ javaScriptEnabled: true })` because they exercise the
// hydrated client shell), this spec must NOT add that override. The whole
// point of spec §8 ("useSearchParams bleibt unter Suspense... der
// serverseitige Fallback trägt die SEO-Last") is that the SERVER-rendered
// `BrowseFallback` (components/research/ResearchHubPage.tsx) — not the
// client `ResearchHub` — carries every review href, and that only proves
// anything if this test genuinely never executes a script.
//
// The expected hrefs come from e2e/fixtures/research-review-hrefs.json, a
// fixture generated by `npx tsx scripts/research/export-review-hrefs.mts` —
// an INDEPENDENT re-derivation of lib/research/catalog.ts's own
// loadMarketReviewItems() inclusion rule (slug !== 'index', numeric
// editorial rating), read straight from the MDX files on disk via
// getContentByMarketAndCategory()/marketCategories, never by importing
// catalog.ts itself (which is `import 'server-only'`-guarded and cannot run
// in a plain script). The expected list is NEVER read from the page or DOM
// under test — a test that derived its own expectations from the thing it is
// checking would only prove the page agrees with itself.

import { test, expect } from '@playwright/test';
import hrefFixture from './fixtures/research-review-hrefs.json';

type MarketKey = keyof typeof hrefFixture;

const RESEARCH_PATHS = ['/research', '/uk/research', '/ca/research', '/au/research'] as const;

const marketForResearchPath = (path: string): MarketKey =>
  path === '/research' ? 'us' : (path.split('/')[1] as MarketKey);

const expectedReviewHrefsFor = (path: string): string[] => hrefFixture[marketForResearchPath(path)];

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** The visible text of the FIRST anchor in the raw HTML whose href is exactly
 *  `href`. Both card components (components/research/CatalogCard.tsx,
 *  components/research/ResearchCard.tsx) render the card's own title/name as
 *  a plain-text `<Link>` BEFORE any "Read research"/"Compare" CTA button that
 *  might reuse the same href further down the card — so the first match in
 *  document order is always the card's real, human-readable title, never a
 *  generic CTA label. */
function firstAnchorText(html: string, href: string): string | null {
  const pattern = new RegExp(`<a[^>]*href="${escapeRegExp(href)}"[^>]*>([^<]+)</a>`);
  const match = html.match(pattern);
  return match ? match[1].trim() : null;
}

test.describe('Research hubs — raw HTML with JavaScript disabled', () => {
  test('raw HTML contains every review href, with real titles behind the first/middle/last links', async ({
    request,
  }) => {
    for (const path of RESEARCH_PATHS) {
      const response = await request.get(path);
      expect(response.status(), `${path} did not return 200`).toBe(200);
      const html = await response.text();

      const expectedHrefs = expectedReviewHrefsFor(path);
      expect(expectedHrefs.length, `no expected review hrefs fixtured for ${path}`).toBeGreaterThan(0);

      // Invariant 12 (spec §15) — every single one, not a sample.
      for (const href of expectedHrefs) {
        expect(html, `${path}: missing href="${href}"`).toContain(`href="${href}"`);
      }

      const first = expectedHrefs[0];
      const middle = expectedHrefs[Math.floor(expectedHrefs.length / 2)];
      const last = expectedHrefs.at(-1)!;

      expect(html, `${path}: missing first href="${first}"`).toContain(`href="${first}"`);
      expect(html, `${path}: missing middle href="${middle}"`).toContain(`href="${middle}"`);
      expect(html, `${path}: missing last href="${last}"`).toContain(`href="${last}"`);

      // OPERATOR MERGE BLOCKER: prove real catalog TITLES, not merely that a
      // wrapper element exists. Each of the three sampled links must carry
      // real, non-empty visible anchor text — an empty <article> shell or a
      // bare href with no label would fail here even though the string
      // checks above already passed.
      for (const href of [first, middle, last]) {
        const title = firstAnchorText(html, href);
        expect(title, `${path}: no anchor text found for href="${href}"`).not.toBeNull();
        expect(
          title!.length,
          `${path}: anchor text for href="${href}" is suspiciously short: "${title}"`,
        ).toBeGreaterThan(2);
      }
    }
  });

  // OPERATOR MERGE BLOCKER: a link that 404s is not "navigable" — prove at
  // least one sampled href per market genuinely resolves, not just that its
  // string appears in the markup.
  test('a sampled review href from each hub is genuinely navigable (200)', async ({ request }) => {
    for (const path of RESEARCH_PATHS) {
      const expectedHrefs = expectedReviewHrefsFor(path);
      const middle = expectedHrefs[Math.floor(expectedHrefs.length / 2)];
      const res = await request.get(middle);
      expect(res.status(), `${middle} (linked from ${path}) did not return 200`).toBe(200);
    }
  });
});
