-- Comparison Cockpit — seed UK money-saving-tools (market='uk',
-- category='cost-of-living', UK-exclusive topic). Visit-only launch
-- (AU/CA/UK rollout, Stage 3 Slice UK-3): affiliate_link_id NULL,
-- is_affiliate=false, review_slug NULL, external_url = provider homepage.
-- Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- ukMoneySavingToolsAttributesSchema. MoneySuperMarket and Quidco's shared
-- MONY Group parent ownership is disclosed. TopCashback and Quidco's
-- industry-wide cashback payout-delay pattern is disclosed for both, not
-- singling out either. Chip's FSCS-via-ClearBank structure (aggregated
-- £120,000 across all ClearBank-held products, not per product) is
-- disclosed precisely.
-- Provenance: live research 2026-07-11 against official pricing pages,
-- Ofgem, Trustpilot, CMA enforcement records.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'moneysupermarket',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'MoneySuperMarket',
  'A broad, Ofgem-accredited comparison hub',
  9,
  4.8,
  56000,
  56000,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Ofgem-accredited energy comparison', 'Multi-category: energy, insurance, credit cards', 'Trustpilot 4.8/5 (~56K reviews)']::text[],
  ARRAY['Ofgem-accredited for its energy comparison channel, plus broad multi-category coverage (insurance, credit cards, broadband)', 'FCA-authorised (as an appointed representative) for insurance, mortgage and consumer-credit comparisons', 'Strong Trustpilot rating (4.8/5, ~56,000 reviews)']::text[],
  ARRAY['Shares the same FTSE 250 parent (MONY Group) as Quidco and MoneySavingExpert — worth knowing if comparing more than one on this page', 'Commission-based revenue model, though FCA rules require this not to affect comparison ranking']::text[],
  '{"trust":9,"breadth":9.4,"rating":9.6}'::jsonb,
  'The broadest, most trusted comparison hub in this comparison.',
  '{"tool_type":"multi_category_comparison","business_model_note":"Free to use; earns commission from suppliers (energy, insurance, credit cards, broadband) when a user completes a switch or purchase — commission does not affect comparison ranking. MoneySuperMarket.com Limited is an appointed representative of MoneySuperMarket.com Financial Group Ltd, FCA-authorised (FRN 303190).","key_feature_note":"Broad multi-category comparison across energy, insurance, credit cards and broadband, positioned as a one-stop bill-cutting hub.","ofgem_accredited":true,"trustpilot_rating":4.8,"trustpilot_count":56000,"trustpilot_note":"uk.trustpilot.com/review/www.moneysupermarket.com — \"Excellent\"","regulatory_note":"MoneySuperMarket, MoneySavingExpert and Quidco (also on this page) are all owned by the same FTSE 250 parent, MONY Group plc — worth knowing if comparing more than one as though they were fully independent recommendations. No CMA or FCA enforcement action was found for 2024-2026; the FCA has separately warned about clone-firm scams impersonating the \"Money Supermarket\" name, which is fraud against the brand, not a finding against the real company."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.moneysupermarket.com/',
  true,
  'Households wanting the broadest comparison coverage',
  1,
  'https://www.moneysupermarket.com/how-moneysupermarket-works/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'topcashback',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'TopCashback',
  'The UK''s largest cashback portal — with a disclosed payout-delay pattern',
  8.6,
  4.6,
  0,
  0,
  0,
  '[{"type":"green","label":"Best cashback portal"}]'::jsonb,
  ARRAY['15M+ UK members', '£1bn+ paid out cumulatively', '⚠ Payout-delay complaints — see detail']::text[],
  ARRAY['The UK''s largest cashback portal by membership (15M+ members)', 'Won Consumer Moneyfacts "Cashback Site of the Year 2024"', 'Strong Trustpilot rating (4.6/5, "Excellent")']::text[],
  ARRAY['Multiple 2026 complaints describe cashback claims declined or delayed for months beyond the stated payment window', 'A small membership fee applies to unlock 100% payout on some account tiers — verify current fee structure at signup']::text[],
  '{"trust":7.6,"breadth":8.8,"rating":9.2}'::jsonb,
  'The largest cashback portal by scale — a real payout-delay pattern to weigh, common across the industry.',
  '{"tool_type":"cashback_portal","business_model_note":"Retailers pay TopCashback commission for referred sales; TopCashback passes on a large share of that commission to members as cashback, plus revenue from on-site sponsored placements.","key_feature_note":"Passive cashback layered on top of everyday spending across thousands of UK retailers — the UK''s largest such platform by membership.","ofgem_accredited":null,"trustpilot_rating":4.6,"trustpilot_count":null,"trustpilot_note":"trustpilot.com/review/www.topcashback.co.uk — \"Excellent\"","regulatory_note":"Multiple 2026 complaints (via BBB and consumer forums) describe cashback claims declined or delayed for months beyond the stated payment window, and slow support-ticket resolution. This is a genuine, recurring pattern reflecting retailer-side tracking-pixel reliability across the cashback industry broadly, not unique to TopCashback, but real and worth disclosing plainly."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.topcashback.co.uk/',
  false,
  'Shoppers wanting the largest cashback network',
  2,
  'https://www.topcashback.co.uk/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'compare-the-market',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'Compare the Market',
  'The highest independently corroborated customer satisfaction of the 7',
  8.4,
  4.9,
  124500,
  124500,
  0,
  '[{"type":"sky","label":"Highest customer satisfaction"}]'::jsonb,
  ARRAY['Trustpilot 4.9/5 (124,500+ reviews)', 'Rewards loyalty scheme', 'Broad insurance, energy comparison']::text[],
  ARRAY['The highest independently corroborated customer satisfaction of the 7 (4.9/5 on Trustpilot, 124,500+ reviews)', 'A "Rewards" loyalty scheme (free cinema tickets/meals with qualifying purchases) adds extra value alongside comparison']::text[],
  ARRAY['Its own site is not itself listed as a direct Ofgem Confidence Code accreditation holder — its energy comparison function is understood to be underpinned by a third-party accredited engine, worth verifying directly against Ofgem''s current list', 'Historically (pre-2020) was subject to a CMA investigation into ''most-favoured nation'' pricing clauses in home insurance, resolved by dropping the clauses']::text[],
  '{"trust":8.4,"breadth":8.2,"rating":9.8}'::jsonb,
  'The best-reviewed comparison site of the 7, with a genuinely valuable loyalty scheme.',
  '{"tool_type":"multi_category_comparison","business_model_note":"Free to use; results-based commission from suppliers (insurance, energy, etc.) when a customer switches. Part of BGL Group (majority-owned by BHL (UK) Holdings, minority stake held by CPP Investments).","key_feature_note":"Broad comparison (car/home insurance, energy, broadband) plus a \"Rewards\" loyalty scheme offering free cinema tickets/meals with qualifying purchases.","ofgem_accredited":null,"trustpilot_rating":4.9,"trustpilot_count":124500,"trustpilot_note":"uk.trustpilot.com/review/www.comparethemarket.com — \"Excellent\"; do not confuse with the separate, lower-rated Australian entity (comparethemarket.com.au)","regulatory_note":"Its direct Ofgem Confidence Code accreditation status was not conclusively confirmed in research — its energy comparison function is understood to rely on a third-party accredited engine; verify directly against Ofgem''s live accredited-sites register before relying on this. Historically (pre-2020) Compare the Market was subject to a CMA investigation into \"most-favoured nation\" pricing clauses in the home-insurance market, resolved by the company dropping the clauses — background context, not a live issue."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.comparethemarket.com/',
  false,
  'Households wanting the best-reviewed comparison experience',
  3,
  'https://www.comparethemarket.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'quidco',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'Quidco',
  'The UK''s second-largest cashback portal',
  7.6,
  4.2,
  130900,
  130900,
  0,
  '[]'::jsonb,
  ARRAY['10M+ members since 2005', '£400m+ shared cumulatively', '⚠ Payout-delay complaints — see detail']::text[],
  ARRAY['The UK''s second-largest cashback portal (10M+ members since 2005, ~£300/year average member return cited)', 'Runs its own affiliate/new-member programme through the Awin network']::text[],
  ARRAY['Owned by the same MONY Group parent as MoneySuperMarket and MoneySavingExpert', 'Similar to TopCashback, recurring complaints describe cashback payout delays (up to around a year in some cases) and tracking failures on larger purchases']::text[],
  '{"trust":7.4,"breadth":8,"rating":8.4}'::jsonb,
  'A large, long-running cashback portal — the same industry-wide payout-delay pattern applies as with TopCashback.',
  '{"tool_type":"cashback_portal","business_model_note":"Retailer commission on tracked purchases, shared with members as cashback; also earns via featured placement, promotions and a comparison-referral arm. Quidco Limited is an appointed representative of MONY Group Financial Ltd (FCA-regulated), the same parent group that owns MoneySuperMarket and MoneySavingExpert.","key_feature_note":"Cashback on everyday and larger purchases across thousands of UK retailers; average member return cited at approximately £300/year.","ofgem_accredited":null,"trustpilot_rating":4.2,"trustpilot_count":130900,"trustpilot_note":"uk.trustpilot.com/review/www.quidco.com — \"Great\"","regulatory_note":"Owned by the same MONY Group parent as MoneySuperMarket and MoneySavingExpert (also on this page). Similar to TopCashback, recurring complaints describe cashback payout delays of up to around a year in some cases and tracking failures on larger purchases — an industry-wide pattern (dependent on retailer-side tracking pixels), not unique to Quidco."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.quidco.com/',
  false,
  'Shoppers wanting a long-running, established cashback site',
  4,
  'https://www.quidco.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'uswitch-money-saving',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'Uswitch',
  'A leading energy/broadband comparison site since 2000',
  7.4,
  4.7,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Ofgem Confidence Code accredited', 'Energy/broadband/SIM-only comparison', 'Since 2000']::text[],
  ARRAY['Ofgem Confidence Code accredited for energy comparison, one of the original UK comparison sites (since 2000)', 'Multi-category tariff switching (energy, broadband, SIM-only) plus stacked cashback/voucher incentives', 'Strong Trustpilot rating (~4.7/5)']::text[],
  ARRAY['Recurring complaints about technical glitches requiring re-entry of data, and occasional mismatches between quoted and actual tariffs', 'Some users report not being clearly warned about early-exit penalties on switched contracts']::text[],
  '{"trust":8.4,"breadth":7.4,"rating":9}'::jsonb,
  'A well-established, Ofgem-accredited energy and broadband comparison specialist.',
  '{"tool_type":"energy_comparison","business_model_note":"Free to use; earns commission from energy/broadband/mobile suppliers when a user completes a switch through the site — commission does not affect the tariff price the customer pays.","key_feature_note":"Multi-category tariff switching (energy, broadband, SIM-only) plus stacked cashback/voucher incentives directly targeting bill reduction.","ofgem_accredited":true,"trustpilot_rating":4.7,"trustpilot_count":null,"trustpilot_note":"trustpilot.com/review/www.uswitch.com","regulatory_note":"No CMA or Ofgem enforcement action against Uswitch specifically was found for 2024-2026. The CMA''s late-2025 \"drip pricing\" enforcement wave did not name Uswitch."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.uswitch.com/',
  false,
  'Households wanting a dedicated energy/broadband specialist',
  5,
  'https://www.uswitch.com/gas-electricity/guides/ofgem/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'emma-cost-of-living',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'Emma',
  'Free budgeting with open-banking analysis, direct cost-of-living response',
  7.2,
  4.3,
  8800,
  8800,
  0,
  '[]'::jsonb,
  ARRAY['3M+ users', 'Open-banking spend analysis', '⚠ Billing/cancellation complaints — see detail']::text[],
  ARRAY['Aggregates 50+ UK bank/institution accounts via open banking to auto-generate a budget and flag overspend', 'Explicitly marketed around subscription-cancellation as a direct cost-of-living-crisis response', '3 million+ users']::text[],
  ARRAY['Recurring complaints describe unexpected charges after free-trial periods and difficulty cancelling paid subscriptions — a real friction point for a tool marketed around saving money', 'Free tier core budgeting, but the deepest features sit behind paid tiers (£4.99-£14.99/month)']::text[],
  '{"trust":7.6,"breadth":7,"rating":8.6}'::jsonb,
  'A genuinely useful free budgeting tool — the billing-friction complaints are worth knowing about upfront.',
  '{"tool_type":"budgeting_app","business_model_note":"Freemium subscription — free core budgeting tier, plus paid tiers (Plus £4.99, Pro £9.99, Ultimate £14.99/month). Emma Technologies Ltd is FCA-registered under the Payment Services Regulations 2017 for account-information services.","key_feature_note":"Aggregates 50+ UK bank/institution accounts via open banking, auto-generates a spending budget, flags overspend, surfaces duplicate/wasteful subscriptions, and offers auto-save — explicitly positioned as a cost-of-living-crisis response.","ofgem_accredited":null,"trustpilot_rating":4.3,"trustpilot_count":8800,"trustpilot_note":"Figures fragmented across multiple listed entities (emma-app.com and myemma.com); Google Play shows 4.3/5 (8,800+ reviews)","regulatory_note":"Recurring complaints describe unexpected charges after free-trial periods, being charged annually when expecting monthly billing, difficulty cancelling subscriptions, and features moved behind paywalls after previously being included free — a legitimate reputational/billing risk worth disclosing given the page''s cost-of-living, money-saving framing."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://emma-app.com/',
  false,
  'Users wanting free open-banking spend analysis',
  6,
  'https://www.openbanking.org.uk/apps/emma/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'chip',
  'uk',
  'cost-of-living',
  'money-saving-tools',
  'Chip',
  'AI autosave — savings held via FSCS-protected partner bank ClearBank',
  6.8,
  3.8,
  1600,
  1600,
  0,
  '[]'::jsonb,
  ARRAY['Finder Savings App of the Year 2025', 'AI-powered autosave', 'FSCS protection via ClearBank — see detail']::text[],
  ARRAY['Confirmed winner of Finder''s 2025 "Savings App Provider of the Year" award', 'AI-powered autosave analyses linked-account spending and auto-transfers "spare" amounts based on a user-selected intensity']::text[],
  ARRAY['Trustpilot rating is notably lower and more polarised than the comparison/cashback sites on this page (~3.8/5, 65% five-star but 22% one-star)', 'Chip is not itself a bank — savings sit with partner bank ClearBank, and the £120,000 FSCS protection is aggregated across all ClearBank-held Chip products, not per product']::text[],
  '{"trust":6.8,"breadth":6.4,"rating":6.8}'::jsonb,
  'An award-winning AI autosave tool — understand the FSCS-via-ClearBank structure precisely.',
  '{"tool_type":"budgeting_app","business_model_note":"Freemium app (Chip Financial Ltd, FCA-regulated); revenue from subscription tiers and from the interest/rate spread on partner-bank savings products it distributes.","key_feature_note":"Uses open banking to analyse linked-account spending and auto-transfer \"spare\" amounts into savings based on a user-selected autosave intensity.","ofgem_accredited":null,"trustpilot_rating":3.8,"trustpilot_count":1600,"trustpilot_note":"trustpilot.com — 65% five-star but 22% one-star, a polarised distribution; recurring complaints about customer-support responsiveness and occasional technical glitches","regulatory_note":"Chip is not a bank and does not hold customer deposits itself. Savings products (Instant Access, Easy Access Saver, Cash ISA, Prize Savings Account) are held via partner bank ClearBank, which is the actual FSCS-protected institution. Protection (up to £120,000, the UK-wide limit effective 1 December 2025) is aggregated across all products held at that one banking licence — a customer holding multiple Chip products on ClearBank''s licence gets one combined £120,000 ceiling, not £120,000 per product."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.getchip.uk/',
  false,
  'Savers wanting AI-automated autosave',
  7,
  'https://www.getchip.uk/how-we-protect-your-money',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
