-- Comparison Cockpit — seed UK savings-accounts (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-1): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated
-- against ukSavingsAttributesSchema. FSCS bank-deposit protection is
-- £120,000 (since 1 Dec 2025) -- all 7 candidates hold full UK banking
-- licences; Paragon shares its licence with its "Spring" brand, disclosed
-- via fscs_shared_licence_note. Every bonus/conditional rate is shown
-- alongside its real base/fallback rate and exact conditions -- no bare
-- volatile-rate claims. UK terminology uses AER throughout, never APY.
-- Marcus's weak UK Trustpilot score (2.9/5) and Shawbrook's legacy 2021
-- timeshare mis-selling case are disclosed in full.
-- Provenance: live research 2026-07-11 against official bank rate pages,
-- MoneySavingExpert, Bank of England, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'atom-bank',
  'uk',
  'savings',
  'savings-accounts',
  'Atom Bank',
  'The strongest independently corroborated customer rating researched',
  9,
  4.9,
  18000,
  18000,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Trustpilot 4.8-5.0/5', 'Reward tier up to 4.85% AER', 'Cash ISA at 4.25% AER']::text[],
  ARRAY['The strongest independently corroborated customer rating of the 7 (Trustpilot 4.8-5.0/5, ~15,800-20,500+ reviews)', 'A competitive Reward-tier rate (up to 4.75-4.85% AER) for customers who skip withdrawals in a given month', 'A genuinely competitive Easy Access Cash ISA (4.25% AER variable)']::text[],
  ARRAY['The Reward tier rate drops to the 2.50% base rate the moment any withdrawal is made in a month', 'Easy-access balance is capped at £100,000 combined']::text[],
  '{"rate":9,"protection":10,"flexibility":7.8,"support":9.8}'::jsonb,
  'The best-reviewed, most trusted savings bank in this comparison.',
  '{"max_rate_pct":4.85,"base_rate_pct":2.5,"rate_type":"conditional","rate_conditions":"Instant Saver Reward tier pays up to 4.75-4.85% AER only in months with no withdrawal; any withdrawal drops that month''s rate to the 2.50% base","cash_isa_available":true,"cash_isa_note":"Easy Access Cash ISA at 4.25% AER variable","min_deposit":1,"fscs_full":true,"trustpilot_rating":4.9,"trustpilot_count":18000,"trustpilot_note":"Sources cite 4.8-5.0/5, 15,800-20,500+ reviews","regulatory_note":"No material FCA enforcement action found for 2024-2026. An FCA clone-scam warning exists for an unrelated entity (\"Immediate Atom\") impersonating the brand — not a real Atom Bank issue."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.atombank.co.uk/savings/',
  true,
  'Savers wanting the most trusted, best-reviewed bank',
  1,
  'https://www.atombank.co.uk/savings/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'charter-savings-bank',
  'uk',
  'savings',
  'savings-accounts',
  'Charter Savings Bank',
  'The best unconditional easy-access rate — no conditions attached',
  8.7,
  4.25,
  4000,
  4000,
  0,
  '[{"type":"green","label":"Best unconditional rate"}]'::jsonb,
  ARRAY['4.21% AER, no conditions', 'Same-day access', 'Fixed Cash ISAs up to 4.46% AER']::text[],
  ARRAY['The best unconditional easy-access rate of the 7 (4.21% AER, no bonus conditions to meet)', 'Same-day access if requested before 9pm — no notice required on the easy-access product', 'A range of Fixed Cash ISAs (1/2/3-year) all paying 4.46% AER']::text[],
  ARRAY['Smaller review base than several peers (~3,900-4,200 Trustpilot reviews)', 'Award claims found in some sources ("Which? Recommended", "Moneynet Provider of the Year") could not be independently confirmed against a canonical source — not asserted as fact here']::text[],
  '{"rate":9.4,"protection":10,"flexibility":9,"support":7.6}'::jsonb,
  'The strongest genuinely unconditional easy-access rate in this comparison.',
  '{"max_rate_pct":4.46,"base_rate_pct":4.21,"rate_type":"fixed_term","rate_conditions":"4.46% AER applies to 1/2/3-year Fixed Cash ISAs (funds locked for the term); the unconditional Easy Access rate (4.21% AER) requires no conditions at all and is the strongest such rate in this comparison","cash_isa_available":true,"cash_isa_note":"1/2/3-year Fixed Cash ISAs at 4.46% AER; Easy Access Cash ISA at 4.21% AER","min_deposit":1000,"fscs_full":true,"trustpilot_rating":4.25,"trustpilot_count":4000,"trustpilot_note":"\"Great\" rating, sources cite 4.2-4.3/5, ~3,900-4,200 reviews","regulatory_note":"No FCA enforcement action found. Some sources reference a \"Which? Recommended Provider for Savings 2025\" and \"Moneynet Cash ISA Provider of the Year 2026\" award, but neither could be independently confirmed against a canonical which.co.uk or Moneynet source at research time — these are not asserted as fact on this page pending direct verification."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.chartersavingsbank.co.uk/',
  false,
  'Savers wanting the best rate with zero conditions',
  2,
  'https://www.chartersavingsbank.co.uk/ataglance',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'shawbrook-bank',
  'uk',
  'savings',
  'savings-accounts',
  'Shawbrook Bank',
  'A long-running UK best-buy fixture since 2017',
  8.3,
  4.65,
  15000,
  15000,
  0,
  '[{"type":"sky","label":"Best long-running fixed-rate option"}]'::jsonb,
  ARRAY['Best-buy fixture since 2017', 'Bonus Easy Access 4.13% AER', 'Next-working-day access']::text[],
  ARRAY['A long-running fixture of UK savings best-buy tables since 2017', 'Strong Trustpilot rating (4.6-4.7/5, "Excellent")', 'A competitive Bonus Easy Access rate (4.13% AER, including a 12-month fixed bonus) with next-working-day access, no limits']::text[],
  ARRAY['A legacy 2021 timeshare mis-selling case (unsecured loans tied to Club La Costa/Diamond Resorts) — the Financial Ombudsman ruled for affected customers, upheld on High Court judicial review in 2023', 'Standard Easy Access base rate (2.70% AER) is meaningfully lower than the Bonus tier']::text[],
  '{"rate":8.6,"protection":10,"flexibility":8.6,"support":8.6}'::jsonb,
  'A consistently well-reviewed, long-running best-buy fixture — with disclosed legacy litigation.',
  '{"max_rate_pct":4.3,"base_rate_pct":2.7,"rate_type":"fixed_term","rate_conditions":"4.30% AER on the 1-year Fixed Cash ISA (funds locked for the term); a separate Bonus Easy Access account pays 4.13% AER (includes a fixed 12-month bonus), while the standard unconditional Easy Access rate is 2.70% AER","cash_isa_available":true,"cash_isa_note":"Easy Access Cash ISA at 4.00% AER; 1-year Fixed Cash ISA at 4.30% AER","min_deposit":1000,"fscs_full":true,"trustpilot_rating":4.65,"trustpilot_count":15000,"trustpilot_note":"Sources cite 4.6-4.7/5, 10,000-21,000 reviews depending on source","regulatory_note":"A legacy timeshare mis-selling case (unsecured loans connected to Club La Costa/Diamond Resorts) saw the Financial Ombudsman rule in favour of affected customers in 2021, upheld on High Court judicial review in 2023. This predates the 2024-2026 research window, but related claims are reportedly still being processed — disclosed for transparency. Separately, Shawbrook Group plc completed an LSE main-market IPO on 4 November 2025 (~£2bn valuation), and as of May 2026 was reportedly weighing a merger involving Aldermore — corporate context, not a compliance matter."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.shawbrook.co.uk/savings/',
  false,
  'Savers wanting a consistently well-reviewed bank',
  3,
  'https://www.shawbrook.co.uk/savings/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'zopa-bank',
  'uk',
  'savings',
  'savings-accounts',
  'Zopa Bank',
  'A well-known challenger bank with a competitive Cash ISA',
  7.8,
  4.2,
  29000,
  29000,
  0,
  '[]'::jsonb,
  ARRAY['Standalone UK bank since 2020', 'Cash ISA at 3.25% AER', 'Biscuit-boosted rate up to 4.75%']::text[],
  ARRAY['A standalone, full UK banking licence since 2020', 'A competitive Cash ISA (Access ISA at 3.25% AER)', 'A boosted rate (up to 4.75% AER) for customers holding an active Zopa "Biscuit" current account']::text[],
  ARRAY['Base easy-access rate (2.95% AER) is unremarkable without the Biscuit boost', 'Combined balance across pots is capped at £250,000']::text[],
  '{"rate":8,"protection":10,"flexibility":8.4,"support":7.4}'::jsonb,
  'A solid, well-known challenger bank — the Biscuit-boosted rate is the real draw.',
  '{"max_rate_pct":4.75,"base_rate_pct":2.95,"rate_type":"conditional","rate_conditions":"Up to 4.75% AER requires holding an active Zopa \"Biscuit\" current account for 12 months; the unconditional Access pot rate is 2.95% AER","cash_isa_available":true,"cash_isa_note":"Access ISA at 3.25% AER variable","min_deposit":1,"fscs_full":true,"trustpilot_rating":4.2,"trustpilot_count":29000,"trustpilot_note":"Sources showed variance (4.0-4.5/5, 22,000-36,000+ reviews) — \"Excellent\" band, verify live before relying on an exact figure","regulatory_note":"Zopa has publicly pushed back on the FCA''s motor-finance redress scheme design, setting aside £7.9m in provisions and describing the retrospective approach as \"penalising\" (January 2026) — a genuine, disclosed regulatory friction point concerning its motor-finance business specifically, not the savings products on this page."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.zopa.com/savings',
  false,
  'Existing Zopa/Biscuit customers wanting a boosted rate',
  4,
  'https://www.zopa.com/savings',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'marcus-goldman-sachs',
  'uk',
  'savings',
  'savings-accounts',
  'Marcus by Goldman Sachs',
  'A competitive MSE-listed fixed rate — with a weak UK Trustpilot score disclosed',
  6.8,
  2.9,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['MSE top pick: 4.9% AER (1-yr fixed)', '~1M UK savers', '⚠ Weak UK Trustpilot (2.9/5) — see detail']::text[],
  ARRAY['MoneySavingExpert''s current top pick for a 1-year fixed-rate bond (4.9% AER)', 'Backed by Goldman Sachs'' scale, with approximately 1 million UK savers', 'Offers a Cash ISA alongside its easy-access and fixed products']::text[],
  ARRAY['A genuinely weak UK-specific Trustpilot score (2.9/5), with 2025 complaints describing sudden account closures', 'Easy-access rate (3.75% AER) is unremarkable without locking into the fixed-term product']::text[],
  '{"rate":8.4,"protection":10,"flexibility":6.4,"support":3.4}'::jsonb,
  'A competitive fixed rate from a major name — the disclosed UK service complaints are real, weigh them.',
  '{"max_rate_pct":4.9,"base_rate_pct":3.75,"rate_type":"fixed_term","rate_conditions":"4.90% AER on the 1-year fixed-rate bond (funds locked for the term, MoneySavingExpert''s current top pick in that category); the unconditional Online Savings Account pays 3.75% AER variable (includes a 0.49% 12-month bonus)","cash_isa_available":true,"cash_isa_note":"Cash ISA offered — current AER not independently confirmed at research time, verify on-site","min_deposit":1,"fscs_full":true,"trustpilot_rating":2.9,"trustpilot_count":null,"trustpilot_note":"uk.trustpilot.com/review/www.marcus.co.uk — notably weak for a major bank","regulatory_note":"Multiple 2025 Trustpilot/Resolver complaints describe sudden account closures without notice and frozen funds. An FCA clone-scam warning exists for firms impersonating Marcus — not a real Marcus issue. Parent entity Goldman Sachs International was previously fined £34.3m by the FCA for transaction-reporting failures relating to its wholesale business — not confirmed as connected to the retail Marcus savings product, disclosed as parent-company context only."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.marcus.co.uk/uk/en/savings',
  false,
  'Savers wanting a competitive fixed rate from a major name',
  5,
  'https://www.marcus.co.uk/uk/en/savings',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'paragon-bank',
  'uk',
  'savings',
  'savings-accounts',
  'Paragon Bank',
  'A FTSE 250-listed bank — but a genuinely low headline easy-access rate',
  6.4,
  4.7,
  10500,
  10500,
  0,
  '[]'::jsonb,
  ARRAY['FTSE 250-listed (Paragon Banking Group)', 'Shares licence with "Spring" brand', 'Easy-access rate only 1.50% AER']::text[],
  ARRAY['A FTSE 250-listed group with a strong Trustpilot rating (4.7/5)', 'A wide range of Cash ISA products (1-year Fixed 4.00% AER, 14-month Fixed 4.30% AER)', 'A 120-Day Notice account paying 3.75% AER for savers who can plan ahead']::text[],
  ARRAY['The standard Easy Access rate (1.50% AER) is genuinely low, the weakest headline easy-access rate of the 7', 'Shares its banking licence with its "Spring" savings brand — combined balances across both count toward the same £120,000 FSCS cap']::text[],
  '{"rate":6,"protection":9.6,"flexibility":6.4,"support":8.4}'::jsonb,
  'Strong fixed and ISA products — but the headline easy-access rate is genuinely uncompetitive.',
  '{"max_rate_pct":4.25,"base_rate_pct":1.5,"rate_type":"fixed_term","rate_conditions":"4.25% AER on the 1-year fixed-rate bond (funds locked for the term); the standard unconditional Easy Access rate is only 1.50% AER — a Triple Access account reaches up to 3.20% AER but limits withdrawals to 3/year before the rate is cut, and a 120-Day Notice account pays 3.75% AER","cash_isa_available":true,"cash_isa_note":"1-year Fixed Cash ISA at 4.00% AER; 14-month Fixed Cash ISA at 4.30% AER; Easy Access Cash ISA only 1.50% AER","min_deposit":500,"fscs_full":true,"fscs_shared_licence_note":"Paragon Bank shares its banking licence with its \"Spring\" savings brand — a customer''s combined balance across both counts toward the same £120,000 FSCS limit","trustpilot_rating":4.7,"trustpilot_count":10500,"trustpilot_note":"Sources cite 4.7/5, ~10,000-11,500 reviews","regulatory_note":"Parent Paragon Banking Group has disclosed exposure to the industry-wide FCA motor-finance redress scheme (sector-wide estimated £9-12bn), which lenders were reportedly considering legally challenging as of March 2026 — this is sector/group-level exposure, not confirmed misconduct specific to Paragon''s savings business."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.paragonbank.co.uk/savings',
  false,
  'Savers wanting fixed-term/ISA products, not easy access',
  6,
  'https://www.paragonbank.co.uk/savings',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'chase-uk',
  'uk',
  'savings',
  'savings-accounts',
  'Chase UK',
  'A well-known name — but no Cash ISA offered',
  6,
  4.1,
  15000,
  15000,
  0,
  '[]'::jsonb,
  ARRAY['Boosted Saver 4.5% AER (12mo, new customers)', 'Backed by J.P. Morgan', '⚠ No Cash ISA offered']::text[],
  ARRAY['A competitive Boosted Saver rate (4.5% AER) for new customers in their first 12 months', 'Backed by J.P. Morgan Europe Ltd — a large, well-capitalized institution']::text[],
  ARRAY['Does not currently offer a Cash ISA — a genuine gap for tax-free-savings-focused savers', 'The Boosted Saver rate reverts to the Standard Saver rate (2.25% AER) after 12 months', 'Only easy-access/round-up savings — no 1-year fixed-rate bond product']::text[],
  '{"rate":6.6,"protection":10,"flexibility":8.8,"support":5.6}'::jsonb,
  'A competitive introductory rate — but no Cash ISA, a real limitation for many UK savers.',
  '{"max_rate_pct":4.5,"base_rate_pct":2.25,"rate_type":"intro","rate_conditions":"4.50% AER on the Boosted Saver applies for 12 months to new customers only (tracks BoE base rate minus 1.50%, updated ~5 business days after MPC changes), reverting to the 2.25% AER Standard Saver rate afterward","cash_isa_available":false,"cash_isa_note":"Not offered as of July 2026","min_deposit":1,"fscs_full":true,"trustpilot_rating":4.1,"trustpilot_count":15000,"trustpilot_note":"Sources disagree significantly (3.5-4.7/5) — treat as mixed, verify the live score before relying on a specific figure","regulatory_note":"No FCA enforcement action found for 2024-2026 beyond a clone-firm scam warning (fraud impersonating Chase, not an issue with Chase itself)."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.chase.co.uk/',
  false,
  'New customers wanting a 12-month boosted rate',
  7,
  'https://www.chase.co.uk/gb/en/product/chase-saver-account',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
