-- Comparison Cockpit — seed AU business bank accounts (market='au', topic='business-bank-accounts').
-- Visit-only launch (AU/CA/UK rollout, Stage 1 Slice AU-1): affiliate_link_id NULL,
-- is_affiliate=false, review_slug NULL, external_url = provider homepage.
-- Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- lib/comparison/topics/au/business-bank-accounts.ts (auBusinessBankAttributesSchema).
-- Provenance: docs/superpowers/specs/2026-07-10-best-x-au-ca-uk-country-shortlist.md
-- (AU section 6) + live research 2026-07-10 (official pricing/PDS pages, APRA
-- ADI register, Trustpilot/ProductReview).

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks,
  monthly_fee, fx_fee_pct, atm_fee,
  badges, chips, pros, cons, sub_scores,
  card_network, wire_transfers, fdic_coverage, apps, verdict,
  has_no_monthly_fee, has_free_atm, has_no_fx_fee, has_cashback, has_bonus,
  has_sub_accounts, has_interest, has_apple_pay,
  entity_types, supports_cash_deposits, supports_intl_wires, has_bookkeeping, has_lending, integrations,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL, 'tyro-business', 'au', 'business-banking', 'business-bank-accounts', 'Tyro', 'Fee-free business account from a real Australian bank',
  9.2, 4.0, 553, 553,
  0, 0, 0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['$0 account fees','Same-day EFTPOS settlement','Xero & MYOB feeds']::text[],
  ARRAY['Real APRA-licensed bank with FCS protection to A$250,000','Same-day settlement for EFTPOS transactions, 7 days a week','Free Xero and MYOB bank feeds plus multiple sub-accounts']::text[],
  ARRAY['No international payments or multi-currency support','Strongest value when paired with a Tyro EFTPOS terminal']::text[],
  '{"fees":9.8,"features":8.5,"ux":8.8,"support":8.5}'::jsonb,
  'Visa Debit', 'Domestic only — no international payments', 'FCS protected — to A$250,000 (APRA ADI)', '[]'::jsonb,
  'A genuinely fee-free business account from a licensed Australian bank — the strongest all-round pick for everyday transacting.',
  true, false, false, false, false,
  true, false, false,
  ARRAY['sole-trader','company']::text[], false, false, true, false, ARRAY['xero','myob']::text[],
  '{"adi_status":true,"fcs_protected":true,"protection_note":"","interest_rate_pct":0,"has_transaction_account":true,"afsl_or_licence":"AFSL 471951","setup_time_note":"Online in under 2 minutes","trustpilot_rating":4.0,"trustpilot_count":553}'::jsonb,
  'official', 'high',
  false, NULL, 'https://www.tyro.com/products/business-banking/transaction-account/', true, 'Everyday business banking', 1,
  'https://www.tyro.com/products/business-banking/transaction-account/', DATE '2026-07-10', true
),
(
  NULL, 'airwallex-business', 'au', 'business-banking', 'business-bank-accounts', 'Airwallex', 'Global business account for international payments',
  8.8, 3.7, 2469, 2469,
  0, 0.5, 0,
  '[{"type":"sky","label":"Best for international"}]'::jsonb,
  ARRAY['20+ currency Global Accounts','FX from 0.5% over interbank','Free local transfers to 120+ destinations']::text[],
  ARRAY['Accounts in 20+ currencies, transact like a local in 70+ countries','$0/month realistically achievable (A$5k deposit or A$10k balance)','Multi-currency cards + Xero/QuickBooks/NetSuite integrations']::text[],
  ARRAY['Not an ADI — no FCS deposit protection, only safeguarding/bank guarantee','Trustpilot complaints about account freezes during KYC review']::text[],
  '{"fees":8.6,"features":9.4,"ux":8.5,"support":7.6}'::jsonb,
  'Multi-currency Visa/Mastercard', 'Global Accounts in 20+ currencies; local transfers to 120+ destinations; FX from 0.5% over interbank', 'Not FCS-protected — funds held via segregated ADI accounts + bank guarantee (GLAS Nominees trust)', '[]'::jsonb,
  'The strongest choice for businesses that pay or get paid internationally, at the cost of bank-grade deposit protection.',
  true, false, false, false, false,
  true, false, false,
  ARRAY['sole-trader','company']::text[], false, true, false, false, ARRAY['xero','quickbooks','netsuite']::text[],
  '{"adi_status":false,"fcs_protected":false,"protection_note":"Funds held on segregated ADI accounts plus a bank guarantee, held in trust by GLAS Nominees — not a government-guaranteed deposit.","interest_rate_pct":0,"has_transaction_account":true,"afsl_or_licence":"AFSL 487221","setup_time_note":"Online application ~15 minutes; approval 1-3 business days","trustpilot_rating":3.7,"trustpilot_count":2469}'::jsonb,
  'official', 'high',
  false, NULL, 'https://www.airwallex.com/au/business-account', false, 'International payments', 2,
  'https://www.airwallex.com/au/pricing', DATE '2026-07-10', true
),
(
  NULL, 'zeller-business', 'au', 'business-banking', 'business-bank-accounts', 'Zeller', 'The 5-minute free business account with a card and EFTPOS built in',
  8.6, 3.9, 283, 283,
  0, 0, 0,
  '[{"type":"green","label":"Fastest setup"}]'::jsonb,
  ARRAY['Open in under 5 minutes','Unlimited sub-accounts','Up to 4.95% p.a. on savings']::text[],
  ARRAY['Opens in under 5 minutes, completely free including the debit card','Unlimited named sub-accounts plus up to 4.95% p.a. in Zeller Savings','All-in-one with EFTPOS terminal, invoicing and Xero integration']::text[],
  ARRAY['Not an ADI — funds held in trust at Cuscal, explicitly NOT FCS-protected','Trustpilot reports of settlement holds during verification']::text[],
  '{"fees":9.5,"features":8.8,"ux":9.2,"support":7.8}'::jsonb,
  'Zeller Debit Mastercard', 'Domestic only — AUD, no international payments or multi-currency', 'Not FCS-protected — funds held on trust at Cuscal Limited (APRA ADI), not a government-guaranteed deposit', '[]'::jsonb,
  'The fastest, simplest free account for sole traders and small businesses that accept the non-ADI trust structure.',
  true, false, false, false, false,
  true, true, false,
  ARRAY['sole-trader','company']::text[], false, false, false, false, ARRAY['xero']::text[],
  '{"adi_status":false,"fcs_protected":false,"protection_note":"Funds held in a client segregated moneys account on bare trust at Cuscal Limited (an APRA ADI) — not a government-guaranteed deposit.","interest_rate_pct":4.95,"has_transaction_account":true,"afsl_or_licence":"AFSL 534281","setup_time_note":"Under 5 minutes, fully online","trustpilot_rating":3.9,"trustpilot_count":283}'::jsonb,
  'official', 'high',
  false, NULL, 'https://www.myzeller.com/au/business-transaction-account', false, 'Sole traders & fast setup', 3,
  'https://www.myzeller.com/au/business-transaction-account', DATE '2026-07-10', true
),
(
  NULL, 'wise-business-au', 'au', 'business-banking', 'business-bank-accounts', 'Wise Business', 'Multi-currency account with the real mid-market exchange rate',
  8.9, 4.3, 295000, 295000,
  0, 0.63, 0,
  '[{"type":"sky","label":"Best FX rate"}]'::jsonb,
  ARRAY['Mid-market exchange rate','Kept in 40+ currencies','4.3★ from ~295,000 Trustpilot reviews']::text[],
  ARRAY['Mid-market rate with no markup, transfers from 0.63%','Local account details in 22 currencies for receiving payments','Exceptional trust record: 4.3★ from ~295,000 Trustpilot reviews']::text[],
  ARRAY['A$65 one-off setup fee and no FCS protection (safeguarding model)','Not a full bank account — no BPAY receiving, no lending']::text[],
  '{"fees":8.8,"features":9.0,"ux":9.2,"support":8.6}'::jsonb,
  'Wise multi-currency card', 'Local account details in 22 currencies; hold 40+ currencies; cards usable in 231 countries', 'Not FCS-protected — funds "safeguarded" across a diversified group of financial institutions, not a government-guaranteed deposit', '[]'::jsonb,
  'The best exchange-rate value for freelancers and firms with international clients or suppliers.',
  true, false, false, false, false,
  true, false, false,
  ARRAY['sole-trader','company']::text[], false, true, false, false, ARRAY['xero']::text[],
  '{"adi_status":false,"fcs_protected":false,"protection_note":"Funds are safeguarded across a diversified group of financial institutions — not a government-guaranteed deposit.","interest_rate_pct":0,"has_transaction_account":true,"afsl_or_licence":"AFSL 513764","setup_time_note":"Online registration in minutes; verification typically a few business days","trustpilot_rating":4.3,"trustpilot_count":295000}'::jsonb,
  'official', 'high',
  false, NULL, 'https://wise.com/au/business/', false, 'Freelancers & international clients', 4,
  'https://wise.com/au/pricing/business', DATE '2026-07-10', true
),
(
  NULL, 'judo-business-savings', 'au', 'business-banking', 'business-bank-accounts', 'Judo Bank Business Savings', 'Where to park business cash for up to 4.60% p.a.',
  8.0, 4.6, 2000, 2000,
  0, 0, 0,
  '[{"type":"green","label":"Best for idle cash"}]'::jsonb,
  ARRAY['Up to 4.60% p.a. on balances to A$250k','No deposit conditions','APRA ADI with FCS protection']::text[],
  ARRAY['4.60% p.a. on business balances up to A$250,000, no deposit conditions','Genuine APRA-licensed bank with FCS protection to A$250,000','SME-specialist with Australian-based phone support (4.6★ ProductReview)'],
  ARRAY['No transaction account or debit card — savings/term deposits only','Internet banking reportedly unusable outside AU/NZ, no international payments'],
  '{"fees":9.0,"features":6.5,"ux":8.0,"support":8.8}'::jsonb,
  NULL, 'Domestic only', 'FCS protected — to A$250,000 (APRA ADI)', '[]'::jsonb,
  'Not a transaction account — the highest-yield place to park a business cash buffer.',
  true, false, false, false, false,
  false, true, false,
  ARRAY['sole-trader','company']::text[], false, false, false, false, ARRAY[]::text[],
  '{"adi_status":true,"fcs_protected":true,"protection_note":"","interest_rate_pct":4.60,"has_transaction_account":false,"afsl_or_licence":"AFSL & Australian Credit Licence 501091","setup_time_note":"Online application","trustpilot_rating":null,"trustpilot_count":null}'::jsonb,
  'official', 'medium',
  false, NULL, 'https://www.judo.bank/savings-accounts/business-savings-account/', false, 'Parking business cash reserves', 5,
  'https://www.judo.bank/savings-accounts/business-savings-account/', DATE '2026-07-10', true
),
(
  NULL, 'anz-business-essentials', 'au', 'business-banking', 'business-bank-accounts', 'ANZ Business Essentials', 'Big-four $0 digital account with full branch access',
  7.6, 1.5, 740, 740,
  0, 0, 2.50,
  '[]'::jsonb,
  ARRAY['$0 with digital-only usage','Full branch & cash network','Xero discount included']::text[],
  ARRAY['$0 account-keeping fee for unlimited digital transactions','Full big-four infrastructure: branches, cash deposits, international wires, lending','FCS-protected plus a free Visa Debit card and Xero discount'],
  ARRAY['A$2.50 per counter-assisted or cheque transaction — costly for cash-heavy businesses','Very weak service ratings (1.5★ Trustpilot): long wait times, account holds'],
  '{"fees":8.4,"features":8.8,"ux":6.0,"support":4.0}'::jsonb,
  'ANZ Business Visa Debit', 'International wires available via ANZ Internet Banking (fees + FX margin apply)', 'FCS protected — to A$250,000 (APRA ADI)', '[]'::jsonb,
  'Big-four reliability at $0 for digital-only banking — weigh the poor service ratings against the branch network.',
  true, false, false, false, false,
  true, false, false,
  ARRAY['sole-trader','company']::text[], true, true, false, true, ARRAY['xero']::text[],
  '{"adi_status":true,"fcs_protected":true,"protection_note":"","interest_rate_pct":0,"has_transaction_account":true,"afsl_or_licence":"AFSL 234527","setup_time_note":"Online/app in about 10 minutes","trustpilot_rating":1.5,"trustpilot_count":740}'::jsonb,
  'official', 'medium',
  false, NULL, 'https://www.anz.com.au/business/accounts/transaction-accounts/business-essentials/', false, 'Businesses needing branch/cash access', 6,
  'https://www.anz.com.au/content/dam/anzcomau/documents/pdf/transaction-accounts-fees-charges.pdf', DATE '2026-07-10', true
),
(
  NULL, 'nab-business-everyday', 'au', 'business-banking', 'business-bank-accounts', 'NAB Business Everyday', 'Australia''s largest business bank, free for digital banking',
  7.5, 1.4, 517, 517,
  0, 0, 3.00,
  '[]'::jsonb,
  ARRAY['$0 monthly-fee option','6 months free Xero + $300 gift card','Largest business-lending network']::text[],
  ARRAY['Genuine $0 account, opened online in about 10 minutes','Strong onboarding: 6 months free Xero plus a $300 gift card','Australia''s largest business-banking network: branches, credit, merchant services'],
  ARRAY['A$3 per counter-assisted transaction or cheque — unsuited to cash-heavy businesses','Consistently negative service reviews (517 Trustpilot reviews, largely 1-star tenor)'],
  '{"fees":8.2,"features":8.6,"ux":6.2,"support":3.8}'::jsonb,
  'NAB Business Visa Debit', 'International wires available via NAB Internet Banking (fees + FX margin apply)', 'FCS protected — to A$250,000 (APRA ADI)', '[]'::jsonb,
  'The largest network in Australian business banking — a solid $0 digital option if you can tolerate weak service reviews.',
  true, false, false, false, false,
  true, false, false,
  ARRAY['sole-trader','company']::text[], true, true, false, true, ARRAY['xero']::text[],
  '{"adi_status":true,"fcs_protected":true,"protection_note":"","interest_rate_pct":0,"has_transaction_account":true,"afsl_or_licence":"AFSL 230686","setup_time_note":"Online in as little as 10 minutes","trustpilot_rating":1.4,"trustpilot_count":517}'::jsonb,
  'official', 'medium',
  false, NULL, 'https://www.nab.com.au/business/business-bank-accounts/transaction-accounts/no-monthly-fee-business-account', false, 'Digital-first with big-bank backing', 7,
  'https://www.nab.com.au/important-information/business/banking-fees-charges', DATE '2026-07-10', true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  tagline = EXCLUDED.tagline,
  score = EXCLUDED.score,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  fx_fee_pct = EXCLUDED.fx_fee_pct,
  atm_fee = EXCLUDED.atm_fee,
  badges = EXCLUDED.badges,
  chips = EXCLUDED.chips,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores,
  card_network = EXCLUDED.card_network,
  wire_transfers = EXCLUDED.wire_transfers,
  fdic_coverage = EXCLUDED.fdic_coverage,
  apps = EXCLUDED.apps,
  verdict = EXCLUDED.verdict,
  has_no_monthly_fee = EXCLUDED.has_no_monthly_fee,
  has_free_atm = EXCLUDED.has_free_atm,
  has_no_fx_fee = EXCLUDED.has_no_fx_fee,
  has_cashback = EXCLUDED.has_cashback,
  has_bonus = EXCLUDED.has_bonus,
  has_sub_accounts = EXCLUDED.has_sub_accounts,
  has_interest = EXCLUDED.has_interest,
  has_apple_pay = EXCLUDED.has_apple_pay,
  entity_types = EXCLUDED.entity_types,
  supports_cash_deposits = EXCLUDED.supports_cash_deposits,
  supports_intl_wires = EXCLUDED.supports_intl_wires,
  has_bookkeeping = EXCLUDED.has_bookkeeping,
  has_lending = EXCLUDED.has_lending,
  integrations = EXCLUDED.integrations,
  attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type,
  confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate,
  review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url,
  is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for,
  display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url,
  data_verified_at = EXCLUDED.data_verified_at,
  active = EXCLUDED.active;
