-- Comparison Cockpit — seed UK investing-apps (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-1): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated
-- against ukInvestingAppsAttributesSchema. FSCS investment protection is
-- £85,000 (UNCHANGED) -- a different scheme from the £120,000 UK
-- bank-deposit limit used on the savings/business-banking pages, never
-- conflated. Trading 212 tops the Which? 2026 survey but is explicitly NOT
-- a "Which? Recommended Provider" due to its CFD-arm risk warning --
-- disclosed, not glossed over. Freetrade's 2022 FCA Second Supervisory
-- Notice (predating its 2025 IG Group acquisition) and HL's disputed 2026
-- ransomware claim are disclosed in full.
-- Provenance: live research 2026-07-11 against official pricing pages,
-- Which? 2026 survey, FCA Register, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'aj-bell',
  'uk',
  'personal-finance',
  'investing-apps',
  'AJ Bell',
  'The highest raw Which? customer-satisfaction score of any platform tested',
  9.1,
  4.9,
  15459,
  15459,
  0.25,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Which? Recommended Provider (77%)', 'Highest satisfaction score (81%)', 'Trustpilot 4.9/5']::text[],
  ARRAY['The highest raw customer-satisfaction score (81%) of any platform in the Which? 2026 survey', 'A 2026 Which? Recommended Provider — #2 overall (77%)', 'Strongest independently corroborated review score in this comparison (Trustpilot 4.9/5, 15,459 reviews)']::text[],
  ARRAY['0.25% platform fee, capped at £3.50/month — not the cheapest option for very large portfolios', '£5.00 dealing fee per trade — higher than interactive investor''s £3.99']::text[],
  '{"fees":8.6,"universe":8.8,"ux":9.2,"support":9.4}'::jsonb,
  'The highest-satisfaction, most trusted platform in this comparison.',
  '{"fee_structure":"percentage","fee_note":"0.25% platform fee, capped at £3.50/month (cap reached around £17,000)","dealing_fee_gbp":5,"investment_universe_note":"~8,200 shares, 4,000+ funds, 3,400 ETFs, 450 trusts, 134 bonds/gilts, 24 markets","fscs_protected":true,"which_survey_note":"Which? 2026 — #2 overall (77%), Recommended Provider, highest raw satisfaction score (81%)","trustpilot_rating":4.9,"trustpilot_count":15459,"trustpilot_note":"trustpilot.com/review/ajbell.co.uk","regulatory_note":""}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.ajbell.co.uk/',
  true,
  'Investors wanting the highest-satisfaction platform',
  1,
  'https://www.ajbell.co.uk/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'trading-212',
  'uk',
  'personal-finance',
  'investing-apps',
  'Trading 212',
  'The lowest cost structure — £0 platform fee, £0 dealing',
  9,
  4.6,
  0,
  0,
  0,
  0,
  '[{"type":"green","label":"Lowest cost"}]'::jsonb,
  ARRAY['£0 platform fee, £0 dealing', 'Which? #1 overall (83%)', '⚠ Not a Which? Recommended Provider — see detail']::text[],
  ARRAY['No platform fee and no dealing commission — only a 0.15% FX fee on non-GBP trades', 'Topped the Which? 2026 investment platform survey outright (83% overall, 100% fees score)', 'A new 2026 SIPP product launched with the same £0 platform/dealing fee structure']::text[],
  ARRAY['Explicitly NOT a "Which? Recommended Provider" — Trading 212''s FCA authorisation covers CFD trading, carrying the standard high-risk retail-investor warning', 'Multiple Financial Ombudsman complaints exist over account-freeze/re-verification issues, though FOS decisions reviewed did not uphold them']::text[],
  '{"fees":10,"universe":7.6,"ux":8.8,"support":7.4}'::jsonb,
  'The lowest-cost platform in this comparison — understand the CFD-arm risk-warning nuance first.',
  '{"fee_structure":"zero_platform","fee_note":"£0 platform fee, £0 dealing commission; only a 0.15% FX fee applies on non-GBP trades","dealing_fee_gbp":0,"investment_universe_note":"Thousands of UK/US/EU shares and ETFs; new 2026 SIPP product (waitlist rollout, 75,000+ beta sign-ups)","fscs_protected":true,"which_survey_note":"Which? 2026 — #1 overall (83%), perfect 100% fees score, but explicitly NOT a Which? Recommended Provider due to the standard CFD-arm risk warning its FCA authorisation carries","trustpilot_rating":4.6,"trustpilot_count":null,"trustpilot_note":"Review count not independently confirmed at research time","regulatory_note":"Multiple Financial Ombudsman Service complaints exist over account freezes/re-verification (KYC) — the FOS decisions reviewed did not uphold these complaints, finding Trading 212 acted within its terms and AML/KYC obligations. Separately, an unrelated \"TRADING212\" clone-scam entity has been FCA-flagged — not the real firm."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.trading212.com/',
  false,
  'Cost-conscious investors okay with the CFD warning',
  2,
  'https://www.trading212.com/isa',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'investengine',
  'uk',
  'personal-finance',
  'investing-apps',
  'InvestEngine',
  'The best pick for pure ETF portfolio-builders',
  8.7,
  4.6,
  0,
  0,
  0,
  0,
  '[{"type":"sky","label":"Best for ETF portfolios"}]'::jsonb,
  ARRAY['£0 platform fee (DIY)', 'Which? Recommended, 3rd year running', '"Great Value" badge, 2nd year']::text[],
  ARRAY['No platform fee on the DIY plan, commission-free ETF dealing', 'A Which? Recommended Provider for the 3rd consecutive year, plus a "Great Value" badge for the 2nd year', 'Strong Trustpilot rating (4.6-4.7/5)']::text[],
  ARRAY['~830 ETFs only — no individual stocks, the narrowest investment universe of the 7 candidates', 'Managed plan (as opposed to DIY) carries an additional ~0.25% fee']::text[],
  '{"fees":9.6,"universe":5.6,"ux":8.6,"support":8.6}'::jsonb,
  'The best-value, most-trusted choice for ETF-only portfolio building — not for stock-pickers.',
  '{"fee_structure":"zero_platform","fee_note":"£0 platform fee on the DIY plan; the Managed plan adds an additional fee (~0.25%)","dealing_fee_gbp":0,"investment_universe_note":"~830 ETFs only — no individual stocks; an ETF/portfolio-builder tool, not a stock-picker''s platform","fscs_protected":true,"which_survey_note":"Which? 2026 — #3 overall (76%), Recommended Provider (3rd consecutive year), \"Great Value\" badge (2nd year)","trustpilot_rating":4.6,"trustpilot_count":null,"trustpilot_note":"Sources cite 4.6-4.7/5; exact review count not independently confirmed at research time","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.investengine.com/',
  false,
  'Investors wanting a low-cost, ETF-only portfolio',
  3,
  'https://www.investengine.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'interactive-investor',
  'uk',
  'personal-finance',
  'investing-apps',
  'interactive investor',
  'A flat monthly fee — cheaper than a percentage fee at larger balances',
  8.2,
  4.5,
  0,
  0,
  0.12,
  0,
  '[]'::jsonb,
  ARRAY['Flat £4.99-11.99/month fee', 'Cheapest per-trade dealing (£3.99)', '40,000+ combined instruments']::text[],
  ARRAY['A flat monthly fee that stays the same regardless of balance — genuinely cheaper than percentage-fee platforms above roughly £17,000-20,000', 'The cheapest per-trade dealing commission of the "full-service" platforms (£3.99)', 'A vast combined universe of 40,000+ instruments across 500,000+ investors']::text[],
  ARRAY['The flat fee makes small ISAs relatively expensive — Which? gave it the weakest fees score (45%) of the platforms reviewed', 'Which? 2026 — #8 overall (64%), the lowest-ranked platform in this comparison']::text[],
  '{"fees":6.6,"universe":9.6,"ux":8,"support":7.8}'::jsonb,
  'The best choice for large portfolios — a flat fee that becomes expensive on smaller ones.',
  '{"fee_structure":"flat_monthly","fee_note":"Flat £4.99-11.99/month depending on tier (not a % of assets). Shown here as an effective 0.12% on a £50,000 reference portfolio — the real cost is FIXED regardless of balance, making ii cheaper than percentage-fee platforms above roughly £17,000-20,000 and more expensive below that threshold.","dealing_fee_gbp":3.99,"investment_universe_note":"40,000+ combined instruments; 3,000+ funds, 1,000+ ETFs, 37 bonds/59 gilts","fscs_protected":true,"which_survey_note":"Which? 2026 — #8 overall (64%), weakest fees score (45%) of the platforms reviewed — the flat fee structure penalises smaller ISAs specifically","trustpilot_rating":4.5,"trustpilot_count":null,"trustpilot_note":"Review count not independently confirmed at research time","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.ii.co.uk/',
  false,
  'Larger portfolios where a flat fee beats a percentage',
  4,
  'https://www.ii.co.uk/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'freetrade',
  'uk',
  'personal-finance',
  'investing-apps',
  'Freetrade',
  'Now a wholly owned IG Group subsidiary — with a disclosed 2022 FCA notice',
  7.6,
  4.15,
  7300,
  7300,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Fully owned by IG Group since April 2025', 'Which? #4 overall (76%)', '⚠ 2022 FCA supervisory notice — see detail']::text[],
  ARRAY['Commission-free equity dealing across a growing universe, backed by IG Group''s scale since its April 2025 acquisition', 'Which? 2026 — #4 overall (76%), perfect 100% fees score']::text[],
  ARRAY['Received a formal FCA Second Supervisory Notice in 2022 over misleading social-media financial promotions — predates the IG acquisition but remains disclosed regulatory history', 'FX fees (0.39-0.99% depending on plan) are notably higher than Trading 212''s flat 0.15%']::text[],
  '{"fees":8,"universe":7.4,"ux":8,"support":7}'::jsonb,
  'A backed-by-IG-Group platform with real regulatory history — disclosed, not hidden.',
  '{"fee_structure":"flat_monthly","fee_note":"Tiered Basic/Standard/Plus plans; SIPP fee removed on the Basic plan from 22 January 2026. FX fee ranges 0.39% (Plus) to 0.99% (Basic).","dealing_fee_gbp":0,"investment_universe_note":"Growing universe under IG Group ownership; assets under administration +34% to £3.3bn in FY2025","fscs_protected":true,"which_survey_note":"Which? 2026 — #4 overall (76%), 100% fees score","trustpilot_rating":4.15,"trustpilot_count":7300,"trustpilot_note":"Sources showed variance (4.0-4.3/5) — figure shown is a midpoint, verify live before relying on an exact number","regulatory_note":"The FCA issued a Second Supervisory Notice against Freetrade Ltd on 8 February 2022, ordering removal of paid-for social media promotions with an influencer, citing breaches of financial-promotion rules (missing risk warnings, risk of misleading vulnerable/indebted consumers). This predates Freetrade''s 1 April 2025 acquisition by IG Group Holdings plc (£160m enterprise value) but remains part of its disclosed regulatory history. Freetrade''s loss before tax widened to £24.4m in its first year under IG ownership (FY2025), from £6.8m the prior year."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://freetrade.io/',
  false,
  'Investors wanting IG Group-backed scale',
  5,
  'https://freetrade.io/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'moneyfarm',
  'uk',
  'personal-finance',
  'investing-apps',
  'Moneyfarm',
  'One of the UK''s largest non-bank-owned digital wealth managers',
  7.4,
  0,
  0,
  0,
  0.65,
  0,
  '[]'::jsonb,
  ARRAY['160,000+ active investors, £5bn+ AUM', 'Not bank/broker-owned', 'Managed ISA, no per-trade dealing']::text[],
  ARRAY['Reports 160,000+ active investors and £5bn+ AUM — one of the UK''s largest non-bank-owned digital wealth managers', 'Not owned by a bank or broker group, distinguishing it from Freetrade (IG-owned) or J.P. Morgan Personal Investing (bank-owned, formerly Nutmeg)', 'Managed portfolios remove the need to pick individual investments']::text[],
  ARRAY['Not present in the Which? 2026 investment platform survey — no independently confirmed customer-satisfaction ranking', 'Combined custody + management fee (0.45-0.75%+ typical) is higher than the percentage-fee DIY platforms in this comparison']::text[],
  '{"fees":6.8,"universe":7,"ux":8,"support":0}'::jsonb,
  'One of the largest non-bank-owned managed platforms — no independent satisfaction ranking found.',
  '{"fee_structure":"percentage","fee_note":"0.35% custody fee, capped at £45/year, plus a tiered management fee (~0.75% down to ~0.35% by portfolio size) — combined cost typically 0.45-0.75%+ on top of underlying ETF costs (~0.20% average)","dealing_fee_gbp":null,"investment_universe_note":"Managed ETF-based portfolios, not individual stock-picking","fscs_protected":true,"which_survey_note":"Not present in the Which? 2026 survey reviewed for this comparison","trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No reliable Trustpilot rating found for Moneyfarm specifically at research time — shown as not yet rated rather than an unverified figure","regulatory_note":"Moneyfarm (trading name of MFM Investment Ltd) has significant minority institutional ownership — Allianz SE holds 25-50% via its holding company, the largest single stakeholder, alongside M&G, Poste Italiane, Allianz Global Investors, Smedvig Ventures and Venrex. We describe it as \"one of the UK''s largest non-bank-owned\" digital wealth managers rather than asserting it is the single largest independent platform, since no third-party ranking directly confirmed that superlative against competitors."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.moneyfarm.com/uk/',
  false,
  'Investors wanting a managed portfolio, not bank-owned',
  6,
  'https://www.moneyfarm.com/uk/pricing/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'hargreaves-lansdown',
  'uk',
  'personal-finance',
  'investing-apps',
  'Hargreaves Lansdown',
  'The UK''s largest platform — with a disputed 2026 breach claim disclosed',
  7,
  4.35,
  21000,
  21000,
  0.35,
  0,
  '[]'::jsonb,
  ARRAY['UK''s largest platform (~1.9M clients)', 'ISA fee cut to 0.35% (Jan 2026)', '⚠ Disputed 2026 ransomware claim — see detail']::text[],
  ARRAY['The UK''s largest investment platform by client count (~1.9M clients)', 'ISA fee cut from 0.45% to 0.35% in January 2026, capped at £12.50/month', 'The widest investment universe of the 7 candidates (~8,500 shares, 3,000 funds, 1,400 ETFs, 400 trusts)']::text[],
  ARRAY['A ransomware group (APT73/Bashe) claimed a breach in January and again April 2026; HL disputes any breach occurred and states no evidence of a cyberattack was found', '£6.95 dealing fee — the highest per-trade commission in this comparison', 'Did not appear in the Which? 2026 top-10 satisfaction table found']::text[],
  '{"fees":6,"universe":9.6,"ux":7.6,"support":7.6}'::jsonb,
  'The largest, widest-universe platform — weigh the disputed 2026 breach claim below.',
  '{"fee_structure":"percentage","fee_note":"0.35% platform fee (cut from 0.45% in January 2026, for portfolios under £250k), capped at £12.50/month (cap reached around £43,000)","dealing_fee_gbp":6.95,"investment_universe_note":"~8,500 shares, 3,000 funds, 1,400 ETFs, 400 trusts, 200+ bonds/gilts (UK/US/Europe/Canada)","fscs_protected":true,"which_survey_note":"Did not appear in the Which? 2026 top-10 satisfaction table reviewed for this comparison","trustpilot_rating":4.35,"trustpilot_count":21000,"trustpilot_note":"Sources cite 4.3-4.4/5","regulatory_note":"A ransomware group calling itself APT73/Bashe claimed a breach of Hargreaves Lansdown systems in January and again April 2026 (alleging 50GB of stolen data); Hargreaves Lansdown disputes any breach occurred and states it has found no evidence of a cyberattack. We present this as a disputed, unconfirmed claim rather than a proven incident. No FCA enforcement fine was found against Hargreaves Lansdown for 2024-2026."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.hl.co.uk/',
  false,
  'Investors wanting the UK''s widest investment universe',
  7,
  'https://www.hl.co.uk/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
