-- Comparison Cockpit — seed US robo-advisors (topic = 'robo-advisors').
-- Mirrors lib/comparison/dev-seed.ts. Idempotent (ON CONFLICT DO UPDATE).
-- Provenance is mandatory per row (source_url/source_type/confidence/data_verified_at).
-- Affiliate links are left to the attribution gate: until a provider's affiliate_links
-- row is tracking_status='verified'|'dashboard_only', the loader renders review/visit
-- (never a hidden /go). Apply AFTER the topic-columns migration.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  attributes, source_type, confidence,
  badges, chips, pros, cons, sub_scores, verdict, deep_dive,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'wealthfront' AND market = 'us' LIMIT 1),
  'wealthfront', 'us', 'personal-finance', 'robo-advisors', 'Wealthfront', 'Best overall for hands-off investors',
  9.4, 4.6, 3210, 3210, 0.250, 500,
  '{"tlh":true,"human_advisor":false,"account_types":["taxable","ira","roth","sep"],"sipc":true,"frac":true,"sri":true,"crypto":false}'::jsonb,
  'official', 'high',
  '[{"type":"gold","label":"Top pick"},{"type":"sky","label":"Most clicked"}]'::jsonb,
  ARRAY['Auto tax-loss harvesting','0.25% flat fee','$500 minimum']::text[],
  ARRAY['Best-in-class tax-loss harvesting','Huge range of account types incl. 529','4.5% APY on uninvested cash']::text[],
  ARRAY['No human advisor option','$500 minimum to start']::text[],
  '{"fees":9.3,"features":9.5,"ux":9.4,"support":8.8}'::jsonb,
  'The best all-round automated investing platform',
  'Wealthfront pairs a low 0.25% flat fee with the most aggressive tax-loss harvesting in the category and an unusually wide set of account types, making it the default pick for hands-off investors who want automation without paying for an advisor.',
  true, 'wealthfront-review', 'https://www.wealthfront.com', true, 'Most investors', 1,
  'https://www.wealthfront.com/pricing', DATE '2026-06-28', true
),
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'betterment' AND market = 'us' LIMIT 1),
  'betterment', 'us', 'personal-finance', 'robo-advisors', 'Betterment', 'Best for goal-based investing',
  9.2, 4.5, 4120, 4120, 0.250, 0,
  '{"tlh":true,"human_advisor":true,"account_types":["taxable","ira","roth"],"sipc":true,"frac":true,"sri":true,"crypto":true}'::jsonb,
  'official', 'high',
  '[{"type":"green","label":"Best for goals"}]'::jsonb,
  ARRAY['Start from $0','Goal-based portfolios','SRI & crypto options']::text[],
  ARRAY['No minimum to start','Goal-based planning tools','SRI, ESG and crypto portfolios']::text[],
  ARRAY['0.25% adds up on small balances','Human advice needs Premium']::text[],
  '{"fees":8.9,"features":9.2,"ux":9.5,"support":9.0}'::jsonb,
  'The best choice for goal-based investing',
  'Betterment lets you start with $0 and organizes everything around goals, with optional human advisors on its Premium tier and a broad menu of SRI, ESG and crypto portfolios — ideal for investors who want guidance baked into the experience.',
  true, 'betterment-review', 'https://www.betterment.com', false, 'Goal planning', 2,
  'https://www.betterment.com/pricing', DATE '2026-06-28', true
),
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'fidelity-go' AND market = 'us' LIMIT 1),
  'fidelity-go', 'us', 'personal-finance', 'robo-advisors', 'Fidelity Go', 'Best for cost-conscious beginners',
  9.0, 4.7, 2680, 2680, 0, 10,
  '{"tlh":false,"human_advisor":true,"account_types":["taxable","ira","hsa"],"sipc":true,"frac":true,"sri":false,"crypto":false}'::jsonb,
  'official', 'high',
  '[{"type":"green","label":"Lowest cost"}]'::jsonb,
  ARRAY['Free under $25,000','No real minimum','Backed by Fidelity']::text[],
  ARRAY['Completely free under $25,000','No practical minimum to start','Fidelity research and support']::text[],
  ARRAY['No tax-loss harvesting','0.35% above $25,000']::text[],
  '{"fees":9.9,"features":7.8,"ux":8.4,"support":8.8}'::jsonb,
  'The best free starter for cost-conscious investors',
  'Fidelity Go is free under $25,000 and has effectively no minimum, making it the cheapest way to start automated investing — the trade-off is no tax-loss harvesting and a 0.35% fee once balances grow past $25k.',
  false, 'fidelity-go-review', 'https://www.fidelity.com', false, 'Beginners', 3,
  'https://www.fidelity.com/go', DATE '2026-06-28', true
),
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'schwab-intelligent' AND market = 'us' LIMIT 1),
  'schwab-intelligent', 'us', 'personal-finance', 'robo-advisors', 'Schwab Intelligent', 'Best zero-fee option for larger balances',
  8.8, 4.5, 1540, 1540, 0, 5000,
  '{"tlh":true,"human_advisor":false,"account_types":["taxable","ira","roth"],"sipc":true,"frac":false,"sri":true,"crypto":false}'::jsonb,
  'official', 'high',
  '[{"type":"green","label":"Best $0 fee"}]'::jsonb,
  ARRAY['0% advisory fee','Tax-loss harvesting $50k+','24/7 live support']::text[],
  ARRAY['No advisory fee at all','Tax-loss harvesting above $50k','24/7 phone and chat support']::text[],
  ARRAY['High $5,000 minimum','Holds a cash allocation (cash drag)']::text[],
  '{"fees":9.6,"features":8.5,"ux":8.0,"support":9.0}'::jsonb,
  'The best zero-fee option for larger balances',
  'Schwab Intelligent Portfolios charges no advisory fee and adds tax-loss harvesting above $50k, but requires a $5,000 minimum and keeps a mandatory cash allocation that can drag on returns.',
  false, 'schwab-intelligent-review', 'https://www.schwab.com', false, '$50k+ balances', 4,
  'https://www.schwab.com/intelligent-portfolios', DATE '2026-06-28', true
),
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'vanguard-digital' AND market = 'us' LIMIT 1),
  'vanguard-digital', 'us', 'personal-finance', 'robo-advisors', 'Vanguard Digital', 'Best for buy-and-hold index investors',
  8.9, 4.6, 2010, 2010, 0.150, 100,
  '{"tlh":false,"human_advisor":false,"account_types":["taxable","ira"],"sipc":true,"frac":false,"sri":false,"crypto":false}'::jsonb,
  'official', 'high',
  '[{"type":"green","label":"Long-term index"}]'::jsonb,
  ARRAY['Very low 0.15% fee','Real Vanguard index funds','Trusted long-term']::text[],
  ARRAY['Among the lowest fees at 0.15%','Genuine Vanguard index funds','Built for long-term holders']::text[],
  ARRAY['$100 minimum','No tax-loss harvesting']::text[],
  '{"fees":9.4,"features":7.4,"ux":7.6,"support":8.2}'::jsonb,
  'The best pick for buy-and-hold index investors',
  'Vanguard Digital Advisor wraps genuine Vanguard index funds in a very low 0.15% all-in fee, making it the natural home for long-term, buy-and-hold investors who do not need tax-loss harvesting.',
  false, 'vanguard-digital-advisor-review', 'https://investor.vanguard.com', false, 'Long-term index', 5,
  'https://investor.vanguard.com/advice/digital-advisor', DATE '2026-06-28', true
),
(
  (SELECT id FROM public.affiliate_links WHERE slug = 'sofi-robo' AND market = 'us' LIMIT 1),
  'sofi-robo', 'us', 'personal-finance', 'robo-advisors', 'SoFi Robo', 'Best free starter robo for beginners',
  8.5, 4.3, 1180, 1180, 0, 50,
  '{"tlh":false,"human_advisor":true,"account_types":["taxable","ira","roth"],"sipc":true,"frac":true,"sri":false,"crypto":false}'::jsonb,
  'official', 'medium',
  '[{"type":"green","label":"Beginner-friendly"}]'::jsonb,
  ARRAY['Free management','Free access to advisors','Beginner-friendly app']::text[],
  ARRAY['No management fee','Free access to human advisors','Polished beginner app']::text[],
  ARRAY['Smaller fund selection','No tax-loss harvesting']::text[],
  '{"fees":9.5,"features":7.2,"ux":9.0,"support":8.4}'::jsonb,
  'The best free starter robo for beginners',
  'SoFi''s automated investing is free to manage and includes complimentary access to human financial planners, which — combined with a $50 minimum and a polished app — makes it a friendly on-ramp for first-time investors.',
  true, 'sofi-robo-review', 'https://www.sofi.com', false, 'Beginners', 6,
  'https://www.sofi.com/invest/automated', DATE '2026-06-28', true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  tagline = EXCLUDED.tagline,
  score = EXCLUDED.score,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee,
  account_minimum = EXCLUDED.account_minimum,
  attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type,
  confidence = EXCLUDED.confidence,
  badges = EXCLUDED.badges,
  chips = EXCLUDED.chips,
  pros = EXCLUDED.pros,
  cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores,
  verdict = EXCLUDED.verdict,
  deep_dive = EXCLUDED.deep_dive,
  is_affiliate = EXCLUDED.is_affiliate,
  review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url,
  is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for,
  display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url,
  data_verified_at = EXCLUDED.data_verified_at,
  active = EXCLUDED.active;
