-- Comparison Cockpit — seed UK business-bank-accounts (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-1): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated
-- against ukBusinessBankAttributesSchema. FSCS bank-deposit protection rose
-- to £120,000 on 1 December 2025 but applies ONLY to full UK banking
-- licences -- Tide/Wise use e-money safeguarding (not FSCS), Revolut is
-- transitional (March 2026 licence, phased migration). fscs_status +
-- fscs_note disclose the exact position per provider rather than a blanket
-- claim. Real 2024-2025 FCA fines (Starling £28.96M, Monzo £21.09M,
-- Barclays £42M combined) disclosed in full.
-- Provenance: live research 2026-07-11 against official pricing pages, FCA
-- Register, FSCS, Bank of England, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'starling-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Starling Bank Business',
  'A full UK banking licence with unambiguous £120,000 FSCS protection',
  8.8,
  4.1,
  45000,
  45000,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['£0/mo, free UK transfers', 'Full FSCS £120,000', 'Free Making Tax Digital tool']::text[],
  ARRAY['A full UK banking licence — deposits are unambiguously FSCS-protected up to £120,000', 'Free GBP current account with no monthly fee and no UK transfer fees', 'A genuinely useful free Making Tax Digital tool for sole traders (launched March 2026)']::text[],
  ARRAY['The FCA fined Starling Bank £28,959,426 in October 2024 for financial-crime screening failures', 'No interest paid on the main current account (savings products separately pay up to ~2.5% AER)']::text[],
  '{"fees":9.6,"protection":10,"integrations":8.4,"support":7.6}'::jsonb,
  'Best overall — unambiguous full FSCS protection and genuinely free banking, with a disclosed 2024 fine.',
  '{"fscs_status":"full_fscs","fscs_note":"Starling Bank Ltd holds a full UK banking licence — deposits are FSCS-protected up to £120,000, no ambiguity.","interest_rate_note":"No interest on the main current account; separate savings products pay up to ~2.5% AER","intl_payments_note":"EUR account £2/month; USD accounts closed to new applicants (April 2026)","accounting_integrations":["Xero","QuickBooks","FreeAgent"],"trustpilot_rating":4.1,"trustpilot_count":45000,"trustpilot_note":"uk.trustpilot.com/review/starlingbank.com","regulatory_note":"The FCA fined Starling Bank £28,959,426 in October 2024 for financial-crime risk-management failures — the bank opened 54,000+ accounts for approximately 49,000 high-risk customers in breach of a 2021 regulatory requirement, and its sanctions screening had checked only a fraction of the full sanctions list since 2017. Starling states the underlying issues have since been remediated."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.starlingbank.com/business-account/',
  true,
  'Businesses wanting unambiguous full FSCS protection',
  1,
  'https://www.starlingbank.com/legal/account/fscs-protection/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'mettle-natwest',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Mettle by NatWest',
  'Completely free, including free FreeAgent accounting software',
  8.6,
  4.6,
  6350,
  6350,
  0,
  '[{"type":"green","label":"Best value"}]'::jsonb,
  ARRAY['£0/mo, no fees', 'Free FreeAgent accounting', 'Full FSCS via NatWest']::text[],
  ARRAY['Completely free — no monthly fee, free UK transfers', 'Free FreeAgent accounting software (conditional on at least 1 transaction/month) — a genuinely valuable inclusion', 'Full FSCS £120,000 protection via National Westminster Bank plc''s banking licence']::text[],
  ARRAY['Balances count toward the same £120,000 FSCS limit shared across the wider NatWest Group (NatWest, RBS, Ulster Bank, NatWest Boxed, Mettle)', 'Smallest review base of the 7, consistent with being a narrower product aimed at freelancers and small limited companies']::text[],
  '{"fees":10,"protection":9.6,"integrations":8.8,"support":8.4}'::jsonb,
  'The best value — genuinely free banking plus free accounting software.',
  '{"fscs_status":"full_fscs","fscs_note":"Provided by National Westminster Bank plc — full UK banking licence, FSCS-protected up to £120,000, shared with the wider NatWest Group licence (NatWest, RBS, Ulster Bank, NatWest Boxed, Mettle count as one licence for FSCS purposes).","interest_rate_note":"No interest on the core account","intl_payments_note":"Standard NatWest Group international payment rails","accounting_integrations":["FreeAgent (free)","Xero","QuickBooks"],"trustpilot_rating":4.6,"trustpilot_count":6350,"trustpilot_note":"uk.trustpilot.com/review/mettle.co.uk","regulatory_note":"No material FCA enforcement action or lawsuit specific to Mettle was found for 2024-2026 in this research pass."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.mettle.co.uk/',
  false,
  'Freelancers wanting free banking plus accounting',
  2,
  'https://www.mettle.co.uk/fscs-key-information/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'monzo-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Monzo Business',
  'The strongest accounting-integration breadth — with a disclosed 2025 fine',
  8.2,
  4.6,
  69500,
  69500,
  0,
  '[{"type":"sky","label":"Best accounting integration"}]'::jsonb,
  ARRAY['Xero, QuickBooks, FreeAgent, Sage', 'Full FSCS £120,000', '⚠ July 2025 FCA fine — see detail']::text[],
  ARRAY['The broadest accounting-software integration of the 7 (Xero, QuickBooks, FreeAgent, Sage)', 'Free Lite tier with a real-time accounting sync and Savings Pots', 'Strong Trustpilot rating (4.6/5, ~69,500 reviews)']::text[],
  ARRAY['The FCA fined Monzo Bank £21,091,300 in July 2025 for anti-money-laundering system failures spanning October 2018-August 2020', 'Paid tiers (Pro £9/mo, Team £25/mo) required for the deepest accounting features']::text[],
  '{"fees":9,"protection":9.6,"integrations":9.6,"support":8}'::jsonb,
  'The strongest accounting integration of the 7 — weigh the disclosed 2025 AML fine.',
  '{"fscs_status":"full_fscs","fscs_note":"Monzo Bank Ltd holds a full UK banking licence — deposits are FSCS-protected up to £120,000.","interest_rate_note":"No interest on the core Lite account; Savings Pots pay separately","intl_payments_note":"Foreign-currency payment fees 0.5-1.30% variable + fixed fee £0.50-£2.68","accounting_integrations":["Xero","QuickBooks","FreeAgent","Sage"],"trustpilot_rating":4.6,"trustpilot_count":69500,"trustpilot_note":"trustpilot.com/review/www.monzo.com","regulatory_note":"The FCA fined Monzo Bank £21,091,300 on 8 July 2025 for anti-money-laundering systems and controls failures spanning October 2018-August 2020, including allowing accounts to be opened with implausible addresses (e.g. \"Buckingham Palace\") and breaching a regulatory order by opening 34,000+ high-risk accounts between August 2020 and June 2022. Monzo states the underlying issues were remediated years ago."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://monzo.com/business-banking/',
  false,
  'Businesses wanting the deepest accounting sync',
  3,
  'https://monzo.com/business-banking/plans-pricing',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'barclays-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Barclays',
  'The most traditional corporate-bank feature set — with disclosed 2025 fines',
  6.8,
  4,
  22000,
  22000,
  8.5,
  '[]'::jsonb,
  ARRAY['12 months free for new businesses', 'SWIFT gpi payment tracking', '⚠ £42M combined 2025 FCA fines — see detail']::text[],
  ARRAY['The most traditional corporate-bank feature set of the 7 — SWIFT gpi payment tracking, 120+ currencies, 200+ countries', 'Free for the first 12 months for new-to-Barclays businesses; branch access for businesses that need it', 'Bespoke ERP/TMS reporting for larger businesses']::text[],
  ARRAY['The FCA fined Barclays a combined £42 million in 2025 across two separate financial-crime risk-management cases', 'International transfers use Barclays'' own FX rate, not the mid-market rate, and cost from £4']::text[],
  '{"fees":6.6,"protection":9.6,"integrations":7,"support":7.6}'::jsonb,
  'The most traditional, branch-backed option — weigh the disclosed 2025 combined fines.',
  '{"fscs_status":"full_fscs","fscs_note":"Barclays Bank UK plc holds a full UK banking licence — deposits are FSCS-protected up to £120,000.","interest_rate_note":"Standard business current account rates apply — not a headline-rate product","intl_payments_note":"120+ currencies, 200+ countries reach via SWIFT gpi tracking; transfers from £4 at Barclays'' own FX rate (not mid-market)","accounting_integrations":["Xero","QuickBooks","FreeAgent (discounted, not free)"],"trustpilot_rating":4,"trustpilot_count":22000,"trustpilot_note":"Fragmented across multiple Barclays subdomains on Trustpilot — treat as directional only","regulatory_note":"The FCA fined Barclays a combined £42 million in 2025 across two separate financial-crime risk-management cases: £3.09m (after settlement discount) relating to Barclays Bank UK plc''s onboarding of collapsed wealth manager WealthTek, and £39.3m relating to Barclays Bank plc''s oversight of a precious-metals firm (Stunt & Co) that received £46.8m from a known money-laundering network before Barclays acted."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.barclays.co.uk/business-banking/',
  false,
  'Businesses needing branch access or complex treasury needs',
  4,
  'https://www.barclays.co.uk/business-banking/accounts/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'wise-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Wise Business',
  'The strongest international/multi-currency proposition — safeguarded, not FSCS',
  7.4,
  4.3,
  294000,
  294000,
  0,
  '[]'::jsonb,
  ARRAY['Multi-currency (8+ local currency details)', 'FX from 0.33-0.37%', '⚠ Safeguarded, not FSCS — see detail']::text[],
  ARRAY['The strongest pure international/multi-currency proposition of the 7 — local account details in 8+ currencies', 'FX from 0.33-0.37% at the mid-market rate, transparently disclosed', 'No monthly fee on the Essential plan']::text[],
  ARRAY['An e-money institution, not a bank — funds are safeguarded, NOT FSCS-protected, a real and lower-assurance distinction', 'Advanced features (Direct Debits, receiving) require a one-off £50 fee']::text[],
  '{"fees":8.8,"protection":5,"integrations":7.6,"support":7.8}'::jsonb,
  'The best international-payments proposition — understand the safeguarding-not-FSCS distinction first.',
  '{"fscs_status":"safeguarded","fscs_note":"Wise Payments Ltd is an e-money institution, not a bank — funds are held under statutory safeguarding (segregated accounts, government bonds/cash) under the Electronic Money Regulations, NOT FSCS-protected. Wise is explicit about this itself.","interest_rate_note":"A separate \"interest\" product is available on GBP/USD/EUR balances — rate varies, check wise.com/gb/interest for the current figure","intl_payments_note":"Local account details in 8+ currencies; FX from 0.33-0.37% at the mid-market rate — the strongest pure-FX proposition of the 7","accounting_integrations":["Xero","QuickBooks"],"trustpilot_rating":4.3,"trustpilot_count":294000,"trustpilot_note":"Platform-wide figure (not business-account-specific)","regulatory_note":"No major FCA enforcement action was found for 2024-2026. General criticism in third-party reviews centres on account freezes/verification delays common to e-money providers, not a specific regulatory finding."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://wise.com/gb/business/',
  false,
  'Internationally-trading businesses prioritizing FX cost',
  5,
  'https://wise.com/help/articles/4IusAofIppsIGPcs7sEIXI/how-our-uk-entity-wise-payments-ltd-safeguards-customer-funds',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'tide-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Tide',
  'Built-in invoicing and business savings — protection depends on which rail your funds sit on',
  7,
  4.35,
  30000,
  30000,
  0,
  '[]'::jsonb,
  ARRAY['Built-in invoicing + savings', '30,000+ Trustpilot reviews', '⚠ Split FSCS/safeguarding rails — see detail']::text[],
  ARRAY['Built-in invoicing, expense cards, accounting integrations and business savings in the free tier', 'Strong Trustpilot rating (4.3-4.4/5, 30,000+ reviews)']::text[],
  ARRAY['Protection depends on which rail your funds sit on — newer accounts on ClearBank rails get FSCS £120,000, legacy accounts (PrePay Technologies-issued) remain safeguarded-only — a genuinely confusing split for customers', 'Documented cases of accounts frozen without warning, with recurring Financial Ombudsman-level complaints about chargeback handling and support responsiveness']::text[],
  '{"fees":8.2,"protection":6,"integrations":8,"support":6.6}'::jsonb,
  'Feature-rich free banking — check which rail your account sits on for its real protection status.',
  '{"fscs_status":"transitional","fscs_note":"Tide Platform Ltd is fundamentally an e-money institution (FCA-authorised under the Electronic Money Regulations 2011) — not FSCS-protected by default. However, newer accounts are moved onto ClearBank (a licensed bank) rails, giving FSCS protection up to £120,000 for those specific deposits, while legacy PrePay Technologies-issued accounts remain safeguarded-only. Protection genuinely depends on which rail a given customer''s funds currently sit on — check in-app rather than assuming either status.","interest_rate_note":"Interest available on business savings products; no interest on the core current account","intl_payments_note":"2.75% card FX fee on the free plan","accounting_integrations":["Xero","QuickBooks","FreeAgent"],"trustpilot_rating":4.35,"trustpilot_count":30000,"trustpilot_note":"trustpilot.com/review/tide.co","regulatory_note":"Documented cases of accounts frozen without warning, causing operational disruption for customers, with recurring complaints about chargeback handling and support responsiveness reaching the Financial Ombudsman Service. Separately, an unrelated clone-firm scam (\"Tide Finance\"/\"Tide Capital Markets\") has been FCA-flagged — not the real Tide."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.tide.co/',
  false,
  'Businesses wanting built-in invoicing and savings tools',
  6,
  'https://www.tide.co/safety-security/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'revolut-business',
  'uk',
  'business-banking',
  'business-bank-accounts',
  'Revolut Business',
  'A new UK bank licence — with real disclosed fraud-complaint and EU-arm issues',
  6.2,
  4.7,
  400000,
  400000,
  10,
  '[]'::jsonb,
  ARRAY['New UK banking licence (March 2026)', '25+ currencies at interbank FX', '⚠ Worst-for-fraud-complaints (Which?) — see detail']::text[],
  ARRAY['Received a full UK banking licence in March 2026 — new/migrated accounts now qualify for FSCS £120,000 protection', '25+ currencies with FX at interbank rates within plan allowances']::text[],
  ARRAY['Migration is phased — accounts opened before March 2026 may still sit with the legacy e-money entity and remain safeguarded-only, not FSCS-covered, until actively migrated', 'Which? named Revolut the UK''s worst firm for fraud/scam complaints escalated to the Financial Ombudsman for two consecutive years (2024, 2025); its EU arm had business activities restricted by the ECB in July 2025']::text[],
  '{"fees":7,"protection":5.6,"integrations":7.4,"support":5.4}'::jsonb,
  'A newly-banked platform with real, current fraud-complaint and transitional-protection issues to weigh.',
  '{"fscs_status":"transitional","fscs_note":"Revolut Bank UK Ltd received a full UK banking licence on 11 March 2026 (PRA mobilisation restrictions lifted). New/migrated accounts are FSCS-protected up to £120,000. Accounts opened before 11 March 2026 may still sit with the legacy e-money entity (Revolut Ltd) and remain under safeguarding, not FSCS, until Revolut actively migrates them (with at least 2 months'' customer notice). Check your specific account''s current status in-app rather than assuming full protection.","interest_rate_note":"Varies by plan tier","intl_payments_note":"25+ currencies, FX at interbank rates within plan allowances","accounting_integrations":["Xero","QuickBooks"],"trustpilot_rating":4.7,"trustpilot_count":400000,"trustpilot_note":"Platform-wide figure, notably high — weigh against the disclosed fraud-complaint data below","regulatory_note":"Which? named Revolut the UK''s worst firm for fraud/scam complaints escalated to the Financial Ombudsman Service for two consecutive years (2024 and 2025); BBC Panorama (2024) separately flagged Revolut as a leading target for fraud among digital banks. In July 2025 the European Central Bank restricted business activities at Revolut''s EU (Lithuania-licensed) arm pending an independent risk review — this concerns the EU entity, not directly the new UK bank, but is disclosed given the shared brand."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.revolut.com/business/',
  false,
  'Businesses that confirmed current FSCS status',
  7,
  'https://www.revolut.com/blog/post/is-revolut-a-fully-licensed-bank-in-the-uk/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
