-- Comparison Cockpit — seed UK cybersecurity-smb (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-3, completes UK
-- 9/9 and the ENTIRE 26-topic AU/CA/UK rollout): affiliate_link_id NULL,
-- is_affiliate=false, review_slug NULL, external_url = provider homepage.
-- Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- ukCybersecuritySmbAttributesSchema. UK-specific presence data (Sophos's
-- genuine Oxfordshire HQ since 1985 + SE Labs Awards 2026, ESET's dedicated
-- Bournemouth office, CrowdStrike's London-registered entity, Bitwarden's
-- confirmed lack of a UK/EU-for-UK data region post-Brexit) combined with
-- security-incident data carried over from prior AU/CA research in this
-- rollout. Every row discloses a real 2024-2026 incident or vulnerability.
-- Provenance: live research 2026-07-11 against official vendor sources,
-- NCSC, SE Labs, G2, Capterra, security-incident reporting.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'sophos-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'Sophos',
  'A genuinely British company, headquartered in Oxfordshire since 1985',
  8.9,
  4.6,
  820,
  820,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['HQ: Abingdon, Oxfordshire since 1985', 'SE Labs Awards 2026 — 3 categories won', 'NCSC CIR-assured']::text[],
  ARRAY['A genuinely British company, headquartered in Abingdon, Oxfordshire since 1985, hosting its SophosLabs threat-analysis centre on-site', 'Won three categories at the UK-based SE Labs Awards 2026 (Enterprise Endpoint Windows, Small Business Endpoint Windows, Small Business Security Development)', 'NCSC-assured for Cyber Incident Response (CIR) Standard and Enhanced levels']::text[],
  ARRAY['Sophos''s own Firewall product line (a different product from Intercept X) has been targeted by a multi-year nation-state exploitation campaign', 'Zero self-serve pricing — quote-only via reseller']::text[],
  '{"cost":7,"features":8.8,"trust":9.6,"support":8.6}'::jsonb,
  'The most UK-relevant vendor of the 7 — a genuinely British company with independent UK award recognition.',
  '{"pricing_model":"per-user/year, reseller-quoted","starting_price_note":"No official price published (quote-only via reseller). Third-party estimates from prior research: Intercept X Advanced ~$66 USD/user/yr for small deployments — unverified against an official UK quote.","product_category":"endpoint_protection","key_feature_note":"Deep-learning malware prevention plus optional XDR add-on tiers scaled to org maturity — the Advanced tier (no XDR) is the realistic SMB entry point.","uk_presence_note":"Headquartered in Abingdon, Oxfordshire since 1985 (global HQ, not just a UK office) — genuinely British, hosting SophosLabs threat-analysis on-site. Won 3 categories at the UK-based SE Labs Awards 2026 and holds NCSC Cyber Incident Response scheme assurance.","review_score":4.6,"review_count":820,"review_source":"G2 (Sophos Endpoint, not Intercept X-specific)","review_note":"Capterra shows 4.5/5 (218 reviews) listed as \"Intercept X Endpoint\".","security_note":"Sophos''s own ''Pacific Rim'' research (October 2024) documented a five-year China-linked nation-state campaign actively exploiting zero-day vulnerabilities in Sophos Firewall (XG/XGS) products against critical infrastructure; the US DOJ separately charged a Chinese national in 2024 over a 2020 campaign that compromised roughly 81,000 Sophos firewalls globally. This exploitation history is specific to Sophos''s network Firewall product line, not Intercept X (the endpoint product featured here) — but we disclose it in full given it''s the same vendor."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.sophos.com/en-us/products/endpoint-antivirus',
  true,
  'Businesses wanting a British vendor with UK awards',
  1,
  'https://secure2.sophos.com/en-us/products/intercept-x/get-pricing.aspx',
  DATE '2026-07-11',
  true
),
(
  NULL,
  '1password-business-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  '1Password Business',
  'Transparent pricing and no confirmed platform-level breach',
  8.8,
  0,
  0,
  0,
  7,
  '[{"type":"green","label":"Best password manager"}]'::jsonb,
  ARRAY['Transparent published pricing', 'SSO integrations for growing teams', 'No confirmed platform breach']::text[],
  ARRAY['One of the few vendors on this page with fully transparent, published self-serve pricing', 'SSO integrations (Okta, Entra ID, Duo) and role-based vault sharing suit growing SMB teams', 'No confirmed platform-level breach of its own found']::text[],
  ARRAY['No confirmed dedicated UK office — headquartered in Toronto, Canada; offers EU data residency (Frankfurt) but no UK-specific data-residency option', 'Current G2/Capterra review score could not be independently confirmed at research time']::text[],
  '{"cost":8.2,"features":9,"trust":9,"support":8.4}'::jsonb,
  'The most transparent, best-attested password manager researched — no confirmed UK office, but a clean record.',
  '{"pricing_model":"per-user/month","starting_price_note":"$8.99 USD/user/month (Business, billed annually), confirmed on the official pricing page; converts to an estimated ~£7/user/month. No native GBP price found (pricing shown in USD, CAD and EUR only).","product_category":"password_manager","key_feature_note":"SSO integrations (Okta, Entra ID, Duo), role-based vault sharing, Watchtower security-hygiene alerts and activity monitoring.","uk_presence_note":"No confirmed dedicated UK office found — headquartered in Toronto, Canada. Offers EU data residency (vault data hosted in Frankfurt, Germany) as an option, but this is an EU offering, not UK-specific.","review_score":null,"review_count":null,"review_source":"G2/Capterra","review_note":"A specific, current G2/Capterra star rating and review count could not be independently confirmed at research time — shown as not yet rated.","security_note":"No confirmed breach, lawsuit or fine was found for 2024-2026. The 2023 Okta third-party incident touched some 1Password-adjacent systems, but no customer vault data was accessed — a resolved, pre-window matter disclosed for context. In 2025, a DEF CON researcher disclosed and helped patch browser-extension vulnerabilities affecting several password managers including 1Password, and phishing campaigns have separately impersonated 1Password''s ''Watchtower'' brand — both are third-party/attacker-side issues, not 1Password platform compromises."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://1password.com/business/',
  false,
  'Teams wanting transparent pricing and SSO',
  2,
  'https://1password.com/pricing/password-manager',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'crowdstrike-uk-smb',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'CrowdStrike Falcon Go',
  'A London-registered UK entity — with a well-documented 2024 outage disclosed',
  8.3,
  4.6,
  385,
  385,
  6,
  '[]'::jsonb,
  ARRAY['CrowdStrike UK Limited (London)', 'NCSC CIR-assured', '⚠ July 2024 global outage — see detail']::text[],
  ARRAY['CrowdStrike UK Limited is registered in London and holds NCSC Cyber Incident Response (CIR) scheme assurance', 'Falcon Go is a purpose-built SMB bundle from a top-tier EDR vendor, with strong review scores (G2 4.6/5, 385 reviews)']::text[],
  ARRAY['The July 2024 global outage — a faulty Falcon sensor update bricked approximately 8.5 million Windows devices worldwide — remains the most severe documented incident of any vendor in this comparison', 'Falcon Go lacks true EDR; real detection/response requires upgrading to the pricier Falcon Pro or Enterprise tiers']::text[],
  '{"cost":7.8,"features":9,"trust":8,"support":8.2}'::jsonb,
  'A London-registered, NCSC-assured EDR vendor — weigh the disclosed 2024 outage, a genuinely severe incident.',
  '{"pricing_model":"per-device/month or /year","starting_price_note":"Falcon Go: $7.99 USD/device/month or $59.99 USD/device/year, capped at 100 devices. No native GBP price found; converts to an estimated ~£6/device/month.","product_category":"endpoint_protection","key_feature_note":"Falcon Go bundles next-gen AV, USB device control and mobile protection with \"Express Support\" onboarding for SMBs — full EDR/response requires upgrading to the pricier Falcon Pro or Enterprise tiers.","uk_presence_note":"CrowdStrike UK Limited is registered at 7 Albemarle Street, London W1S 4HQ, and holds NCSC Cyber Incident Response (CIR) scheme assurance.","review_score":4.6,"review_count":385,"review_source":"G2","review_note":"Capterra shows 4.6-4.7/5 (55 reviews); both reflect the broader Falcon platform, not the Falcon Go SMB tier specifically.","security_note":"The July 2024 global outage — a faulty Falcon sensor update bricked approximately 8.5 million Windows devices worldwide (airlines, hospitals, banks affected) — is the most severe documented incident of any vendor in this comparison; litigation remains live through 2025-26, including a Delta Air Lines lawsuit seeking roughly $500M in damages. Separately, in November 2025 CrowdStrike fired an employee who leaked internal data to the hacking group ''Scattered Lapsus$ Hunters''; CrowdStrike states no systems or customer data were compromised despite the group''s false claim of a full breach."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.crowdstrike.com/en-gb/',
  false,
  'Businesses wanting top-tier, NCSC-assured EDR',
  3,
  'https://www.crowdstrike.com/en-us/pricing/falcon-go/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'bitwarden-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'Bitwarden',
  'The cheapest password manager researched — no UK data region',
  8,
  4.9,
  903,
  903,
  3,
  '[]'::jsonb,
  ARRAY['Cheapest per-seat of the 7', 'Open-source, self-hostable', '⚠ No UK data region + Apr 2026 CLI compromise — see detail']::text[],
  ARRAY['The cheapest per-seat pricing researched (Teams: $4.00 USD/user/month, converts to ~£3/user/month)', 'Open-source, independently-audited codebase with a self-hosting option — relevant for businesses with data-residency concerns', 'Strong review standing (#1 in the G2 Enterprise Grid password-manager category for 11 consecutive quarters)']::text[],
  ARRAY['Offers only US and EU server regions — UK customers cannot use the EU region post-Brexit, meaning UK users default to the US region absent self-hosting', 'A malicious version of the Bitwarden CLI npm package was live for roughly 90 minutes in April 2026 as part of a broader supply-chain campaign']::text[],
  '{"cost":9.4,"features":8.4,"trust":8,"support":7.8}'::jsonb,
  'The cheapest, most open password manager researched — the UK data-residency gap is a real, disclosed limitation.',
  '{"pricing_model":"per-user/month","starting_price_note":"Teams: $4.00 USD/user/month (billed annually); Enterprise: $6.00 USD/user/month. No native GBP price; converts to an estimated ~£3/user/month (Teams). Pricing stated as \"USD only,\" \"taxes not included.\"","product_category":"password_manager","key_feature_note":"Open-source, independently-audited codebase plus a self-hosting option — lets businesses with data-residency concerns keep vault infrastructure in-country.","uk_presence_note":"No confirmed UK office found. Data-residency-wise, Bitwarden offers US and EU server regions only — UK customers explicitly cannot use the EU region post-Brexit, meaning UK users default to the US region unless self-hosting.","review_score":4.9,"review_count":903,"review_source":"G2 (98/100 satisfaction score)","review_note":"Capterra shows 4.7/5 (215 reviews). Widely cited as \"best free password manager\" across UK-facing tech press (Tom''s Guide, Gadget Scout) for 2026.","security_note":"On 22 April 2026, a malicious version of the Bitwarden CLI npm package (@bitwarden/cli@2026.4.0) was live for approximately 1.5 hours as part of a broader supply-chain campaign, stealing SSH keys, npm tokens and AWS credentials from roughly 334 downloaders. Bitwarden confirmed no vault data was accessed and the impact was scoped strictly to CLI/developer users, not the password-manager app itself."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://bitwarden.com/business/',
  false,
  'Budget-conscious teams wanting self-hosting',
  4,
  'https://bitwarden.com/pricing/business/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'bitdefender-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'Bitdefender GravityZone',
  'A GBP storefront exists — with an April 2025 GDPR fine disclosed',
  7.6,
  4.6,
  208,
  208,
  3,
  '[]'::jsonb,
  ARRAY['GBP-priced storefront (en-gb)', 'SMB-tiered up to 30 endpoints', '⚠ April 2025 GDPR fine — see detail']::text[],
  ARRAY['A localized bitdefender.com/en-gb storefront uses GBP pricing (exact figures not confirmed, dynamically loaded)', 'SMB-sized tiers with ransomware remediation/rollback and a single-pane console', 'Strong Capterra score (4.6/5, 208 reviews)']::text[],
  ARRAY['Romania''s data protection authority fined Bitdefender approximately €10,000 in April 2025 for a GDPR violation after an email-security update exposed customer names and emails', 'No independently confirmed dedicated UK operations office — the UK entity appears to be a registered/holding entity rather than a staffed office']::text[],
  '{"cost":8,"features":8.6,"trust":7.4,"support":7.6}'::jsonb,
  'A GBP-priced option with strong SMB features — weigh the disclosed 2025 GDPR fine.',
  '{"pricing_model":"per-device/year","starting_price_note":"A GBP-priced storefront exists at bitdefender.com/en-gb, but exact current figures did not render in research (dynamic pricing widget) — third-party USD estimate from prior research: Small Business Security ~$77.69/3 devices/year ≈ £3/device/month, unverified against an official UK quote.","product_category":"endpoint_protection","key_feature_note":"Multi-layered ransomware prevention, network attack defense, misconfiguration/risk management, anti-phishing and web filtering in a single-pane console.","uk_presence_note":"Bitdefender Limited UK entity is registered (address via agent in Stoke-on-Trent), but appears to be a registered/holding entity rather than a staffed operations office — primary HQ is dual Bucharest (Romania) / San Antonio (US).","review_score":4.6,"review_count":208,"review_source":"Capterra","review_note":"G2 shows a lower 4.0/5 (72 reviews) specifically for \"GravityZone XDR,\" a scope mismatch worth noting versus plain Business Security.","security_note":"Romania''s data protection authority (ANSPDCP) fined Bitdefender SRL approximately €10,000 (RON 47,772) on 30 April 2025 for GDPR Article 32 violations, after a programming error in an email-security update exposed customer names and emails to third parties. Several 2024-2025 CVEs affecting Bitdefender products exist, though none are listed in CISA''s Known Exploited Vulnerabilities catalog as of this research."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.bitdefender.com/en-gb/business/smb-products/business-security',
  false,
  'SMBs wanting a GBP-priced storefront',
  5,
  'https://www.bitdefender.com/en-gb/business/smb-products/business-security',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'eset-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'ESET PROTECT',
  'A dedicated Bournemouth office — with an actively-exploited CVE disclosed',
  7.4,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Dedicated Bournemouth UK office', 'Runs well on legacy hardware', '⚠ Actively-exploited 2024 CVE — see detail']::text[],
  ARRAY['A dedicated UK office at Ocean 80, Holdenhurst Road, Bournemouth, opened as part of ESET''s stated "British expansion", plus distribution via UK partner Avosec', 'Cloud-managed PROTECT console with a flexible Entry/Advanced/Complete/MDR upgrade path', 'Runs lightly on older hardware, a real advantage for cost-conscious SMBs']::text[],
  ARRAY['CVE-2024-11859, a flaw in ESET''s own scanner, was actively exploited by the ToddyCat APT group into 2025 — a genuine product-security concern for a security vendor', 'Zero public list pricing anywhere — quote-only, and current review scores could not be independently confirmed']::text[],
  '{"cost":7,"features":8.4,"trust":7,"support":8}'::jsonb,
  'A real, dedicated UK office and a flexible upgrade path — but a real exploited CVE to weigh, and no public pricing.',
  '{"pricing_model":"per-device, custom quote","starting_price_note":"No public list price found anywhere — ESET states pricing is quote-only. The eset.com/uk pricing page shows \"excl. VAT\" language consistent with UK-targeted pricing, but exact GBP figures did not render in research.","product_category":"endpoint_protection","key_feature_note":"Tiered PROTECT platform (Entry/Advanced/Complete/MDR) lets SMBs start with basic endpoint AV and add EDR/MDR later without switching vendors; runs lightly on older hardware.","uk_presence_note":"A dedicated UK office at Ocean 80, 80 Holdenhurst Road, Bournemouth BH8 8AQ, opened per ESET''s own \"British expansion\" press release. Distribution also runs through UK partner Avosec.","review_score":null,"review_count":null,"review_source":"G2/Capterra","review_note":"Small-sample product-specific scores (PROTECT MDR 4.8/5, 16 reviews; PROTECT Complete 4.7/5, 10 reviews) are both too small to be meaningful — shown as not yet rated.","security_note":"CVE-2024-11859, a DLL search-order hijacking flaw (CVSS 8.4) in ESET''s own Windows products, was actively exploited in the wild by the China-linked APT group ToddyCat to deploy malware and disable kernel security notifications, patched in January 2025. Separately, ESET''s own researchers discovered and disclosed CVE-2024-7344, an industry-wide UEFI Secure Boot bypass, fixed via the January 2025 Patch Tuesday."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.eset.com/uk/business/protect-platform/',
  false,
  'Cost-conscious businesses wanting UK-based support',
  6,
  'https://www.eset.com/uk/about/contact/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'nordvpn-business-uk',
  'uk',
  'cybersecurity',
  'cybersecurity-smb',
  'NordVPN (NordLayer Business)',
  'TechRadar UK''s #1 business VPN — with a January 2026 breach claim disclosed',
  7,
  0,
  0,
  0,
  9,
  '[]'::jsonb,
  ARRAY['TechRadar UK #1 business VPN 2026', 'UK office in Nord Security''s footprint', '⚠ Jan 2026 breach claim — see detail']::text[],
  ARRAY['TechRadar''s UK edition ranks NordLayer #1 for "best business VPN" 2026; SafetyDetectives also rates it a top business-VPN pick', 'Sources confirm UK offices among Nord Security''s international footprint']::text[],
  ARRAY['A threat actor claimed a January 2026 breach of Salesforce/Jira-adjacent infrastructure; NordVPN disputes any production impact, calling the leaked data "dummy data" from an old third-party test environment', 'No confirmed native GBP business pricing (consumer NordVPN shows GBP, but NordLayer business pricing found only in USD)']::text[],
  '{"cost":7.4,"features":7.6,"trust":6.4,"support":7.2}'::jsonb,
  'A UK-award-winning business VPN — read the disclosed breach claim below before choosing.',
  '{"pricing_model":"per-user/month","starting_price_note":"Lite $8 USD/user/month, Core $11 USD/user/month, Premium $14 USD/user/month (minimum 5 users); Enterprise from $6 USD/user/month at 200+ seats. No confirmed native GBP business price; converts to an estimated ~£9/user/month (Core).","product_category":"vpn_network_security","key_feature_note":"ThreatBlock malicious-site filtering, IP allowlisting, DNS filtering, Cloud Firewall and site-to-site VPN for distributed teams.","uk_presence_note":"Sources confirm UK offices among Nord Security''s international footprint, though no specific London address was independently confirmed; corporate structure is Panama-registered (NordVPN S.A.) with an EU entity in Amsterdam and parent Nord Security headquartered in Lithuania — a UK presence exists but is not a headquarters.","review_score":null,"review_count":null,"review_source":"G2/Capterra","review_note":"No NordLayer G2 score was independently confirmed at research time — shown as not yet rated.","security_note":"A threat actor calling itself \"1011\" claimed a January 2026 breach of Salesforce/Jira-adjacent development infrastructure. NordVPN''s response within 24 hours: the exposed data came from an isolated third-party test environment and was \"dummy data,\" with no production or customer data affected. No independent forensic verification of either side''s account has surfaced as of this page''s last check."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://nordlayer.com/',
  false,
  'Distributed UK teams needing network access',
  7,
  'https://nordlayer.com/pricing/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
