-- Comparison Cockpit — seed CA ai-tools-finance (market='ca').
-- Visit-only launch (AU/CA/UK rollout, Stage 2 Slice CA-3, completes CA
-- 8/8 topics): affiliate_link_id NULL, is_affiliate=false, review_slug
-- NULL, external_url = provider homepage. Idempotent (ON CONFLICT DO
-- UPDATE). Attributes validated against caAiToolsFinanceAttributesSchema.
-- Unlike AU/US (B2B accounting-software AI), this shortlist is deliberately
-- consumer-facing (general AI assistants + AI-branded budgeting apps).
-- KOHO's "Kortex AI" is disclosed as internal fraud/AML infrastructure, not
-- a customer-facing feature. Moka's AI positioning is disclosed as thin and
-- absorbed into its moka.ai -> intelligentinvesting.ai migration, ranked
-- last per the approved shortlist, not excluded. Wealthsimple's September
-- 2025 data breach (SINs exposed) and OpenAI's active tracker-privacy class
-- action are disclosed in full.
-- Provenance: live research 2026-07-11 against official pricing pages, App
-- Store, Google Play, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'chatgpt',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'ChatGPT',
  'The most-used AI tool among Canadians for money management',
  8.8,
  4.3,
  5298,
  5298,
  27,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Most-used AI tool for money mgmt (BMO report)', 'Dedicated personal-finance experience', 'Free tier available']::text[],
  ARRAY['The most-used AI tool among Canadians for money management, per a BMO report', 'A dedicated "personal finance experience" initiative for budgeting Q&A and document/receipt analysis', 'Free tier available, with paid tiers scaling up to team/enterprise use']::text[],
  ARRAY['Faces an active class-action lawsuit (filed May 2026) alleging undisclosed tracker use on chat content, including financial topics', 'No native CAD pricing — bills in USD, converted at checkout']::text[],
  '{"fees":8,"features":9.4,"ux":9,"support":7}'::jsonb,
  'The most broadly used AI tool for Canadian money questions, with real privacy litigation to weigh.',
  '{"pricing_model":"freemium","starting_price_note":"Free tier available. Plus: $20 USD/month (~C$27/month estimated, no native CAD price). Pro tiers: $100 and $200 USD/month, the $100 tier added April 2026.","target_segment":"general_assistant","ai_features_note":"General-purpose conversational AI; OpenAI''s \"personal finance experience in ChatGPT\" initiative adds budgeting Q&A, financial-concept explanations and receipt/document analysis on top of the base assistant.","free_tier_or_trial":true,"review_score":4.3,"review_count":5298,"review_source":"Google Play","review_note":"No reliable aggregate Trustpilot/G2 score specific to the personal-finance use case was found — this figure reflects the general ChatGPT app.","regulatory_note":"OpenAI faces an active class action (filed May 2026, N.D. California) alleging Meta Pixel and Google Analytics trackers on chatgpt.com secretly sent chat content — including financial and health topics — to Meta and Google without consent; the case survived a motion to dismiss in late 2025. Separately, a January 2026 court order in New York Times copyright litigation compelled OpenAI to produce 20 million anonymized ChatGPT logs — sought by the litigants, not OpenAI, but a real user-privacy consideration."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://chatgpt.com/',
  true,
  'Most Canadians wanting general AI money help',
  1,
  'https://openai.com/business/chatgpt-pricing/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'monarch-money',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'Monarch Money',
  'The strongest dedicated AI budgeting assistant researched',
  8.9,
  4.9,
  70000,
  70000,
  12,
  '[{"type":"green","label":"Best dedicated AI budgeting app"}]'::jsonb,
  ARRAY['AI Assistant: summaries + forecasting', 'App Store 4.9/5 (70K+ ratings)', 'Read-only bank linking']::text[],
  ARRAY['A genuinely AI-branded in-app assistant delivering weekly financial summaries, spending-trend detection and cash-flow forecasting', 'The strongest independent review scores researched for this comparison (App Store 4.9/5, ~70K ratings; Google Play 4.7/5, ~17.6K reviews)', 'Read-only bank linking — Monarch cannot move funds, a real security mitigant']::text[],
  ARRAY['No native CAD pricing — bills in USD, converted at checkout', 'No permanent free tier; trial availability varies by promo code']::text[],
  '{"fees":7.6,"features":9.2,"ux":9.4,"support":8.2}'::jsonb,
  'The strongest dedicated AI budgeting product researched, with genuinely shipped (not just marketed) AI features.',
  '{"pricing_model":"flat_subscription","starting_price_note":"Core: $99.99 USD/year (~C$11.50/month estimated). Plus: $199 USD/year (~C$23/month estimated), adds forecasting, business/rental income tracking and deeper Morningstar-powered investment analysis. No native CAD price.","target_segment":"budgeting","ai_features_note":"In-app \"AI Assistant\" delivers weekly financial summaries, surfaces spending trends, answers natural-language money questions, and provides forward-looking cash-flow projections (\"Monarch Forecasting\") — a genuinely shipped AI feature set, not just marketing language.","free_tier_or_trial":false,"review_score":4.9,"review_count":70000,"review_source":"App Store","review_note":"Google Play separately shows 4.7/5 (~17,600 reviews). G2/Capterra samples were too small to be meaningful for this product.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.monarch.com/',
  false,
  'Households wanting genuine AI budgeting features',
  2,
  'https://www.monarch.com/pricing',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'copilot-money',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'Copilot Money',
  'Apple Design Award recognition, iOS/Mac-only',
  8.5,
  4.8,
  28000,
  28000,
  11,
  '[{"type":"sky","label":"Best for Apple users"}]'::jsonb,
  ARRAY['Apple Design Award Finalist 2026', 'Automatic categorization + cash-flow view', 'iOS/Mac only']::text[],
  ARRAY['Automatic transaction categorization that learns spending patterns, plus a genuinely useful cash-flow visualization tool', 'Apple Editor''s Choice and Apple Design Award Finalist recognition (2026)', 'Strong App Store rating (~4.8/5, 27,000-30,000+ ratings)']::text[],
  ARRAY['iOS/Mac only — no Android app, a real reach limitation for many Canadians', 'Explicitly weaker on long-range planning (debt payoff, retirement modeling) per third-party reviews']::text[],
  '{"fees":7.8,"features":8.6,"ux":9.4,"support":7.8}'::jsonb,
  'The best AI budgeting experience for Apple users specifically — no Android version exists.',
  '{"pricing_model":"flat_subscription","starting_price_note":"$95 USD/year when billed annually (~C$11/month estimated); higher on monthly billing (~$13 USD/month per some reviews — confirm current rate at checkout). Single tier, no feature-gating. No native CAD price.","target_segment":"budgeting","ai_features_note":"Automatic transaction categorization that learns spending patterns, a cash-flow visualization tool for spotting income/spending trends, and subscription/recurring-charge detection.","free_tier_or_trial":true,"review_score":4.8,"review_count":28000,"review_source":"App Store","review_note":"iOS/Mac-only — no Android app.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://copilot.money/',
  false,
  'Apple users wanting a polished budgeting AI',
  3,
  'https://copilot.money/pricing/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'perplexity-ai',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'Perplexity AI',
  'A cited-source research tool — with active copyright litigation disclosed',
  7.4,
  1.6,
  400,
  400,
  27,
  '[]'::jsonb,
  ARRAY['Cited-source AI research', 'Recommended for CA startup market research', '⚠ Active copyright lawsuits — see detail']::text[],
  ARRAY['AI-powered answer engine with cited sources, useful for Canadian startups researching markets or regulations', 'Free tier available, with model-switching between frontier LLMs on paid tiers']::text[],
  ARRAY['Trustpilot score is poor (~1.5-1.6/5, ~180-695 reviews across snapshots), dominated by billing and cancellation complaints', 'Multiple active copyright/IP lawsuits bear directly on the reliability of its AI-generated answers']::text[],
  '{"fees":7,"features":8.6,"ux":7.4,"support":5.4}'::jsonb,
  'A genuinely useful research tool — weigh the disclosed billing complaints and active litigation.',
  '{"pricing_model":"freemium","starting_price_note":"Free tier available. Pro: $20 USD/month or $200 USD/year (~C$27/month estimated). Max: $200 USD/month or $2,000 USD/year, adds a multi-model \"Model Council\" and the Comet AI-agent browser. No native CAD price.","target_segment":"general_assistant","ai_features_note":"AI-powered answer engine with cited sources (\"Pro Search\"), model-switching between frontier LLMs, and (Max tier) an agentic browser (Comet) that can take actions on websites — useful for Canadian founders doing market or regulatory research.","free_tier_or_trial":true,"review_score":1.6,"review_count":400,"review_source":"Trustpilot","review_note":"Sharp platform split — Trustpilot is dominated by billing/cancellation complaints, while Product Hunt/G2/Capterra show notably higher marks for the core search product itself. Both are disclosed since the billing pattern is a legitimate consumer-warning point.","regulatory_note":"Perplexity faces multiple active copyright/IP lawsuits: News Corp (October 2024, alleging misuse of Wall Street Journal/New York Post content plus hallucinated attributions), Encyclopedia Britannica and Merriam-Webster (2026, alleging near-verbatim content reproduction), and Amazon (November 2025, alleging its Comet AI-agent browser impersonated a human shopper on Amazon without disclosing itself as a bot). These bear directly on the reliability of AI-generated answers for research use."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.perplexity.ai/',
  false,
  'Founders doing market or regulatory research',
  4,
  'https://www.perplexity.ai/hub/pricing',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'wealthsimple-ai',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'Wealthsimple',
  'A trusted Canadian brand — with a real 2025 breach disclosed',
  6.8,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Free core budgeting', 'AI support chatbot (Decagon)', '⚠ Sept 2025 data breach — see detail']::text[],
  ARRAY['Free core budgeting/spend-tracking, backed by a large, well-known Canadian brand', 'An AI support chatbot (switched to Decagon in January 2026) resolves an estimated 60-70% of support queries without a human', 'Publishes a dedicated legal AI-disclosure page — a genuine transparency signal']::text[],
  ARRAY['AI positioning is weaker than the other 6 candidates — no headline AI-branded budgeting/forecasting feature the way Monarch or Copilot has', 'Disclosed a real data breach in September 2025 exposing SINs and government IDs for roughly 30,000 customers']::text[],
  '{"fees":9.4,"features":6,"ux":8,"support":6.6}'::jsonb,
  'A trusted, free budgeting tool from a major Canadian brand — the weakest AI positioning of the 7, with a real breach to weigh.',
  '{"pricing_model":"freemium","starting_price_note":"Free — core budgeting/spend-tracking has no subscription fee (does not pull in external bank accounts, unlike Monarch/Copilot, a real limitation). Investing/trading fees are separate and not the focus of this comparison.","target_segment":"budgeting","ai_features_note":"A customer-facing support chatbot (switched to Decagon as the underlying AI vendor in January 2026) resolves an estimated 60-70% of support queries without a human; a planned AI-powered investment research/trading dashboard is rolling out. Budgeting-specific AI (auto-categorization, forecasting) is not a headline feature the way it is for Monarch/Copilot.","free_tier_or_trial":true,"review_score":null,"review_count":null,"review_source":"Not isolated","review_note":"A comprehensive third-party review aggregate score specific to the budgeting feature was not isolated in research — shown as not yet rated rather than citing an overall brand score.","regulatory_note":"Wealthsimple disclosed a data breach in September 2025 — a supply-chain attack via a third-party software package exposed data for roughly 30,000 customers (under 1% of its ~3M users), including SINs, government IDs, dates of birth, IP addresses and account numbers. Wealthsimple states funds and passwords were not compromised and the intrusion was contained within hours; affected users received free credit monitoring."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.wealthsimple.com/en-ca/',
  false,
  'Existing Wealthsimple users wanting free budgeting',
  5,
  'https://www.wealthsimple.com/en-ca/legal/ai-disclosure',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'koho',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'KOHO',
  'A Canadian fintech — its "AI" is internal infrastructure, not an in-app feature',
  6.2,
  4.5,
  2000,
  2000,
  0,
  '[]'::jsonb,
  ARRAY['Canadian fintech (Toronto)', 'Kortex AI = internal fraud/AML tooling', 'Free Essential tier']::text[],
  ARRAY['A genuine Canadian fintech with a free account tier and native CAD pricing on paid plans', 'Kortex AI (built on AWS Bedrock) is real, purpose-built AI infrastructure for fraud investigation and AML compliance', 'Strong Trustpilot rating (~4.5/5, 2,000+ reviews)']::text[],
  ARRAY['Kortex AI is internal-only — Canadians do not directly see or use it inside the app, unlike the other 6 candidates'' customer-facing AI features', 'Recurring complaint pattern around support responsiveness and account holds during re-verification']::text[],
  '{"fees":9,"features":4.4,"ux":7.4,"support":6.6}'::jsonb,
  'A real Canadian fintech with genuine AI infrastructure — but not a customer-facing AI tool in the way the others are.',
  '{"pricing_model":"freemium","starting_price_note":"Essential: free (with direct deposit or $1,000+/month in deposits, otherwise a fee applies). Extra: $12 CAD/month. Everything: ~$14.75 CAD/month billed annually ($177/year) or ~$22 CAD/month billed monthly. Native CAD pricing — no conversion needed.","target_segment":"fraud_security","ai_features_note":"Kortex AI (built on Amazon Bedrock) is an internal platform used for anti-money-laundering suspicious-transaction-report automation, fraud/scam investigation and security-event triage — it is not a labeled, customer-facing in-app feature. Treat this as AI infrastructure powering the product behind the scenes, not a tool Canadians interact with directly.","free_tier_or_trial":true,"review_score":4.5,"review_count":2000,"review_source":"Trustpilot","review_note":"Recurring complaints center on customer service (slow chat, account holds during re-verification), not the AI systems themselves.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.koho.ca/',
  false,
  'Canadians wanting real AI infrastructure, not hype',
  6,
  'https://www.koho.ca/everything/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'moka-ai',
  'ca',
  'ai-tools',
  'ai-tools-finance',
  'Moka',
  'AI positioning largely absorbed into an ongoing platform migration',
  4.6,
  1.9,
  15,
  15,
  15,
  '[]'::jsonb,
  ARRAY['Round-up investing app', '⚠ Active platform migration — see detail', 'Poor Trustpilot score']::text[],
  ARRAY['A distinctive round-up/spare-change investing niche among the 7 candidates']::text[],
  ARRAY['AI-feature positioning is thin and largely absorbed into the ongoing moka.ai → intelligentinvesting.ai migration, rather than a distinct, independently verifiable ''Moka AI'' product', 'Poor Trustpilot score (1.9/5, 15 reviews) with billing-after-cancellation complaints and users describing the in-app AI chatbot as ineffective']::text[],
  '{"fees":6,"features":4,"ux":4.4,"support":4}'::jsonb,
  'Kept on this list per the approved shortlist — its AI claim is the least substantiated and its pricing the least settled of the 7. Read the disclosure below.',
  '{"pricing_model":"freemium","starting_price_note":"Pricing is genuinely unclear and in flux during the platform migration — sources cite figures from $4/month (basic round-up) to $15/month (premium with coaching), with at least one complaint describing a $10.50/month charge persisting post-cancellation. Treat any figure as unverified until reconfirmed directly.","target_segment":"budgeting","ai_features_note":"Marketing around the broader Intelligent Investing platform references a \"Fiscal.ai Pro\" research layer and a \"behavioral science\" engine, but these are positioned at the platform level rather than clearly branded as distinct \"Moka AI\" features still active under the Moka name specifically — the weakest-substantiated AI claim of the 7 candidates on this page.","free_tier_or_trial":false,"review_score":1.9,"review_count":15,"review_source":"Trustpilot","review_note":"Small sample (15 reviews), predominantly negative.","regulatory_note":"Moka''s parent company (Mogo, renamed Orion Digital Corp in December 2025) is actively migrating the platform from moka.ai to intelligentinvesting.ai, with unresolved pricing and feature-branding inconsistencies across sources at research time. Trustpilot reviews describe billing continuing after cancellation requests, no live chat/phone support, and an in-app AI chatbot users describe as ineffective. Website traffic is reportedly down roughly 87%, a signal of declining usage, not a formal incident."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.intelligentinvesting.ai/moka',
  false,
  'Buyers who have confirmed current Moka pricing directly',
  7,
  'https://help.intelligentinvesting.ai/en/articles/11138873-moka-is-a-part-of-your-intelligent-investing-experience-with-mogo',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
