-- Comparison Cockpit — seed US credit card companies (topic = 'credit-card-companies', category = 'personal-finance').
-- Idempotent (ON CONFLICT DO UPDATE). All 10 rows = is_affiliate=false, review_slug=NULL.
-- Attribution Gate: no active affiliate_links rows for any of these issuers as credit-card-company CTAs.
-- All welcome bonus values are editorial estimates based on best standard/elevated public offers as of July 2026.
-- Cost model: banking / monthly_fee=0 for all (all issuers offer at least one $0 annual-fee card).
-- Source: official card issuer sites + App Store ratings (verified July 2026).

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum, monthly_fee,
  attributes, source_type, confidence,
  badges, chips, pros, cons, sub_scores, verdict, deep_dive,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'chase', 'us', 'personal-finance', 'credit-card-companies',
  'Chase / JPMorgan Chase',
  'Best overall: Sapphire, Freedom, Ink rewards',
  9.2, 4.8, 3500000, 0, 0, 0, 0,
  '{"best_card":"Chase Sapphire Preferred","max_welcome_bonus_value":1000,"max_welcome_bonus_desc":"100,000 Ultimate Rewards pts ($1,000 via portal)","min_annual_fee":0,"max_annual_fee":550,"min_credit_score":700,"min_credit_label":"Good (700+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":false,"has_student_card":false,"has_business_card":true,"has_balance_transfer":true,"network":"Visa","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"JPMorgan Chase Bank N.A. — OCC-regulated national bank; FDIC-insured."}'::jsonb,
  'official', 'high',
  '[{"type":"gold","label":"Top pick"}]'::jsonb,
  ARRAY['Ultimate Rewards: 14+ airline & hotel partners','Sapphire Reserve: 3× travel + dining, Priority Pass','Ink Business lineup for freelancers and SMBs']::text[],
  ARRAY['Ultimate Rewards transfers to 14+ airlines & hotels at strong value (often 2¢+ per point)','Sapphire Reserve earns 3× on all travel and dining worldwide, includes Priority Pass lounge access and a $300 travel credit','Ink Business cards (Cash, Preferred, Unlimited) cover most small-business spending categories at 3–5×']::text[],
  ARRAY['5/24 rule: 5+ new cards in 24 months = automatic rejection at Chase','Needs good to excellent credit (700+ recommended) — no path for fair or bad credit','No secured or student card in the lineup']::text[],
  '{"cost":8.8,"features":9.6,"ux":9.2,"support":8.4}'::jsonb,
  'The strongest rewards ecosystem in the US credit card market',
  'Chase dominates the US credit card market — the Ultimate Rewards ecosystem transfers to 14+ airline and hotel partners at strong value (often 2¢+ per point), and the Sapphire Preferred is the most-recommended starter travel card across every major comparison site. The Ink Business lineup (Cash, Preferred, Unlimited) covers most small-business spending at 3–5× with no annual fee on two of the three. The one hard constraint is the 5/24 rule: Chase automatically denies most applicants who have opened five or more credit cards across any issuer in the past 24 months, so Chase cards are best applied for before exploring other issuers.',
  false, NULL, 'https://creditcards.chase.com/', true, 'Best for: Travel rewards & business cards', 1,
  'https://creditcards.chase.com/', DATE '2026-07-05', true
),
(
  NULL,
  'american-express', 'us', 'personal-finance', 'credit-card-companies',
  'American Express',
  'Platinum, Gold, Blue — premium travel & business',
  9.0, 4.9, 2500000, 0, 0, 0, 0,
  '{"best_card":"Amex Platinum Card","max_welcome_bonus_value":1500,"max_welcome_bonus_desc":"150,000 Membership Rewards pts (~$1,500 value)","min_annual_fee":0,"max_annual_fee":695,"min_credit_score":690,"min_credit_label":"Good (690+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":false,"has_student_card":false,"has_business_card":true,"has_balance_transfer":false,"network":"Amex","app_store_rating":4.9,"review_source":"App Store iOS","regulatory_note":"American Express National Bank — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'high',
  '[]'::jsonb,
  ARRAY['Membership Rewards: 21 transfer partners','Platinum: 800+ airport lounges worldwide','Best purchase protection of any issuer']::text[],
  ARRAY['Membership Rewards transfer to 21 airline and hotel partners, including ANA, Air France/KLM, and Singapore Airlines — among the widest transfer networks in the US','The Platinum card includes Centurion, Delta Sky Club, and Priority Pass lounge access covering 800+ global lounges','Best-in-class purchase protection and extended warranty on all Amex cards, regardless of annual fee']::text[],
  ARRAY['Not accepted at ~1–4% of US merchants — carry a Visa or Mastercard as a backup internationally','$695 Platinum annual fee — requires actively using travel credits, Uber Cash, and other perks to break even','No secured or student cards — approval is selective, typically requiring good-to-excellent credit']::text[],
  '{"cost":7.8,"features":9.8,"ux":9.4,"support":8.6}'::jsonb,
  'The best premium travel and business card issuer in the US',
  'American Express leads in premium travel and business cards — the Platinum''s 800+ lounge network and the Gold''s 4× dining/groceries have no close rivals, and Membership Rewards transfers to 21 partners including ANA, Air France/KLM, and Singapore Airlines at up to 1.4–2¢+ per point. The honest caveats: the Platinum''s $695 annual fee requires actively using travel credits and Uber Cash to break even, and Amex acceptance — while over 99% domestically — can lag Visa and Mastercard in certain international markets, so carrying a backup card is advisable when traveling abroad.',
  false, NULL, 'https://www.americanexpress.com/us/credit-cards/', false, 'Best for: Premium travel & business', 2,
  'https://www.americanexpress.com/us/credit-cards/', DATE '2026-07-05', true
),
(
  NULL,
  'capital-one', 'us', 'personal-finance', 'credit-card-companies',
  'Capital One',
  'Venture X to Platinum — any credit score',
  8.5, 4.8, 1800000, 0, 0, 0, 0,
  '{"best_card":"Capital One Venture X","max_welcome_bonus_value":750,"max_welcome_bonus_desc":"75,000 miles (~$750 via travel portal)","min_annual_fee":0,"max_annual_fee":395,"min_credit_score":580,"min_credit_label":"Fair (580+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":true,"has_student_card":true,"has_business_card":true,"has_balance_transfer":true,"network":"Mastercard","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"Capital One Bank N.A. — OCC-regulated; FDIC-insured. Note: Discover is now a Capital One subsidiary (merger May 2025) — combined deposits share the $250k FDIC limit."}'::jsonb,
  'official', 'high',
  '[]'::jsonb,
  ARRAY['Full credit spectrum: fair to excellent','Venture X: $395 fee, $400 in annual credits back','Miles transfer to 15+ airline partners']::text[],
  ARRAY['Covers the full credit spectrum from fair (Platinum Secured, Quicksilver Student) to excellent (Venture X, Savor) — no other major issuer matches this range in one portfolio','Venture X ($395/year) returns $300 via travel portal credit + $100 Global Entry/TSA PreCheck credit, effectively netting down to -$5/year if you use both','Venture miles transfer to 15+ partners including Air Canada Aeroplan, Turkish Airlines Miles&Smiles, and Wyndham']::text[],
  ARRAY['Fewer premium transfer sweet-spots than Chase Ultimate Rewards or Amex Membership Rewards','Discover Bank is now a Capital One subsidiary (merger closed May 2025) — deposits at both banks share one $250k FDIC insurance limit','Some entry-level cards (Quicksilver) offer limited bonus categories vs. rivals at the same fee tier']::text[],
  '{"cost":8.6,"features":9.0,"ux":9.0,"support":8.2}'::jsonb,
  'The best all-in-one issuer for any credit score',
  'Capital One''s suite runs the full credit spectrum: the Venture X ($395/year, offset by $300 travel portal credit and $100 Global Entry/TSA PreCheck) targets premium travelers, while the Platinum Secured and Quicksilver Student cover fair/no credit applicants who no other major issuer will touch at competitive terms. Venture miles transfer to 15+ partners, though the program lacks the premium sweet spots of Chase''s or Amex''s networks. Discover Bank is now a Capital One subsidiary (merger completed May 2025) — it continues to operate as a separate brand, but combined deposits at both banks share the $250k FDIC insurance limit.',
  false, NULL, 'https://creditcards.capitalone.com/', false, 'Best for: All credit scores', 3,
  'https://creditcards.capitalone.com/', DATE '2026-07-05', true
),
(
  NULL,
  'citi', 'us', 'personal-finance', 'credit-card-companies',
  'Citi',
  'Double Cash 2%, best balance transfer issuer',
  8.0, 4.9, 1200000, 0, 0, 0, 0,
  '{"best_card":"Citi Double Cash","max_welcome_bonus_value":750,"max_welcome_bonus_desc":"75,000 ThankYou points (Strata Premier offer)","min_annual_fee":0,"max_annual_fee":95,"min_credit_score":670,"min_credit_label":"Good (670+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":false,"has_student_card":false,"has_business_card":true,"has_balance_transfer":true,"network":"Mastercard","app_store_rating":4.9,"review_source":"App Store iOS","regulatory_note":"Citibank N.A. — OCC-regulated national bank; FDIC-insured."}'::jsonb,
  'official', 'high',
  '[]'::jsonb,
  ARRAY['Double Cash: 2% on everything, no tracking','Longest 0% APR for balance transfers (21 mo)','Strata Premier: 3× travel, groceries, dining']::text[],
  ARRAY['Double Cash earns 2% on every purchase (1% when you buy, 1% when you pay) — the simplest flat-rate cash back card in the US market, no annual fee','Longest 0% APR promotional period for balance transfers in this comparison: up to 21 months with a 3–5% transfer fee — the default pick for paying down existing debt interest-free','Strata Premier earns 3× on travel, hotels, grocery stores, and restaurants, with ThankYou points transferable to American Airlines, Air France/KLM, and 15+ other partners']::text[],
  ARRAY['ThankYou Points transfer network has fewer premium airline partners than Chase Ultimate Rewards or Amex Membership Rewards','App and online banking experience rated below Chase, Amex, and Capital One in user reviews','No secured card in the current lineup — applicants below ~670 FICO should look elsewhere']::text[],
  '{"cost":9.0,"features":8.2,"ux":7.8,"support":7.4}'::jsonb,
  'The best balance transfer issuer and the simplest flat-rate cash back card',
  'Citi''s Double Cash card (2% back on everything — 1% when you buy, 1% when you pay) remains the simplest flat-rate cash back card in the US market with no annual fee, and the Strata Premier (3× travel, hotels, groceries, restaurants) earns ThankYou Points transferable to American Airlines, Air France/KLM, Wyndham, and 15 others. Citi''s biggest strength is its balance transfer products: 0% APR promotional periods up to 21 months with a 3–5% transfer fee are the longest in this comparison, making Citi the default pick for carrying an existing balance interest-free while paying it down.',
  false, NULL, 'https://www.citi.com/credit-cards/credit-card-offers/', false, 'Best for: Balance transfers & cash back', 4,
  'https://www.citi.com/credit-cards/credit-card-offers/', DATE '2026-07-05', true
),
(
  NULL,
  'discover', 'us', 'personal-finance', 'credit-card-companies',
  'Discover',
  'No annual fee ever — Cashback Match year 1',
  7.8, 4.8, 900000, 0, 0, 0, 0,
  '{"best_card":"Discover it Cash Back","max_welcome_bonus_value":300,"max_welcome_bonus_desc":"Cashback Match — all first-year rewards doubled","min_annual_fee":0,"max_annual_fee":0,"min_credit_score":580,"min_credit_label":"Fair (580+)","has_travel_cards":false,"has_cashback_cards":true,"has_secured_card":true,"has_student_card":true,"has_business_card":false,"has_balance_transfer":true,"network":"Discover","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"Discover Bank — FDIC-insured. Now a Capital One subsidiary (merger closed May 2025); continues to operate as a separate brand."}'::jsonb,
  'official', 'high',
  '[]'::jsonb,
  ARRAY['Cashback Match: year-1 rewards doubled automatically','No annual fee on any Discover card — ever','Secured it auto-upgrades after ~7 months']::text[],
  ARRAY['Cashback Match automatically doubles every dollar of cash back earned in year 1 — no cap, no conditions, no enrollment needed','Zero annual fee on every Discover card, including the Secured it — no other major issuer is $0 across the entire portfolio','The Secured it card auto-graduates to an unsecured card with a credit limit increase after approximately seven months of on-time payments']::text[],
  ARRAY['Fewer international merchants than Visa or Mastercard — acceptance gaps at some overseas locations','Rotating 5% categories (up to $1,500/quarter) require quarterly opt-in activation — easy to forget','Now a Capital One subsidiary (merger May 2025) — brand continues for now, but long-term trajectory is uncertain']::text[],
  '{"cost":9.4,"features":7.8,"ux":8.6,"support":8.0}'::jsonb,
  'The best issuer for beginners, students, and credit builders',
  'Discover builds its value proposition around the first-year Cashback Match — every dollar of cash back earned in year 1 is doubled automatically, with no spending caps. All Discover cards charge zero annual fee, zero foreign transaction fees, and carry no penalty APR (rates don''t spike if you miss a payment). The Secured it card is the strongest mainstream option for credit-building: it auto-graduates to an unsecured card after approximately seven months of on-time payments. Important context: Discover is now a Capital One subsidiary (merger closed May 2025) — it continues to operate as a separate brand, but the long-term trajectory is uncertain.',
  false, NULL, 'https://www.discover.com/credit-cards/', false, 'Best for: Students & credit beginners', 5,
  'https://www.discover.com/credit-cards/', DATE '2026-07-05', true
),
(
  NULL,
  'bank-of-america', 'us', 'personal-finance', 'credit-card-companies',
  'Bank of America',
  'Preferred Rewards boost: up to 3.5% cashback',
  7.3, 4.8, 4000000, 0, 0, 0, 0,
  '{"best_card":"Bank of America Premium Rewards","max_welcome_bonus_value":500,"max_welcome_bonus_desc":"50,000 points ($500 cash value, Premium Rewards)","min_annual_fee":0,"max_annual_fee":550,"min_credit_score":670,"min_credit_label":"Good (670+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":true,"has_student_card":true,"has_business_card":true,"has_balance_transfer":true,"network":"Visa","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"Bank of America N.A. — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'medium',
  '[]'::jsonb,
  ARRAY['3.5% cashback for $100k+ Preferred Rewards clients','Travel Rewards: 1.5× points, no foreign-tx fee','Secured, student, and business cards available']::text[],
  ARRAY['Preferred Rewards multiplier boosts cashback up to 3.5% on a chosen category for clients with $100,000+ across Bank of America and Merrill accounts — the best bank-loyalty multiplier in the US','Travel Rewards card earns 1.5× on all purchases with no foreign transaction fee and no annual fee — solid for travelers who don''t want to track categories','Full card lineup: secured, student, travel, cash rewards, and business cards all available in one institution']::text[],
  ARRAY['Best rates (3.5% cash back, 2.625× travel) locked behind Preferred Rewards — requires $100,000+ in BofA/Merrill assets','Without Preferred Rewards, BofA cards are competitive but not market leaders vs. Citi Double Cash or Capital One Quicksilver at the same tier','Premium Rewards Elite ($550/year) offers fewer differentiated travel perks than Chase Sapphire Reserve at the same fee level']::text[],
  '{"cost":8.2,"features":8.4,"ux":8.6,"support":7.8}'::jsonb,
  'The best issuer for existing Bank of America customers',
  'Bank of America''s strongest value is reserved for Preferred Rewards members — clients with $100,000+ across Bank of America and Merrill accounts unlock a rewards multiplier that takes the Travel Rewards card to 2.625× and the Cash Rewards card to 3.5% in a chosen category. Without Preferred Rewards, BofA cards are competitive but not leaders: the Travel Rewards (1.5× on everything, no foreign transaction fee) and Unlimited Cash Rewards (1.5% flat) are solid but outpaced by Citi Double Cash, Chase Freedom Unlimited, and Capital One Quicksilver at the same fee tier.',
  false, NULL, 'https://www.bankofamerica.com/credit-cards/', false, 'Best for: Existing BofA customers', 6,
  'https://www.bankofamerica.com/credit-cards/', DATE '2026-07-05', true
),
(
  NULL,
  'wells-fargo', 'us', 'personal-finance', 'credit-card-companies',
  'Wells Fargo',
  'Active Cash 2% flat — simplest cashback card',
  7.0, 4.8, 2100000, 0, 0, 0, 0,
  '{"best_card":"Wells Fargo Active Cash","max_welcome_bonus_value":300,"max_welcome_bonus_desc":"$300 cash bonus (Active Cash)","min_annual_fee":0,"max_annual_fee":95,"min_credit_score":670,"min_credit_label":"Good (670+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":false,"has_student_card":false,"has_business_card":true,"has_balance_transfer":true,"network":"Visa","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"Wells Fargo Bank N.A. — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'medium',
  '[]'::jsonb,
  ARRAY['Active Cash: 2% flat on everything, no tracking','Strong 0% APR on purchases & balance transfers','Autograph Journey: 3× restaurants, travel, streaming']::text[],
  ARRAY['Active Cash earns 2% flat cash rewards on every purchase with no annual fee and no categories to track — one of the simplest cards in the US market','Strong 0% APR intro periods on both new purchases and balance transfers, with no annual fee on the Active Cash','Autograph Journey ($95/year) earns 3× on restaurants, travel, and streaming with a $50 annual airline credit']::text[],
  ARRAY['Smaller card lineup than Chase or Capital One — fewer niche cards for specific spending patterns','No premium lounge access at any tier — the Autograph Journey does not include Priority Pass','2016 fake-accounts scandal is part of the brand''s history — a factor for trust-sensitive customers']::text[],
  '{"cost":8.8,"features":7.6,"ux":8.4,"support":7.2}'::jsonb,
  'The best issuer for a simple, uncomplicated flat-rate cash back card',
  'Wells Fargo''s Active Cash is one of the cleanest flat-rate cash back cards in the US market — 2% on every purchase with no rotating categories, no minimums, and the strongest 0% APR offer currently running (15 months on purchases and balance transfers, no annual fee). The Autograph Journey adds a mid-tier travel card with 3× on restaurants, travel, and streaming with a $50 airline credit. Wells Fargo''s card lineup is narrower than Chase or Capital One and lacks any dedicated premium lounge card — but for a user who wants one simple, uncomplicated card with a competitive rate, it''s hard to beat.',
  false, NULL, 'https://creditcards.wellsfargo.com/', false, 'Best for: Simple flat-rate cash back', 7,
  'https://creditcards.wellsfargo.com/', DATE '2026-07-05', true
),
(
  NULL,
  'us-bank', 'us', 'personal-finance', 'credit-card-companies',
  'U.S. Bank',
  'Cash+ 5% on your categories — Altitude Reserve',
  6.8, 4.8, 700000, 0, 0, 0, 0,
  '{"best_card":"U.S. Bank Cash+ Visa","max_welcome_bonus_value":400,"max_welcome_bonus_desc":"$400 cash bonus (Altitude Connect)","min_annual_fee":0,"max_annual_fee":400,"min_credit_score":670,"min_credit_label":"Good (670+)","has_travel_cards":true,"has_cashback_cards":true,"has_secured_card":true,"has_student_card":false,"has_business_card":true,"has_balance_transfer":true,"network":"Visa","app_store_rating":4.8,"review_source":"App Store iOS","regulatory_note":"U.S. Bank National Association — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'medium',
  '[]'::jsonb,
  ARRAY['Cash+: choose your own 5% categories quarterly','Altitude Reserve: 3× on Apple Pay/mobile wallet','No foreign transaction fees on flagship cards']::text[],
  ARRAY['Cash+ Visa lets cardholders choose their own 5% categories (gas, utilities, fast food, TV/internet, and more) updated quarterly, plus a 2% everyday category — the most flexible category cash back structure in the US','Altitude Reserve earns 3× on all purchases made via mobile wallet (Apple Pay, Google Pay, Samsung Pay) — the best card for heavy contactless spenders','No foreign transaction fees on the Altitude Connect and Altitude Reserve travel cards']::text[],
  ARRAY['Less brand recognition than the top-5 issuers — limited branch footprint outside core US markets','Altitude Reserve ($400/year) requires excellent credit and lags Chase Sapphire Reserve in lounge access and transfer partners','Rewards ecosystem is smaller than Chase, Amex, or Capital One — fewer redemption options for points']::text[],
  '{"cost":8.4,"features":8.2,"ux":8.2,"support":7.6}'::jsonb,
  'The best issuer for category optimizers and mobile-wallet users',
  'U.S. Bank''s niche is category optimization — the Cash+ Visa lets cardholders choose their own 5% category (gas, utilities, fast food, TV/internet, and more) and a 2% everyday category, updated quarterly, with no annual fee. The Altitude Reserve targets frequent mobile-wallet users with 3× on Apple Pay, Google Pay, and Samsung Pay purchases. The Altitude Connect ($95/year) bridges the gap with 4× travel and grocery, Priority Pass (4 visits/year), and TSA PreCheck credit. The tradeoff: U.S. Bank has fewer branches than JPMorgan Chase or Bank of America, and the rewards ecosystem is smaller.',
  false, NULL, 'https://www.usbank.com/credit-cards.html', false, 'Best for: Category maximizers', 8,
  'https://www.usbank.com/credit-cards.html', DATE '2026-07-05', true
),
(
  NULL,
  'credit-one-bank', 'us', 'personal-finance', 'credit-card-companies',
  'Credit One Bank',
  'Unsecured cards for rebuilding credit (580+)',
  6.0, 4.1, 200000, 0, 0, 0, 0,
  '{"best_card":"Credit One Bank Platinum Visa","max_welcome_bonus_value":0,"max_welcome_bonus_desc":"No welcome bonus","min_annual_fee":0,"max_annual_fee":99,"min_credit_score":300,"min_credit_label":"Bad credit OK (300+)","has_travel_cards":false,"has_cashback_cards":true,"has_secured_card":false,"has_student_card":false,"has_business_card":false,"has_balance_transfer":false,"network":"Visa","app_store_rating":4.1,"review_source":"App Store iOS","regulatory_note":"Credit One Bank N.A. — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'medium',
  '[]'::jsonb,
  ARRAY['Unsecured — no security deposit needed','Bad credit accepted (300+ FICO)','Reports to all 3 bureaus monthly']::text[],
  ARRAY['Unsecured credit cards for bad and rebuilding credit — no security deposit required, unlike secured cards at other issuers','Some cards offer 1% cash back on eligible purchases, which is uncommon for the bad-credit card segment','Reports to Equifax, Experian, and TransUnion monthly — responsible use builds credit history from day 1']::text[],
  ARRAY['Annual fees of $0–99 are charged upfront and may reduce your initial credit limit — read the terms before applying','High APRs (typically 25–30%+) — carrying a balance is very expensive and erases any cash back benefit','Approval terms vary widely — the same applicant may see different fees and limits depending on their pre-screened offer']::text[],
  '{"cost":6.2,"features":5.8,"ux":7.4,"support":6.4}'::jsonb,
  'The best unsecured option for rebuilding bad credit without a deposit',
  'Credit One Bank is the only major US card issuer that focuses almost entirely on unsecured credit cards for bad and fair credit — no security deposit is required, unlike secured cards at Discover or Capital One. Most cards offer 1% cash back on eligible purchases, which is uncommon for this segment. The catch: annual fees between $0 and $99 are charged upfront (sometimes reducing the initial credit limit), APRs run 25–30%+, and the approval process is inconsistent — the same applicant may receive wildly different terms depending on their specific credit profile and which pre-screened offer they responded to.',
  false, NULL, 'https://www.creditonebank.com/', false, 'Best for: Bad or rebuilding credit', 9,
  'https://www.creditonebank.com/', DATE '2026-07-05', true
),
(
  NULL,
  'opensky', 'us', 'personal-finance', 'credit-card-companies',
  'OpenSky / Capital Bank',
  'Secured Visa, no credit check — truly open',
  5.5, 4.3, 45000, 0, 0, 0, 0,
  '{"best_card":"OpenSky Secured Visa","max_welcome_bonus_value":0,"max_welcome_bonus_desc":"No welcome bonus","min_annual_fee":0,"max_annual_fee":35,"min_credit_score":0,"min_credit_label":"None required","has_travel_cards":false,"has_cashback_cards":false,"has_secured_card":true,"has_student_card":false,"has_business_card":false,"has_balance_transfer":false,"network":"Visa","app_store_rating":4.3,"review_source":"App Store iOS","regulatory_note":"Capital Bank N.A. (issuer) — OCC-regulated; FDIC-insured."}'::jsonb,
  'official', 'medium',
  '[]'::jsonb,
  ARRAY['No credit check — anyone can apply','OpenSky Plus: $0 annual fee option','Credit builder: reports to all 3 bureaus']::text[],
  ARRAY['No credit check required — approval is based on ability to fund a security deposit, not credit history','Reports to Equifax, Experian, and TransUnion every month — responsible use builds or rebuilds a credit file from scratch','OpenSky Plus offers a $0 annual fee version; the Classic is $35/year but no credit check on either variant']::text[],
  ARRAY['No rewards of any kind on any OpenSky card','Must deposit $200–$3,000 as collateral — it is a secured card, not unsecured','Once your credit score reaches ~580–600, a Discover Secured or Capital One Platinum gives better terms']::text[],
  '{"cost":7.0,"features":4.0,"ux":6.8,"support":6.4}'::jsonb,
  'The only option if you need no credit check at all',
  'OpenSky is the only card on this list with no credit check at all — Capital Bank (the issuer) approves applicants based solely on their ability to make a security deposit ($200–$3,000), not their credit history. It''s the genuine last-resort credit builder: OpenSky reports to all three bureaus monthly, so responsible use does build credit. The OpenSky Plus offers a $0 annual fee version. Tradeoffs are real: no rewards, and the Classic card''s $35 annual fee eats into the credit-building value unless you switch to Plus. Once your credit score clears ~580–600, graduating to a Discover Secured or Capital One Platinum gives meaningfully better terms.',
  false, NULL, 'https://www.openskycc.com/', false, 'Best for: No credit check required', 10,
  'https://www.openskycc.com/', DATE '2026-07-05', true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name    = EXCLUDED.display_name,
  tagline         = EXCLUDED.tagline,
  score           = EXCLUDED.score,
  rating          = EXCLUDED.rating,
  review_count    = EXCLUDED.review_count,
  management_fee  = EXCLUDED.management_fee,
  account_minimum = EXCLUDED.account_minimum,
  monthly_fee     = EXCLUDED.monthly_fee,
  attributes      = EXCLUDED.attributes,
  source_type     = EXCLUDED.source_type,
  confidence      = EXCLUDED.confidence,
  badges          = EXCLUDED.badges,
  chips           = EXCLUDED.chips,
  pros            = EXCLUDED.pros,
  cons            = EXCLUDED.cons,
  sub_scores      = EXCLUDED.sub_scores,
  verdict         = EXCLUDED.verdict,
  deep_dive       = EXCLUDED.deep_dive,
  is_affiliate    = EXCLUDED.is_affiliate,
  review_slug     = EXCLUDED.review_slug,
  external_url    = EXCLUDED.external_url,
  is_top_pick     = EXCLUDED.is_top_pick,
  best_for        = EXCLUDED.best_for,
  display_order   = EXCLUDED.display_order,
  source_url      = EXCLUDED.source_url,
  data_verified_at = EXCLUDED.data_verified_at,
  active          = EXCLUDED.active;
