-- Comparison Cockpit — seed UK forex-brokers (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-2): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated
-- against ukForexBrokersAttributesSchema. Mirrors ca/forex-brokers.ts /
-- au/forex-brokers.ts exactly (fee-on-amount, default costLabel). The FCA
-- actively warns about clone firms impersonating Admirals -- only the
-- verified FRN 595450 entity is linked. Every row carries a real, sourced
-- 2024-2026 regulatory/legal matter at the group/parent level, disclosed
-- with the UK-entity-vs-parent scope distinction preserved throughout.
-- Provenance: live research 2026-07-11 against official pricing pages, FCA
-- Register, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'pepperstone-forex-uk',
  'uk',
  'forex',
  'forex-brokers',
  'Pepperstone',
  'The lowest overall cost of any broker researched',
  9,
  4.3,
  3400,
  3400,
  0.0057,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Razor account: avg 0.12 pips EUR/USD', 'MT4, MT5, cTrader, TradingView', '⚠ Self-reported 2023 ASIC breach — see detail']::text[],
  ARRAY['The lowest all-in trading cost of any broker researched, via the Razor account''s ultra-tight raw spreads (average 0.12 pips on EUR/USD)', 'The broadest platform choice of the 7 (MT4, MT5, cTrader, native TradingView)', 'A leverage-cap compliance matter was self-reported and fully remediated under regulatory oversight']::text[],
  ARRAY['Was one of seven brokers found by ASIC to have breached a 2020 CFD leverage-ratio order due to a technical error (self-reported, remediated)', 'Some 2025-2026 review-aggregator complaint spikes about withdrawal delays and slippage — anecdotal, not confirmed regulatory findings']::text[],
  '{"cost":9.8,"platforms":9.4,"trust":8.2,"support":8}'::jsonb,
  'The lowest all-in trading cost researched, with a disclosed, remediated compliance matter.',
  '{"fca_frn":"FRN 684312","avg_spread_eurusd_pips":0.12,"commission_round_turn_gbp":4.5,"account_type_note":"Razor account, raw spread + per-lot commission (~£2.25/lot/side)","max_leverage":"30:1","platforms":["MT4","MT5","cTrader","TradingView","Proprietary webtrader"],"trustpilot_rating":4.3,"trustpilot_count":3400,"trustpilot_note":"uk.trustpilot.com/review/pepperstone.com","regulatory_note":"ASIC found Pepperstone was one of seven brokers that breached Australia''s 2020 CFD leverage-ratio order due to a technical error (finding published November 2023, still relevant/recent); Pepperstone self-reported the issue and ran a remediation program compensating 1,500+ affected clients. No UK FCA fine was identified."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://pepperstone.com/en-gb',
  true,
  'Traders wanting the lowest all-in cost',
  1,
  'https://pepperstone.com/en-gb',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'ig-forex-uk',
  'uk',
  'forex',
  'forex-brokers',
  'IG',
  'The UK''s largest FCA spread-betting provider since 1974',
  8.8,
  4.1,
  9000,
  9000,
  0.006,
  0,
  '[{"type":"green","label":"Widest market range"}]'::jsonb,
  ARRAY['17,000+ markets', 'UK''s largest spread-betting provider since 1974', 'No confirmed FCA fine 2024-2026']::text[],
  ARRAY['The UK''s largest FCA-authorised spread-betting provider, operating since 1974', 'The widest instrument range of any candidate researched (17,000+ markets)', 'No confirmed UK FCA enforcement action found for 2024-2026']::text[],
  ARRAY['Legacy 2015 Swiss franc (SNB) shock complaints remain referenced in ongoing third-party litigation-funding activity', 'Standard account spread (0.6 pips) is competitive but not the outright cheapest researched']::text[],
  '{"cost":8.6,"platforms":8,"trust":9,"support":8}'::jsonb,
  'The UK''s largest, most established forex provider, with the widest market range.',
  '{"fca_frn":"IG Markets Ltd FRN 195355 / IG Index Ltd FRN 114059","avg_spread_eurusd_pips":0.6,"commission_round_turn_gbp":0,"account_type_note":"Standard account, spread-only, no commission","max_leverage":"30:1","platforms":["Proprietary web/app","MT4","ProRealTime","L2 Dealer"],"trustpilot_rating":4.1,"trustpilot_count":9000,"trustpilot_note":"uk.trustpilot.com/review/ig.com","regulatory_note":"Legacy 2015 Swiss franc (SNB) shock complaints (approximately £18.4m in aggregated client losses at the time) remain referenced in ongoing third-party litigation-funding activity — Omni Bridgeway is investigating/funding a prospective UK class action on behalf of affected clients. No confirmed UK FCA fine against IG was found for 2024-2026."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.ig.com/uk',
  false,
  'Traders wanting the widest market range',
  2,
  'https://www.ig.com/uk',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'cmc-markets-forex-uk',
  'uk',
  'forex',
  'forex-brokers',
  'CMC Markets',
  'FCA-regulated since 2001, 330+ FX pairs, FSCS-eligible',
  7.9,
  4.15,
  3000,
  3000,
  0.007,
  0,
  '[]'::jsonb,
  ARRAY['FCA-regulated since 2001', '330+ FX pairs', '⚠ Active AU Federal Court class action — see detail']::text[],
  ARRAY['FCA-regulated since 2001, one of the longest track records of the 7', '330+ FX pairs, FSCS-eligible up to £85,000']::text[],
  ARRAY['An active Australian Federal Court class action (2024-2026) alleges approximately 2,500 clients who failed appropriateness screening were still allowed to trade high-risk products', 'A £4.3m one-off customer remediation charge (2025) tied to an Australian margin-netting industry review']::text[],
  '{"cost":8,"platforms":7.4,"trust":6.4,"support":7.6}'::jsonb,
  'A long-established, FSCS-eligible broker — weigh the active Australian class action.',
  '{"fca_frn":"FRN 173730","avg_spread_eurusd_pips":0.7,"commission_round_turn_gbp":0,"account_type_note":"No-commission account, spread-only; a commission-based account (0 pip + $5/lot) is also available","max_leverage":"30:1","platforms":["Proprietary Next Generation platform","MT4"],"trustpilot_rating":4.15,"trustpilot_count":3000,"trustpilot_note":"uk.trustpilot.com/review/cmcmarkets.com — sources cite 4.0-4.3/5","regulatory_note":"CMC Markets faces an active Australian Federal Court class action (2024-2026) alleging approximately 2,500 clients who failed appropriateness screening were still allowed to trade high-risk CFD products, and separately disclosed a £4.3m one-off customer remediation charge in 2025 tied to an Australian margin-netting industry review. These are Australian matters, not confirmed UK FCA enforcement actions."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.cmcmarkets.com/en-gb',
  false,
  'Traders wanting an FSCS-eligible, established broker',
  3,
  'https://www.cmcmarkets.com/en-gb',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'xtb-forex-uk',
  'uk',
  'forex',
  'forex-brokers',
  'XTB',
  'ForexBrokers.com "Best in Class" for beginners',
  7.4,
  4,
  1900,
  1900,
  0.008,
  0,
  '[]'::jsonb,
  ARRAY['ForexBrokers.com "Best in Class" (beginners)', 'Zero-commission single account', '⚠ March 2026 Polish MiFID II fine — see detail']::text[],
  ARRAY['Named ForexBrokers.com 2026 "Best in Class" for beginners', 'A simple, zero-commission single-account model across FX and CFDs']::text[],
  ARRAY['Poland''s KNF fined parent XTB S.A. approximately $5.5m in March 2026 for MiFID II client-suitability and product-governance failures (2022-2023)', 'Smallest Trustpilot review base of the 7 (1,900+ reviews)']::text[],
  '{"cost":8,"platforms":6.6,"trust":6.6,"support":7.4}'::jsonb,
  'A beginner-friendly, simple pricing model — weigh the disclosed 2026 Polish regulatory fine.',
  '{"fca_frn":"FRN 522157","avg_spread_eurusd_pips":0.8,"commission_round_turn_gbp":0,"account_type_note":"Single zero-commission account","max_leverage":"30:1","platforms":["Proprietary xStation 5 (web/desktop/mobile)"],"trustpilot_rating":4,"trustpilot_count":1900,"trustpilot_note":"uk.trustpilot.com/review/xtb.com","regulatory_note":"Poland''s KNF fined parent XTB S.A. PLN 20m (approximately $5.5m) in March 2026 for MiFID II breaches — inadequate client-suitability questionnaires and product-governance failures between January 2022 and September 2023. A prior KNF fine (PLN 9.9m, 2018) addressed asymmetric price slippage. These are Polish/EU parent-entity actions; XTB UK Ltd operates under the same group governance."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.xtb.com/en',
  false,
  'Beginners wanting a simple, guided experience',
  4,
  'https://www.xtb.com/en',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'forex-com-uk',
  'uk',
  'forex',
  'forex-brokers',
  'FOREX.com',
  'Part of the NASDAQ-listed StoneX Group',
  7,
  0,
  0,
  0,
  0.008,
  100,
  '[]'::jsonb,
  ARRAY['Backed by NASDAQ-listed StoneX', 'RAW & Standard account tiers', 'MT4, MT5, TradingView']::text[],
  ARRAY['Backed by StoneX Group Inc. (NASDAQ-listed parent), a large, well-capitalized institution', 'Choice of spread-only Standard account or commission-based RAW account for high-volume traders']::text[],
  ARRAY['Parent StoneX has a long US regulatory-sanction record and several 2024-2025 exchange-level fines (NYMEX, CME, CFTC)', 'No independent Trustpilot rating confirmed for the UK entity at research time']::text[],
  '{"cost":7.6,"platforms":8,"trust":6.6,"support":7}'::jsonb,
  'A well-capitalized global broker — weigh the disclosed US parent-level regulatory history.',
  '{"fca_frn":"StoneX Financial Ltd FRN 446717","avg_spread_eurusd_pips":0.8,"commission_round_turn_gbp":0,"account_type_note":"Standard account, spread-only, no commission; RAW account offers tighter spreads plus a per-lot commission","max_leverage":"30:1","platforms":["Proprietary web platform","MT4","MT5","TradingView"],"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No independent UK-specific Trustpilot rating confirmed at research time — shown as not yet rated","regulatory_note":"Parent StoneX Financial has a long US regulatory-sanction record (FINRA discloses 76 sanctions historically) and several 2024-2025 exchange-level fines: NYMEX ~$575k (April 2025, block-trade disclosure failures), CME $20k (September 2025, physically-settled futures delivery violation), CME $2,500 (December 2025, data-entry threshold breach), and a CFTC $650k fine against StoneX Markets LLC (disclosure breach). These are US CFTC/exchange actions against the StoneX group/US entities, not the UK FCA-regulated FOREX.com entity, but reflect on overall group compliance culture."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.forex.com/en-uk',
  false,
  'Traders wanting a large, well-capitalized parent',
  5,
  'https://www.forex.com/en-uk',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'admirals-uk',
  'uk',
  'forex',
  'forex-brokers',
  'Admirals',
  'MetaTrader specialist — verify the genuine FRN before trading',
  6.8,
  4.2,
  2150,
  2150,
  0.008,
  250,
  '[]'::jsonb,
  ARRAY['MT4 & MT5 specialist', 'FCA-regulated since 2013', '⚠ FCA actively warns of clone sites — see detail']::text[],
  ARRAY['A dedicated MetaTrader specialist (MT4 and MT5), FCA-regulated since 2013', '8,000+ instruments including FX, CFDs, stocks and fractional shares']::text[],
  ARRAY['The FCA actively warns about fraudulent clone websites impersonating Admirals — always verify the genuine FRN 595450 before depositing funds', 'Admirals Group''s audited FY2025 results showed an €18.5m net loss and a 55% year-over-year drop in net trading income']::text[],
  '{"cost":7.4,"platforms":7,"trust":6,"support":7}'::jsonb,
  'A genuine MetaTrader specialist — the clone-site risk is real, verify the FRN carefully.',
  '{"fca_frn":"Admiral Markets UK Ltd FRN 595450 (verify this exact FRN — multiple clone sites exist)","avg_spread_eurusd_pips":0.8,"commission_round_turn_gbp":0,"account_type_note":"Invest.MT5-type account, spread-only; a Zero account (0 pip + commission) is also available","max_leverage":"30:1","platforms":["MT4","MT5"],"trustpilot_rating":4.2,"trustpilot_count":2150,"trustpilot_note":"uk.trustpilot.com/review/admiralmarkets.com — the correct/claimed corporate domain; an unclaimed \"admiral-markets.com\" alternate profile shows a much lower score from only 3 reviews and should not be conflated with this one","regulatory_note":"The FCA has repeatedly (most recently updated January 2024, with further warnings since) flagged fraudulent clone websites impersonating Admirals (e.g. admiral-fx.com, fxsadmiral.com, admrlmrkts.co) — these offer no FSCS or Financial Ombudsman protection. Separately, Estonia''s Finantsinspektsioon fined the Estonia entity (Admiral Markets AS) €32,000 (2021) and approximately €20,000 (reporting failures); in April 2026 Admirals voluntarily surrendered its Estonian investment-firm licence as part of a restructuring (not a sanction) to consolidate under its Cyprus licence. Admirals Group''s FY2025 results showed an €18.5m net loss and a 55% YoY drop in net trading income, alongside an April 2024 pause on onboarding new European clients linked to CySEC regulatory friction. None of this is a UK FCA action against Admiral Markets UK Ltd (FRN 595450) specifically — its issue set is dominated by third-party clone fraud, not its own conduct."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://admiralmarkets.com/',
  false,
  'MetaTrader users who have verified the genuine FRN',
  6,
  'https://admiralmarkets.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'saxo-forex-uk',
  'uk',
  'forex',
  'forex-brokers',
  'Saxo',
  'BrokerChooser 2026 UK forex overall winner — with a disclosed Danish AML fine',
  6.6,
  3.5,
  8200,
  8200,
  0.007,
  500,
  '[]'::jsonb,
  ARRAY['BrokerChooser 2026 UK forex winner', '185+ FX pairs', '⚠ ~£37-40M Danish AML fine — see detail']::text[],
  ARRAY['Named BrokerChooser 2026 overall winner among UK forex brokers (100+ brokers tested)', '185+ FX pairs across a tiered institutional-grade pricing structure']::text[],
  ARRAY['Denmark''s FSA fined parent Saxo Bank approximately $46-50m for AML Act violations related to KYC/customer due-diligence failures', 'A high-barrier tiered account structure (£500 minimum for Classic, up to £1,000,000 for VIP) and the lowest Trustpilot rating of the 7 (~3.5/5)']::text[],
  '{"cost":7.6,"platforms":7.4,"trust":5,"support":7}'::jsonb,
  'An award-winning platform with real scale — weigh the disclosed Danish AML fine carefully.',
  '{"fca_frn":"FRN 551422 (confirm directly against the FCA Register before relying on this number)","avg_spread_eurusd_pips":0.7,"commission_round_turn_gbp":0,"account_type_note":"Classic tier, spread-only; VIP tier offers tighter spreads (~0.5 pips) at a much higher minimum deposit","max_leverage":"30:1","platforms":["SaxoTraderGO","SaxoTraderPRO","TradingView"],"trustpilot_rating":3.5,"trustpilot_count":8200,"trustpilot_note":"uk.trustpilot.com/review/home.saxo — lowest rating of the 7","regulatory_note":"Denmark''s Financial Supervisory Authority fined parent Saxo Bank approximately $46-50m for AML Act violations related to KYC/customer due-diligence failures, disclosed alongside a 2025 ownership-change process (the purchase price was adjusted down by approximately $8.7m to reflect the fine); the regulator found no evidence that actual money laundering occurred, only compliance-process failures. Saxo''s Hong Kong unit was separately fined approximately $4m for unrelated breaches."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.home.saxo/en-gb',
  false,
  'Traders wanting an award-winning institutional platform',
  7,
  'https://www.home.saxo/en-gb',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
