-- Comparison Cockpit — seed UK cfd-brokers (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-2): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated
-- against ukCfdBrokersAttributesSchema. Unlike au/cfd-brokers.ts (which
-- deviated to 'banking'/£0 due to incompatible spread units across its 7
-- AU providers), all 7 UK candidates gave a consistent pip-quotable spread
-- figure, so 'fee-on-amount' is used, costLabel "Spread cost". Every row
-- carries a real, sourced 2024-2026 regulatory/legal matter at the
-- group/parent level (CMC's AU class action, Saxo's ~£37-40M Danish AML
-- fine, XTB's Polish MiFID II fine, Pepperstone's self-reported ASIC
-- breach, eToro's SEC/Italian fines) -- none are UK FCA actions against the
-- UK entity itself, disclosed with that scope distinction preserved.
-- Provenance: live research 2026-07-11 against official pricing pages, FCA
-- Register, ASIC, Danish FSA, Polish KNF, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'ig-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'IG',
  '17,000+ markets, the widest CFD range of any candidate researched',
  9.1,
  4.1,
  9000,
  9000,
  0.006,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['17,000+ markets', 'Tightest spread researched (0.6 pips)', 'No confirmed FCA fine 2024-2026']::text[],
  ARRAY['The widest CFD instrument range of any candidate researched (17,000+ markets)', 'The tightest EUR/USD-style spread researched (0.6 pips)', 'No confirmed UK FCA enforcement action found for 2024-2026']::text[],
  ARRAY['Legacy 2015 Swiss franc (SNB) shock complaints remain referenced in ongoing third-party litigation-funding activity', 'Broadest range means a steeper learning curve for absolute beginners']::text[],
  '{"cost":9,"range":10,"trust":9,"support":8}'::jsonb,
  'The widest range and tightest spread researched, with a clean recent regulatory record.',
  '{"fca_frn":"IG Markets Ltd FRN 195355 / IG Index Ltd FRN 114059","avg_spread_eurusd_pips":0.6,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown; individual index/share/commodity CFD spreads differ and should be checked per-instrument on IG''s own site","instrument_range_note":"17,000+ markets — the widest range of the 7 candidates","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["Proprietary web/app","MT4","ProRealTime","L2 Dealer"],"retail_loss_pct":71,"retail_loss_note":"recently cited 69-74% depending on period/source, verify live figure","trustpilot_rating":4.1,"trustpilot_count":9000,"trustpilot_note":"uk.trustpilot.com/review/ig.com","regulatory_note":"Legacy 2015 Swiss franc (SNB) shock complaints (approximately £18.4m in aggregated client losses at the time) remain referenced in ongoing third-party litigation-funding activity — Omni Bridgeway is investigating/funding a prospective UK class action on behalf of affected CFD clients. No confirmed UK FCA fine against IG was found for 2024-2026."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.ig.com/uk',
  true,
  'Traders wanting the widest CFD range',
  1,
  'https://www.ig.com/uk',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'capital-com',
  'uk',
  'trading',
  'cfd-brokers',
  'Capital.com',
  'The lowest barrier to entry — £20 minimum deposit',
  8.8,
  4.6,
  13000,
  13000,
  0.007,
  20,
  '[{"type":"green","label":"Best for beginners"}]'::jsonb,
  ARRAY['£20 minimum deposit (lowest of the 7)', 'Highest Trustpilot rating (4.6/5)', 'Single commission-free pricing model']::text[],
  ARRAY['The lowest minimum deposit of any candidate researched (£20)', 'The highest Trustpilot rating of the 7 (4.6/5, 13,000+ reviews)', 'A single, simple commission-free pricing model across both FX and CFDs — no confusing account tiers']::text[],
  ARRAY['A narrower instrument range (5,000+ CFDs) than IG or Saxo', 'No FCA loss-percentage figure was independently confirmed at research time']::text[],
  '{"cost":8.6,"range":7,"trust":9.6,"support":8.4}'::jsonb,
  'The most accessible, best-reviewed entry point for new CFD traders.',
  '{"fca_frn":"Capital Com (UK) Ltd FRN 793714","avg_spread_eurusd_pips":0.7,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown; individual index/share/commodity CFD spreads differ and should be checked per-instrument","instrument_range_note":"5,000+ CFDs","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["Proprietary web/mobile","MT4"],"retail_loss_pct":null,"retail_loss_note":"Not independently confirmed at research time","trustpilot_rating":4.6,"trustpilot_count":13000,"trustpilot_note":"uk.trustpilot.com/review/capital.com","regulatory_note":"No FCA enforcement action, fine or notable lawsuit was found for 2024-2026 in this research pass — noted as \"none found\" rather than a confirmed clean record, given limited primary-source depth available."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://capital.com/en-gb',
  false,
  'Beginners wanting a low-deposit, simple pricing model',
  2,
  'https://capital.com/en-gb',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'pepperstone-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'Pepperstone',
  'The broadest platform choice — with a disclosed 2023 leverage-breach remediation',
  8.7,
  4.3,
  3400,
  3400,
  0.01,
  0,
  '[{"type":"sky","label":"Best for active traders"}]'::jsonb,
  ARRAY['MT4, MT5, cTrader, TradingView', 'Razor account: ultra-tight raw spreads', '⚠ Self-reported 2023 ASIC breach — see detail']::text[],
  ARRAY['The broadest platform choice of the 7 (MT4, MT5, cTrader, native TradingView)', 'Razor account offers ultra-tight raw spreads for active/high-volume traders', 'A leverage-cap compliance matter was self-reported and fully remediated under regulatory oversight']::text[],
  ARRAY['Was one of seven brokers found by ASIC to have breached a 2020 CFD leverage-ratio order due to a technical error (self-reported, remediated)', 'Some 2025-2026 review-aggregator complaint spikes about withdrawal delays and slippage — anecdotal, not confirmed regulatory findings']::text[],
  '{"cost":8.6,"range":8,"trust":8.2,"support":8}'::jsonb,
  'The best platform choice for active traders — a disclosed, remediated compliance matter to weigh.',
  '{"fca_frn":"FRN 684312","avg_spread_eurusd_pips":1,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown for the Standard account; the Razor account offers tighter raw spreads plus a per-lot commission — individual CFD instrument spreads differ from this figure","instrument_range_note":"1,350+ CFDs — FX/index/commodity/share/crypto CFD focus, narrower range than IG/CMC/Saxo","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["MT4","MT5","cTrader","TradingView","Proprietary webtrader"],"retail_loss_pct":80,"retail_loss_note":"recently cited in a wide 74-89% range depending on source/period, verify live","trustpilot_rating":4.3,"trustpilot_count":3400,"trustpilot_note":"uk.trustpilot.com/review/pepperstone.com","regulatory_note":"ASIC found Pepperstone was one of seven brokers that breached Australia''s 2020 CFD leverage-ratio order due to a technical error (finding published November 2023, still relevant/recent); Pepperstone self-reported the issue and ran a remediation program compensating 1,500+ affected clients. No UK FCA fine was identified."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://pepperstone.com/en-gb',
  false,
  'Active traders wanting the broadest platform choice',
  3,
  'https://pepperstone.com/en-gb',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'xtb-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'XTB',
  'A large instrument range on a single zero-commission account',
  8,
  4,
  1900,
  1900,
  0.008,
  0,
  '[]'::jsonb,
  ARRAY['11,400+ instruments', 'Single zero-commission account', '⚠ March 2026 Polish MiFID II fine — see detail']::text[],
  ARRAY['A large instrument range (11,400+ FX, indices, commodities, share and ETF CFDs) on one simple account', 'Proprietary xStation 5 platform across web, desktop and mobile']::text[],
  ARRAY['Poland''s KNF fined parent XTB S.A. approximately $5.5m in March 2026 for MiFID II client-suitability and product-governance failures (2022-2023)', 'Smallest Trustpilot review base of the 7 (1,900+ reviews)']::text[],
  '{"cost":8.2,"range":8.6,"trust":6.6,"support":7.4}'::jsonb,
  'A large, simple instrument range — weigh the disclosed 2026 Polish regulatory fine.',
  '{"fca_frn":"FRN 522157","avg_spread_eurusd_pips":0.8,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown; individual index/share/commodity CFD spreads differ and should be checked per-instrument","instrument_range_note":"11,400+ instruments (FX, indices, commodities, share CFDs, ETF CFDs, plus underlying stock/ETF investing)","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["Proprietary xStation 5 (web/desktop/mobile)"],"retail_loss_pct":70,"retail_loss_note":"recently cited around 70%, verify live","trustpilot_rating":4,"trustpilot_count":1900,"trustpilot_note":"uk.trustpilot.com/review/xtb.com","regulatory_note":"Poland''s KNF fined parent XTB S.A. PLN 20m (approximately $5.5m) in March 2026 for MiFID II breaches — inadequate client-suitability questionnaires and product-governance failures between January 2022 and September 2023 that let inexperienced clients access high-risk CFDs. A prior KNF fine (PLN 9.9m, 2018) addressed asymmetric price slippage. Q1 2025 disclosures also flagged ongoing, non-final regulatory inspections in Czechia, Belize, Spain and Portugal. These are Polish/EU parent-entity actions; XTB UK Ltd operates under the same group governance."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.xtb.com/en',
  false,
  'Traders wanting a large range on one simple account',
  4,
  'https://www.xtb.com/en',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'cmc-markets-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'CMC Markets',
  'FCA-regulated since 2001 — with an active Australian class action disclosed',
  7.6,
  4.15,
  3000,
  3000,
  0.007,
  0,
  '[]'::jsonb,
  ARRAY['FCA-regulated since 2001', '12,000+ CFD instruments', '⚠ Active AU Federal Court class action — see detail']::text[],
  ARRAY['FCA-regulated since 2001, one of the longest track records of the 7', '12,000+ CFD/spread-bet instruments across a proprietary platform']::text[],
  ARRAY['An active Australian Federal Court class action (2024-2026) alleges approximately 2,500 clients who failed appropriateness screening were still allowed to trade high-risk products', 'A £4.3m one-off customer remediation charge (2025) tied to an Australian margin-netting industry review']::text[],
  '{"cost":8,"range":8.6,"trust":6.4,"support":7.6}'::jsonb,
  'A long-established broker — weigh the active Australian class action against the UK-specific regulatory record.',
  '{"fca_frn":"FRN 173730","avg_spread_eurusd_pips":0.7,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style no-commission account spread shown; a commission-based account (0 pip + $5/lot) is also available; individual CFD instrument spreads vary","instrument_range_note":"12,000+ CFD/spread-bet instruments","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["Proprietary Next Generation platform","MT4"],"retail_loss_pct":68,"retail_loss_note":"recently cited around 68% (range 67-84% across periods), verify live","trustpilot_rating":4.15,"trustpilot_count":3000,"trustpilot_note":"uk.trustpilot.com/review/cmcmarkets.com — sources cite 4.0-4.3/5","regulatory_note":"CMC Markets faces an active Australian Federal Court class action (2024-2026) alleging approximately 2,500 clients who failed appropriateness screening were still allowed to trade high-risk CFD products, and separately disclosed a £4.3m one-off customer remediation charge in 2025 tied to an Australian margin-netting industry review. A former senior employee also filed a 2024 bonus-scheme lawsuit (~$1m claim). These are Australian/employment matters, not confirmed UK FCA enforcement actions."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.cmcmarkets.com/en-gb',
  false,
  'Traders wanting an FCA-regulated broker since 2001',
  5,
  'https://www.cmcmarkets.com/en-gb',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'etoro-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'eToro',
  'The market leader in social/copy trading',
  7.4,
  4.15,
  30000,
  30000,
  0.01,
  10,
  '[]'::jsonb,
  ARRAY['Social/copy trading market leader', 'Largest review base (30,000+)', '⚠ US/Italian entity fines — see detail']::text[],
  ARRAY['The market leader in social/copy trading, letting users automatically mirror other traders'' positions', 'The largest Trustpilot review base of the 7 (30,000+ reviews)', 'Low $10 minimum deposit']::text[],
  ARRAY['A narrower CFD-specific range than most peers (approximately 50 currency pairs, 15 indices) — eToro''s core strength is stocks/crypto/social trading, not tight CFD spreads', 'No proprietary MT4/MT5/cTrader/TradingView integration — web/app platform only']::text[],
  '{"cost":7.6,"range":6.4,"trust":7.4,"support":7.6}'::jsonb,
  'The best social/copy-trading platform — weigh its narrower CFD-specific range and disclosed non-UK fines.',
  '{"fca_frn":"FRN 583263","avg_spread_eurusd_pips":1,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown; eToro''s core differentiator is social/copy trading rather than tight CFD spreads — individual instrument spreads vary","instrument_range_note":"3,000+ assets total (stocks/ETFs/crypto/commodities); CFD-specific coverage is narrower — approximately 50 currency pairs, 15 indices","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares, 2:1 crypto","platforms":["Proprietary web/app only"],"retail_loss_pct":61,"retail_loss_note":"recently cited around 61%, notably lower than most peers — plausibly reflects eToro''s retail base skewing toward long-only investing rather than leveraged CFDs, verify live","trustpilot_rating":4.15,"trustpilot_count":30000,"trustpilot_note":"uk.trustpilot.com/review/etoro.com","regulatory_note":"Not UK FCA-specific, but relevant for honest disclosure: the SEC fined eToro USA $1.5m (September 2024) for operating as an unregistered broker/clearing agency in US crypto trading (a separate US entity from the UK FCA-regulated business); Italy''s competition authority fined eToro €1.3m (2023) for misleading fee advertising; historical CySEC (€50k, 2013) and Canadian regulator ($550k + $1.8m disgorgement, 2018) settlements also exist. None of these are UK FCA actions against eToro (UK) Ltd specifically."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.etoro.com/',
  false,
  'Traders wanting social/copy trading',
  6,
  'https://www.etoro.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'saxo-cfd-uk',
  'uk',
  'trading',
  'cfd-brokers',
  'Saxo',
  'The widest multi-asset range — with a disclosed ~£37-40M Danish AML fine',
  7,
  3.5,
  8200,
  8200,
  0.007,
  500,
  '[]'::jsonb,
  ARRAY['8,800+ CFDs, ~19,000+ instruments overall', 'SaxoTraderGO/PRO + TradingView', '⚠ ~£37-40M Danish AML fine — see detail']::text[],
  ARRAY['The widest overall instrument range of the 7 by far (~19,000+ tradable instruments across all product types, reflecting Saxo''s investment-bank positioning)', 'SaxoTraderGO (web/app), SaxoTraderPRO (desktop) and TradingView integration']::text[],
  ARRAY['Denmark''s FSA fined parent Saxo Bank approximately $46-50m (one of the largest fines in years) for AML Act violations related to KYC/customer due-diligence failures', 'The lowest Trustpilot rating of the 7 (~3.5/5), and a tiered account structure (£500 minimum for Classic, up to £1,000,000 for VIP) that is notably higher-barrier than peers']::text[],
  '{"cost":7.8,"range":9.4,"trust":5,"support":7}'::jsonb,
  'The widest multi-asset range in this comparison — weigh the disclosed Danish AML fine carefully.',
  '{"fca_frn":"FRN 551422 (confirm directly against the FCA Register before relying on this number)","avg_spread_eurusd_pips":0.7,"commission_round_turn_gbp":0,"spread_note":"EUR/USD-style spread shown for the Classic tier (VIP tier tighter, from ~0.5 pips); individual CFD instrument spreads across Saxo''s much broader 8,800+ CFD range vary","instrument_range_note":"8,800+ CFDs, part of a wider ~19,000+ tradable-instrument platform including bonds/options — the widest range of the 7","max_leverage":"30:1 FX majors, 20:1 indices/gold, 10:1 other commodities, 5:1 shares","platforms":["SaxoTraderGO","SaxoTraderPRO","TradingView"],"retail_loss_pct":null,"retail_loss_note":"Not independently confirmed at research time","trustpilot_rating":3.5,"trustpilot_count":8200,"trustpilot_note":"uk.trustpilot.com/review/home.saxo — lowest rating of the 7","regulatory_note":"Denmark''s Financial Supervisory Authority fined parent Saxo Bank approximately $46-50m for AML Act violations related to KYC/customer due-diligence failures, disclosed alongside a 2025 ownership-change process (the purchase price was adjusted down by approximately $8.7m to reflect the fine); the regulator found no evidence that actual money laundering occurred, only compliance-process failures. Saxo''s Hong Kong unit was separately fined approximately $4m for unrelated breaches. These are Danish/Hong Kong parent-entity actions, not a UK FCA fine on Saxo Capital Markets UK, but disclosed given their severity and recency."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.home.saxo/en-gb',
  false,
  'Investors wanting the widest multi-asset range',
  7,
  'https://www.home.saxo/en-gb',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
