-- GENERATED by scripts/research/build-trading-confidence-reasons.mjs — DO NOT EDIT BY HAND.
-- Backfills attributes.confidence_reason for the 8 fully-sourced (audited-intent)
-- us/trading/trading-platforms rows, resolving step-2 release-gate M1. The text
-- is a factual provenance statement derived from the source-matrix
--   docs/superpowers/plans/2026-07-03-cockpit-trading-platforms-source-matrix.md
-- (no person/qualification/testing claim; checked against
-- lib/editorial/forbidden-claims.ts by the seed test).
--
-- eToro is deliberately NOT here: its extended_hours cell is low/open, so it is
-- not audited-intent and keeps its own T0b confidence_reason (stays provisional).
--
-- Apply AFTER 20260719130000_seed_trading_research_sources.sql. Together they
-- make these 8 rows satisfy every audited invariant → they render with score +
-- rank at runtime; eToro stays provisional.
--
-- APPLICATION: manual, ONLY via this versioned file (no service-key DML path).
-- NOT auto-applied. STATUS: APPLIED to production on 2026-07-19 and verified
-- — see the apply log under docs/superpowers/plans/data/. Re-running is safe
-- (idempotent).
-- Regenerate with: node scripts/research/build-trading-confidence-reasons.mjs

BEGIN;

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against official published sources."'::jsonb, true)
WHERE slug = 'fidelity' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'charles-schwab' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'interactive-brokers' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'robinhood' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'webull' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against official published sources."'::jsonb, true)
WHERE slug = 'etrade' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'tastytrade' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

UPDATE public.product_attributes
SET attributes = jsonb_set(attributes, '{confidence_reason}', '"All four compared facts — options contract fee, minimum deposit, extended-hours availability and TradingView integration — were verified on 2026-07-03 against a combination of official and independent published sources."'::jsonb, true)
WHERE slug = 'merrill-edge' AND market = 'us' AND category = 'trading' AND topic = 'trading-platforms';

COMMIT;

-- ── ROLLBACK (run manually) — removes only the keys this migration added ──
-- BEGIN;
-- UPDATE public.product_attributes
-- SET attributes = attributes - 'confidence_reason'
-- WHERE market = 'us' AND category = 'trading' AND topic = 'trading-platforms'
--   AND slug IN ('fidelity', 'charles-schwab', 'interactive-brokers', 'robinhood', 'webull', 'etrade', 'tastytrade', 'merrill-edge');
-- COMMIT;
