-- Comparison Cockpit — seed CA mortgage-brokers (market='ca',
-- category='housing', CA-exclusive topic). Visit-only launch (AU/CA/UK
-- rollout, Stage 2 Slice CA-2): affiliate_link_id NULL, is_affiliate=false,
-- review_slug NULL, external_url = provider homepage. Idempotent (ON
-- CONFLICT DO UPDATE). Attributes validated against
-- caMortgageBrokersAttributesSchema. costModel uses a flatFeeAccessor
-- returning 0 (every provider is paid by the lender, not the consumer, for
-- a standard residential mortgage) — see file header in
-- lib/comparison/topics/ca/mortgage-brokers.ts. Mortgage Alliance replaces
-- Dominion Lending Centres per the approved shortlist; DLC's 2023
-- Competition Bureau inquiry was discontinued in June 2024 with no
-- wrongdoing found, disclosed on Mortgage Alliance's row for context, not
-- as an exclusion-for-cause.
-- Provenance: live research 2026-07-11 against official pricing pages,
-- FSRA, BCFSA, RECA and other provincial regulators.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'ratehub',
  'ca',
  'housing',
  'mortgage-brokers',
  'Ratehub',
  'Canada''s dominant rate aggregator, with its own licensed brokerage',
  9,
  4.3,
  92,
  92,
  0,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['$15B+ mortgages facilitated since 2015', 'Own brokerage: CanWise', '$0 to you — paid by the lender']::text[],
  ARRAY['Canada''s dominant rate-comparison platform, having facilitated $15B+ in mortgages since 2015', 'Owns a licensed in-house brokerage (CanWise) for direct execution, not just rate listing', 'Confirmed licensing in Ontario, Quebec and BC, with 30+ lenders on its panel']::text[],
  ARRAY['Explicitly states it does not include the entire universe of available offers', 'Customer reviews describe occasional pre-approval/rate-creep friction once an agent engages']::text[],
  '{"trust":9,"coverage":8.4,"rating":8.6}'::jsonb,
  'Canada''s most recognized rate-comparison brand, backed by a real licensed brokerage.',
  '{"business_model":"rate_comparison_platform","business_model_note":"Rate-comparison/publisher platform that also owns an in-house licensed brokerage (formerly branded CanWise Financial); compensated via lender referral fees and sponsored placements","provincial_licenses":["ON","QC","BC"],"lender_panel_note":"30+ lenders including online lenders and MICs; states it does not include the entire market","consumer_fee_note":"$0 — paid by the lender","trustpilot_rating":4.3,"trustpilot_count":92,"trustpilot_note":"ca.trustpilot.com","regulatory_note":"Recurring complaint themes in customer reviews: pre-approvals dropped or rescinded close to renewal, rate or cost creep once an agent engages, and slow communication — service-quality issues, not confirmed regulatory action."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.ratehub.ca/',
  true,
  'Borrowers wanting the most recognized aggregator',
  1,
  'https://www.ratehub.ca/about-ratehub',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'nesto',
  'ca',
  'housing',
  'mortgage-brokers',
  'nesto',
  'Canada''s largest fully-digital mortgage broker',
  8.8,
  4.4,
  344,
  344,
  0,
  0,
  '[{"type":"green","label":"Best fully-digital experience"}]'::jsonb,
  ARRAY['450,000+ customers', 'Rate-match guarantee', '150-day rate hold']::text[],
  ARRAY['Canada''s largest fully-digital mortgage broker (450,000+ customers since 2018)', 'Rate-match guarantee and a 150-day rate hold, both genuinely differentiated features', 'Broad provincial licensing footprint (8 provinces confirmed) with published license numbers']::text[],
  ARRAY['Blends broker and in-house-lender roles on some files — not a pure independent broker for every mortgage', 'Lender panel size not currently disclosed as a headline number']::text[],
  '{"trust":8.6,"coverage":9,"rating":8.8}'::jsonb,
  'The largest and most fully-digital mortgage experience in this comparison.',
  '{"business_model":"hybrid_broker_lender","business_model_note":"Digital mortgage brokerage that also funds some of its own insured mortgages directly — a broker/lender hybrid depending on the specific product","provincial_licenses":["ON","BC","AB","SK","NB","NS","NL","QC"],"lender_panel_note":"11+ institutional lending partners historically disclosed, plus nesto''s own funding capacity for some insured mortgages","consumer_fee_note":"$0 for standard files; fees can apply on non-standard/self-employed files — confirm per file","trustpilot_rating":4.4,"trustpilot_count":344,"trustpilot_note":"ca.trustpilot.com; Google shows ~4.5/5 from 1,500+ reviews","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.nesto.ca/',
  false,
  'Borrowers wanting a fully digital experience',
  2,
  'https://www.nesto.ca/licences/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'true-north-mortgage',
  'ca',
  'housing',
  'mortgage-brokers',
  'True North Mortgage',
  'The highest independently corroborated customer rating researched',
  8.6,
  4.9,
  2500,
  2500,
  0,
  0,
  '[{"type":"sky","label":"Highest-rated by customers"}]'::jsonb,
  ARRAY['4.9/5 Trustpilot', 'In-house lender: THINK Financial', 'Serving Canada since 1999']::text[],
  ARRAY['Highest customer rating researched for this comparison (4.9/5 on Trustpilot)', 'Operating since 1999, with an in-house lender (THINK Financial) used alongside third-party A/B lenders', 'Serves Atlantic Canada in addition to the provinces most competitors focus on']::text[],
  ARRAY['The company''s own "About" page still references FSCO, Ontario''s mortgage regulator retired in 2019 and replaced by FSRA — confirm the current FSRA registration directly rather than trusting the website reference', 'Claims 17,000+ five-star reviews across platforms; this figure is self-reported']::text[],
  '{"trust":8.4,"coverage":8,"rating":9.6}'::jsonb,
  'The highest customer rating in this comparison, with a genuine in-house lending arm.',
  '{"business_model":"hybrid_broker_lender","business_model_note":"Traditional brokerage that also owns an in-house lender, THINK Financial, used for some client files alongside third-party A/B lenders","provincial_licenses":["AB","BC","ON"],"lender_panel_note":"Works with large public banks and small private trust companies, plus its in-house lender THINK Financial; exact panel size not disclosed","consumer_fee_note":"$0 standard","trustpilot_rating":4.9,"trustpilot_count":2500,"trustpilot_note":"ca.trustpilot.com — rating sourced via the approved candidate shortlist (NerdWallet Canada/Trustpilot); the company separately claims 17,000+ five-star reviews across all platforms, which was not independently re-confirmed this pass","regulatory_note":"True North Mortgage''s own \"About\" page still references FSCO, the Ontario mortgage regulator retired in 2019 and replaced by FSRA — stale website content rather than a licensing problem, but worth confirming the current FSRA registration number directly before relying on it."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.truenorthmortgage.ca/',
  false,
  'Borrowers prioritizing customer satisfaction',
  3,
  'https://www.truenorthmortgage.ca/about-us/company-profile',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'butler-mortgage',
  'ca',
  'housing',
  'mortgage-brokers',
  'Butler Mortgage',
  'One of the largest disclosed lender panels in this comparison',
  8,
  0,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['350+ lending partners', 'Rate-beat guarantee', 'Discount brokerage since 1997']::text[],
  ARRAY['Claims 350+ lending partners — the largest disclosed panel of any candidate researched', 'Discount brokerage model (cuts its own commission rather than charging fees) operating since 1997', 'Rate-beat and after-approval rate guarantees']::text[],
  ARRAY['Public reviews are mixed, with no single reliable aggregate score found across platforms', 'Some complaints describe rate increases after the initial quote, and one account alleges pressure on a client who threatened a negative review']::text[],
  '{"trust":7.2,"coverage":7.8,"rating":6.8}'::jsonb,
  'The largest disclosed lender panel of any candidate — service consistency is the real variable.',
  '{"business_model":"licensed_brokerage","business_model_note":"Discount mortgage brokerage in business since 1997; buys down rates by cutting its own commission rather than charging consumer fees","provincial_licenses":["ON","BC","AB"],"lender_panel_note":"350+ lending partners — one of the largest disclosed panels among Canadian brokers","consumer_fee_note":"$0, with a lowest-rate and after-approval rate guarantee","trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"Public reviews are mixed across platforms with no single reliable aggregate score found — see regulatory note for specific complaint themes","regulatory_note":"Public complaints describe rate creep after the initial quote, and one account alleges the company pressured a client who threatened a negative review. No regulatory enforcement action found."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.butlermortgage.ca/',
  false,
  'Borrowers wanting the largest lender panel',
  4,
  'https://www.butlermortgage.ca/our-lenders/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'pine',
  'ca',
  'housing',
  'mortgage-brokers',
  'Pine',
  'Digital-first, distributed through Wealthsimple',
  7.8,
  4.7,
  308,
  308,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Distributed via Wealthsimple', 'Broker + direct lender', '4.7/5 Google (308 reviews)']::text[],
  ARRAY['Functions as both a licensed broker and a direct lender, funded via partner financial institutions', 'Distributed partly through Wealthsimple Mortgage Services Inc. — a natural fit for existing Wealthsimple users', '4.7/5 on Google from 308 reviews, praising service speed and rates']::text[],
  ARRAY['Not yet licensed in Quebec or the territories (Quebec approval reportedly in progress)', 'No meaningful Trustpilot sample yet, consistent with its 2021 founding']::text[],
  '{"trust":7.6,"coverage":7,"rating":8.4}'::jsonb,
  'A modern, digital-first hybrid broker/lender with a genuine Wealthsimple integration.',
  '{"business_model":"hybrid_broker_lender","business_model_note":"Digital-first mortgage broker, founded 2021, that also functions as a direct lender funded via partner financial institutions; distributed partly through Wealthsimple Mortgage Services Inc., which earns a separate referral fee","provincial_licenses":["ON","BC","AB","SK","NB","NS","NL"],"lender_panel_note":"Functions as both a licensed broker and a direct lender funded via partner financial institutions; exact panel size not disclosed","consumer_fee_note":"$0 — no origination, application, processing, underwriting or commitment-break fees; standard third-party costs (appraisal, legal) may still apply","trustpilot_rating":4.7,"trustpilot_count":308,"trustpilot_note":"Google rating (308 reviews) — no meaningful Trustpilot sample yet, consistent with Pine''s 2021 founding","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.pine.ca/',
  false,
  'Wealthsimple users wanting an integrated mortgage',
  5,
  'https://www.pine.ca/mortgage',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'perch',
  'ca',
  'housing',
  'mortgage-brokers',
  'Perch',
  'A smaller digital broker with a BBB A+ rating since 2023',
  7.4,
  0,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['30+ lenders', 'BBB-accredited since 2023', 'Ongoing renewal optimization focus']::text[],
  ARRAY['BBB-accredited since August 2023, with a clean profile at research time', 'Positions itself around ongoing renewal-scenario optimization, not just origination', 'Aggregates 30+ lenders (banks, credit unions, B-lenders, private lenders)']::text[],
  ARRAY['Only its Ontario FSRA license was independently confirmed, despite claims of operating in all provinces', 'No consolidated Trustpilot page found specifically for the Canadian mortgage entity — thinner third-party verification than larger peers']::text[],
  '{"trust":7,"coverage":6.4,"rating":6.6}'::jsonb,
  'A smaller, BBB-accredited digital broker — confirm your province''s licensing directly.',
  '{"business_model":"licensed_brokerage","business_model_note":"Digital mortgage brokerage/comparison hybrid, founded 2018, positioned around ongoing renewal-scenario optimization","provincial_licenses":["ON"],"lender_panel_note":"30+ lenders (banks, credit unions, B-lenders, private lenders); company states it operates in all provinces though only its Ontario FSRA license was independently confirmed","consumer_fee_note":"$0","trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No consolidated Trustpilot page found for the Canadian mortgage entity specifically — thinner third-party verification than larger peers on this page","regulatory_note":"Not to be confused with unrelated US \"Perch Loans\" or UK \"Perch Capital Limited\" entities, which carry unrelated complaint histories under the same brand name — this row refers specifically to the Canadian mortgage brokerage (Perch Mortgages, myperch.io)."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://myperch.io/',
  false,
  'Borrowers wanting a smaller, digital-first broker',
  6,
  'https://myperch.io/faq/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'mortgage-alliance',
  'ca',
  'housing',
  'mortgage-brokers',
  'Mortgage Alliance',
  'A large national franchise network under M3 Financial Group',
  7.2,
  0,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['2,400+ professionals', '100+ franchises since 1998', 'Part of M3 Financial Group']::text[],
  ARRAY['Large national franchise network — 2,400+ mortgage professionals across 100+ franchises since 1998', 'Part of M3 Financial Group, Canada''s largest non-bank mortgage originator ($75B+ annual volume group-wide)', 'No comparable regulatory scrutiny found, unlike a competing network (see disclosure below)']::text[],
  ARRAY['Not a single licensed brokerage — each individual broker or franchise holds their own provincial license, so service quality depends heavily on which broker you''re matched with', 'BBB lists the parent entity as Not Rated / Not Accredited, and reputation is fragmented across dozens of regional franchise listings']::text[],
  '{"trust":7.4,"coverage":8,"rating":5.4}'::jsonb,
  'A large, in-person franchise network — outcomes depend heavily on your individual broker.',
  '{"business_model":"franchise_network","business_model_note":"Large franchise-based brokerage network (part of M3 Financial Group, alongside Invis, Mortgage Intelligence and Verico); individual brokers/franchisees are independently licensed and paid by lender commission, while the parent earns franchise fees","provincial_licenses":["ON","BC","AB","QC","MB","SK","NS"],"lender_panel_note":"Network-wide lender panel breadth not specifically disclosed; individual franchise brokers typically offer a wide multi-lender panel comparable to peers","consumer_fee_note":"$0 — standard industry commission model","trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"BBB lists the parent entity as Not Rated / Not Accredited (insufficient information); reputation is fragmented across dozens of individual regional franchise listings rather than one consolidated score","regulatory_note":"A 2023 Competition Bureau investigation into anti-competitive franchise practices targeted Dominion Lending Centres (DLC), a competing network — not Mortgage Alliance or its parent M3 Financial Group. That DLC inquiry was discontinued in June 2024 with no wrongdoing found. No comparable Competition Bureau action against Mortgage Alliance or M3 Financial Group was found at any point 2023-2026."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.mortgagealliance.com/',
  false,
  'Borrowers wanting a local, in-person broker',
  7,
  'https://www.joinmortgagealliance.ca/whymortgagealliance',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
