-- Comparison Cockpit — seed CA cybersecurity-smb (market='ca').
-- Visit-only launch (AU/CA/UK rollout, Stage 2 Slice CA-3, completes CA
-- 8/8 topics): affiliate_link_id NULL, is_affiliate=false, review_slug
-- NULL, external_url = provider homepage. Idempotent (ON CONFLICT DO
-- UPDATE). Attributes validated against caCybersecuritySmbAttributesSchema.
-- Every one of the 7 vendors has a real, sourced 2024-2026 incident,
-- vulnerability or regulatory matter disclosed via security_note --
-- corrects an earlier "no material compliance red flags" assumption for
-- Bitdefender (April 2025 Romanian GDPR fine), Sophos (Firewall-line
-- nation-state exploitation, disclosed though it's a different product from
-- Intercept X) and ESET (actively-exploited CVE-2024-11859) found during
-- fresh research. 1Password's Toronto HQ (Canadian-founded since 2005) is
-- verified current.
-- Provenance: live research 2026-07-11 against official pricing pages, G2,
-- Capterra, CISA KEV, vendor security advisories.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  '1password-business-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  '1Password Business',
  'Canadian-founded, Toronto-headquartered, transparent pricing',
  9,
  0,
  0,
  0,
  13,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Canadian-founded (Toronto HQ since 2005)', 'Transparent published pricing', 'SSO integrations for growing teams']::text[],
  ARRAY['A genuinely Canadian-founded company, headquartered in Toronto, Ontario since 2005', 'One of the few vendors on this page with fully transparent, published self-serve pricing', 'SSO integrations (Okta, Entra ID, Duo) and role-based vault sharing suit growing SMB teams']::text[],
  ARRAY['Later-stage ownership is US-led venture capital (~$920M raised 2019-2022) — "Canadian-owned" would overstate this, though "Canadian-founded, Toronto-headquartered" remains accurate', 'Current G2/Capterra review score could not be independently confirmed at research time']::text[],
  '{"fees":8.6,"features":9,"ux":9.2,"support":8.6}'::jsonb,
  'The strongest combination of Canadian provenance and transparent, trustworthy pricing.',
  '{"pricing_model":"per-user/month","starting_price_note":"$8.99 USD/user/month (Business, billed annually), confirmed on the official pricing page; converts to an estimated ~C$13/user/month (no native CAD price shown).","product_category":"password_manager","key_feature_note":"SSO integrations (Okta, Entra ID, Duo), role-based vault sharing, Watchtower security-hygiene alerts and activity monitoring — a Customer Success Manager is included at 101+ seats.","ca_presence_note":"Headquartered in Toronto, Ontario since founding in 2005 — a genuine Canadian-founded company. After 14 self-funded years it raised roughly $920M across three US-led venture rounds (2019-2022, valuing it at $6.8B), so \"Canadian-founded, Toronto-headquartered\" is accurate, though \"Canadian-owned\" would overstate later-stage ownership.","review_score":null,"review_count":null,"review_source":"G2/Capterra","review_note":"A specific, current G2/Capterra star rating and review count could not be independently confirmed at research time — shown as not yet rated rather than citing a stale or unverified figure.","security_note":"No confirmed breach, lawsuit or fine was found for 2024-2026. The 2023 Okta third-party incident touched some 1Password-adjacent systems, but no customer vault data was accessed — a resolved, pre-window matter disclosed for context. In 2025, a DEF CON researcher disclosed and helped patch browser-extension vulnerabilities affecting several password managers including 1Password, and phishing campaigns have separately impersonated 1Password''s ''Watchtower'' brand — both are third-party/attacker-side issues, not 1Password platform compromises."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://1password.com/business/',
  true,
  'Teams wanting a trusted Canadian-founded vendor',
  1,
  'https://1password.com/pricing/password-manager',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'crowdstrike-ca-smb',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'CrowdStrike Falcon Go',
  'Top-tier EDR pedigree — with a well-documented 2024 outage disclosed',
  8.3,
  4.6,
  385,
  385,
  11,
  '[]'::jsonb,
  ARRAY['Purpose-built SMB entry tier', 'Top-tier EDR pedigree', '⚠ July 2024 global outage — see detail']::text[],
  ARRAY['Falcon Go is a purpose-built SMB bundle (AI-powered next-gen antivirus, USB device control, mobile protection) from a top-tier EDR vendor', 'Strong review score (G2 4.6/5, 385 reviews) for the broader Falcon platform', 'Sold via CDW Canada and Pax8 Canada, with a registered Vancouver, BC entity']::text[],
  ARRAY['The July 2024 global outage — a faulty Falcon sensor update bricked ~8.5M Windows devices worldwide — hit Canada hard: Pearson and Montreal-Trudeau airports, Porter Airlines, RBC/TD and hospitals across ON/BC/MB/NL were all disrupted', 'Falcon Go lacks true EDR; real detection/response requires upgrading to the pricier Falcon Pro or Enterprise tiers']::text[],
  '{"fees":7.6,"features":9.2,"ux":8.4,"support":8}'::jsonb,
  'Elite EDR pedigree at an SMB price point — weigh the disclosed 2024 outage, which hit Canada directly.',
  '{"pricing_model":"per-device/month or /year","starting_price_note":"Falcon Go: $7.99 USD/device/month or $59.99 USD/device/year, capped at 100 devices. No native CAD price found; converts to an estimated ~C$11/device/month.","product_category":"endpoint_protection","key_feature_note":"Falcon Go bundles AI-powered next-gen antivirus, USB device control and mobile protection with \"Express Support\" onboarding for SMBs — full EDR/response requires upgrading to the pricier Falcon Pro or Enterprise tiers.","ca_presence_note":"CrowdStrike Canada, Inc. is registered in Vancouver, BC, with a Toronto event/marketing presence; sold via CDW Canada and Pax8 Canada. No stated Canadian data-residency option found.","review_score":4.6,"review_count":385,"review_source":"G2","review_note":"Capterra shows the same 4.6-4.7/5 (55 reviews); both reflect the broader Falcon platform, not the Falcon Go SMB tier specifically.","security_note":"The July 2024 global outage — a faulty Falcon sensor update bricked approximately 8.5 million Windows devices worldwide — hit Canada hard: Toronto Pearson and Montreal-Trudeau airports were disrupted, Porter Airlines cancelled all flights, RBC and TD were affected, and hospitals across Ontario, British Columbia, Manitoba and Newfoundland & Labrador (including Toronto''s UHN and Sunnybrook) faced disruptions. A US federal judge dismissed a shareholder securities-fraud suit in January 2026; Delta Air Lines'' roughly $500M lawsuit survived a motion to dismiss and remains active. Separately, in November 2025 CrowdStrike fired an employee who leaked internal screenshots to the hacking group ''Scattered Lapsus$ Hunters''; CrowdStrike states no systems or customer data were compromised despite the group''s false claim of a full breach."}'::jsonb,
  'official',
  'high',
  false,
  NULL,
  'https://www.crowdstrike.com/en-ca/',
  false,
  'Businesses wanting top-tier EDR pedigree',
  2,
  'https://www.crowdstrike.com/en-us/pricing/falcon-go/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'bitdefender-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'Bitdefender GravityZone',
  'SMB-sized endpoint protection — with an April 2025 GDPR fine disclosed',
  7.9,
  4.6,
  208,
  208,
  3,
  '[]'::jsonb,
  ARRAY['SMB-tiered up to 30 endpoints', 'Localized CA site + contact page', '⚠ April 2025 GDPR fine — see detail']::text[],
  ARRAY['SMB-sized tiers with multi-layered ransomware prevention, network attack defense and a single-pane console', 'Localized bitdefender.com/en-ca site with a dedicated Canadian business-contact page', 'Strong Capterra score (4.6/5, 208 reviews)']::text[],
  ARRAY['Romania''s data protection authority fined Bitdefender approximately €10,000 in April 2025 for a GDPR violation after an email-security update exposed customer names and emails', 'No official self-serve price published (interactive calculator only) — the figure shown is a third-party estimate']::text[],
  '{"fees":8.2,"features":8.6,"ux":8.2,"support":7.6}'::jsonb,
  'Strong SMB endpoint protection — weigh the disclosed 2025 GDPR fine.',
  '{"pricing_model":"per-device/year","starting_price_note":"No official self-serve price published (interactive calculator only). Third-party estimate: Small Business Security ~$77.69 USD/3 devices/year ≈ C$3/device/month — unverified against an official quote, get a direct quote before committing.","product_category":"endpoint_protection","key_feature_note":"Multi-layered ransomware prevention, network attack defense, misconfiguration/risk management, anti-phishing and web filtering in a single-pane console.","ca_presence_note":"Localized bitdefender.com/en-ca site and a dedicated Canadian business-contact page; a Vancouver office address appears only in a lower-tier business directory and is unconfirmed. No explicit Canadian data-residency claim found.","review_score":4.6,"review_count":208,"review_source":"Capterra","review_note":"G2 shows a lower 4.0/5 (72 reviews) specifically for \"GravityZone XDR,\" a scope mismatch worth noting versus plain Business Security.","security_note":"Romania''s data protection authority (ANSPDCP) fined Bitdefender SRL approximately €10,000 (RON 47,772) on 30 April 2025 for GDPR Article 32 violations, after a programming error in an email-security update exposed customer names and emails to third parties. Several 2024-2025 CVEs affecting Bitdefender products exist (including a Console SSRF flaw and a Box-firmware RCE flaw), though none are listed in CISA''s Known Exploited Vulnerabilities catalog as of this research."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.bitdefender.com/en-ca/business/',
  false,
  'SMBs wanting a localized CA business contact',
  3,
  'https://www.bitdefender.com/en-us/business/smb-products/business-security',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'sophos-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'Sophos Intercept X',
  'A genuine, substantial Vancouver presence since 2003',
  7.6,
  4.6,
  820,
  820,
  0,
  '[]'::jsonb,
  ARRAY['Vancouver office since 2003 (~220 staff)', 'Deep-learning malware prevention', 'Contact for pricing']::text[],
  ARRAY['A genuine, substantial Canadian presence — a Vancouver office since 2003 (~220 staff, product R&D via its ActiveState acquisition) plus a Toronto sales office', 'Deep-learning malware detection with optional XDR add-on tiers scaled to organisational maturity', 'Strong review score (G2 4.6/5, 820 reviews) for the broader Sophos Endpoint line']::text[],
  ARRAY['Sophos''s own Firewall product line (a separate product from Intercept X) has been targeted by a multi-year nation-state exploitation campaign', 'Zero self-serve pricing — quote-only via reseller']::text[],
  '{"fees":7,"features":8.8,"ux":8,"support":8.2}'::jsonb,
  'One of the strongest Canadian office presences of the 7 — but no self-serve pricing, budget for a reseller quote.',
  '{"pricing_model":"per-user/year, reseller-quoted","starting_price_note":"No official price published (quote-only via reseller). Third-party estimates: Intercept X Advanced ~$66 USD/user/year for small deployments — unverified against an official CA quote.","product_category":"endpoint_protection","key_feature_note":"Deep-learning malware prevention plus optional XDR add-on tiers scaled to org maturity — the Advanced tier (no XDR) is the realistic SMB entry point.","ca_presence_note":"A Vancouver office since 2003 (~220 staff, product R&D, via its ActiveState acquisition) plus a Toronto sales office — a genuine, substantial Canadian presence. No confirmed Canadian data-residency option for Intercept X specifically.","review_score":4.6,"review_count":820,"review_source":"G2 (Sophos Endpoint, not Intercept X-specific)","review_note":"Capterra shows 4.5/5 (218 reviews) listed specifically as \"Intercept X Endpoint.\"","security_note":"Sophos''s own ''Pacific Rim'' research (October 2024) documented a five-year China-linked nation-state campaign actively exploiting zero-day vulnerabilities in Sophos Firewall (XG/XGS) products against critical infrastructure; the US DOJ separately charged a Chinese national in 2024 over a 2020 campaign that compromised roughly 81,000 Sophos firewalls globally. Multiple critical Firewall RCE CVEs were patched through 2024-2025. This exploitation history is specific to Sophos''s network Firewall product line, not Intercept X (the endpoint product featured on this page) — but we disclose it in full given it''s the same vendor."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.sophos.com/en-us/products/endpoint-antivirus',
  false,
  'Businesses wanting a strong local CA office presence',
  4,
  'https://secure2.sophos.com/en-us/products/intercept-x/get-pricing.aspx',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'eset-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'ESET PROTECT',
  'A Montreal R&D facility since 2009 — with an actively-exploited CVE disclosed',
  7.2,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Montreal R&D facility since 2009', 'Runs well on legacy hardware', '⚠ Actively-exploited 2024 CVE — see detail']::text[],
  ARRAY['A genuine Canadian R&D presence — a Montreal threat-intelligence/R&D facility since 2009, plus a Thornhill, Ontario sales office since 2015', 'Cloud-managed PROTECT console with a flexible Entry/Advanced/Complete/MDR upgrade path', 'Runs lightly on older hardware, a real advantage for cost-conscious SMBs']::text[],
  ARRAY['CVE-2024-11859, a flaw in ESET''s own scanner, was actively exploited by the ToddyCat APT group into 2025 — a genuine product-security concern for a security vendor', 'Zero public list pricing anywhere — quote-only, and current review scores could not be independently confirmed']::text[],
  '{"fees":7,"features":8.4,"ux":7.6,"support":8}'::jsonb,
  'A real Canadian R&D presence and a flexible upgrade path — but a real exploited CVE to weigh, and no public pricing.',
  '{"pricing_model":"per-device, custom quote","starting_price_note":"No public list price found anywhere — ESET states pricing is quote-only and tailored to years and devices purchased.","product_category":"endpoint_protection","key_feature_note":"Tiered PROTECT platform (Entry/Advanced/Complete/MDR) lets SMBs start with basic endpoint AV and add EDR/MDR later without switching vendors; runs lightly on older hardware.","ca_presence_note":"A Montreal threat-intelligence/R&D facility since 2009 and a Thornhill, Ontario sales office since 2015. Marketing references a Montreal-linked \"local data centre,\" though the exact scope of Canadian data residency for PROTECT''s cloud services is unconfirmed.","review_score":null,"review_count":null,"review_source":"G2/Capterra","review_note":"PROTECT MDR (4.8/5, 16 reviews) and PROTECT Complete (4.7/5, 10 reviews) samples are both too small to be meaningful — shown as not yet rated rather than citing an unreliable figure.","security_note":"CVE-2024-11859, a DLL search-order hijacking flaw (CVSS 8.4) in ESET''s own Windows products, was actively exploited in the wild by the China-linked APT group ToddyCat to deploy malware and disable kernel security notifications, patched in January 2025. Separately, ESET''s own researchers discovered and disclosed CVE-2024-7344, an industry-wide UEFI Secure Boot bypass, fixed via the January 2025 Patch Tuesday."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.eset.com/ca/business/',
  false,
  'Budget-conscious businesses on older hardware',
  5,
  'https://www.eset.com/ca/business/contact-sales/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'malwarebytes-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'Malwarebytes',
  'The simplest deployment of the 7 — with the cleanest disclosed record',
  7,
  4.6,
  1120,
  1120,
  14,
  '[{"type":"green","label":"Cleanest disclosed record"}]'::jsonb,
  ARRAY['Simple 3/10/20-device Teams tiers', 'Built-in Privacy VPN + Browser Guard', 'No confirmed Canadian office']::text[],
  ARRAY['The simplest deployment of the 7 — straightforward 3/10/20-device Teams tiers with 24/7 support', 'Built-in Privacy VPN, Browser Guard and Brute Force Protection bundled at every tier', 'The cleanest disclosed security record of the 7 — only a resolved 2021 incident and a local-access-only CVE found']::text[],
  ARRAY['No confirmed Canadian office, distributor or data-residency claim — the only Canada-linked asset found is a consumer VPN exit node in Toronto', 'Weaker advanced reporting/remote-management than competitors, per reviewer feedback']::text[],
  '{"fees":8.4,"features":7.4,"ux":8.4,"support":7.6}'::jsonb,
  'The simplest, cleanest-disclosed option — with the weakest Canadian presence of the 7.',
  '{"pricing_model":"per-device/year","starting_price_note":"Sole Proprietor (3 devices): $119.99 USD/year (~C$14/month estimated). Small Office (20 devices): $519.99 USD/year. No native CAD price found.","product_category":"endpoint_protection","key_feature_note":"Simple 3/10/20-device Teams tiers with 24/7 support, a built-in Privacy VPN, Browser Guard and Brute Force Protection, plus monthly reporting across platforms.","ca_presence_note":"No confirmed Canadian office, distributor or data-residency claim found — company locations are Cork, Ireland and Santa Clara, California only. The sole Canada-linked asset found is a consumer VPN exit node in Toronto, not a business/compliance feature.","review_score":4.6,"review_count":1120,"review_source":"G2","review_note":"This figure is blended across all Malwarebytes products, not isolated to the Teams/Business SKU specifically.","security_note":"A 2021 nation-state email-access incident (attributed to the same actor group behind the SolarWinds breach) is historical and resolved — no customer data was compromised, and no follow-up developments were found for 2024-2026. A local-privilege-escalation CVE exists (a quarantine symlink-abuse flaw, CVSS 7.8, patched November 2024) but requires local device access, and no in-the-wild exploitation was found."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.malwarebytes.com/business',
  false,
  'Small teams wanting the simplest deployment',
  6,
  'https://www.malwarebytes.com/pricing/teams',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'nordlayer-ca',
  'ca',
  'cybersecurity',
  'cybersecurity-smb',
  'NordLayer (NordVPN Business)',
  'Server nodes in Vancouver, Montreal and Toronto — with a January 2026 breach claim disclosed',
  6.6,
  4.6,
  33,
  33,
  15,
  '[]'::jsonb,
  ARRAY['CA server nodes: Vancouver, Montreal, Toronto', 'ThreatBlock + Cloud Firewall', '⚠ Jan 2026 breach claim — see detail']::text[],
  ARRAY['NordLayer gateway server nodes exist in Vancouver, Montreal and Toronto', 'ThreatBlock malicious-site filtering, IP allowlisting, DNS filtering and a Cloud Firewall for distributed teams']::text[],
  ARRAY['No confirmed dedicated Canadian office or NordLayer-specific data-residency guarantee', 'A threat actor claimed a January 2026 breach of Salesforce/Jira-adjacent infrastructure; NordVPN disputes any production impact, calling the leaked data "dummy data" from an old third-party test environment']::text[],
  '{"fees":7.6,"features":7.6,"ux":7.8,"support":7.2}'::jsonb,
  'A capable business VPN with real Canadian server presence — read the disclosed breach claim below before choosing.',
  '{"pricing_model":"per-user/month","starting_price_note":"Lite: $8 USD/user/month. Core: $11 USD/user/month (~C$15/month estimated). Premium: $14 USD/user/month. Minimum 5 users on Lite/Core/Premium; Enterprise from $6 USD/user/month at 200+ seats, custom. No native CAD price.","product_category":"vpn_network_security","key_feature_note":"ThreatBlock malicious-site filtering, IP allowlisting, DNS filtering (Core+), Cloud Firewall and site-to-site VPN (Premium+), up to 1Gbps throughput.","ca_presence_note":"NordLayer gateway server nodes exist in Vancouver, Montreal and Toronto. No confirmed dedicated Canadian office or NordLayer-specific data-residency guarantee.","review_score":4.6,"review_count":33,"review_source":"Capterra","review_note":"Reviews.io separately shows 4.7/5 (152 reviews, 93% recommend). Do not cite consumer NordVPN''s Trustpilot score as NordLayer''s — different product and audience.","security_note":"A threat actor calling itself \"1011\" claimed a January 2026 breach of Salesforce/Jira-adjacent development infrastructure. NordVPN''s response within 24 hours: the exposed data came from an isolated third-party test environment and was \"dummy data,\" with no production or customer data affected. No independent forensic verification of either side''s account has surfaced as of this page''s last check, and no Canada-specific dimension to this incident was found."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://nordlayer.com/',
  false,
  'Distributed CA teams needing network access',
  7,
  'https://nordlayer.com/pricing/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
