-- GENERATED by scripts/research/build-trading-research-sources.mjs — DO NOT EDIT BY HAND.
-- Seeds product_attributes.research_sources (per-Tier-1-fact provenance) +
-- methodology_version + a matrix-derived research_status intent, for
-- us/trading/trading-platforms, from the audited source-matrix
--   docs/superpowers/plans/2026-07-03-cockpit-trading-platforms-source-matrix.md
--
-- research_status is an editorial INTENT (audited iff all 4 required Tier-1
-- keys [optionsFee, minDeposit, extendedHours, tradingview] are sourced with confidence != low). It is
-- SUBORDINATE to runtime degradation (lib/research/deriveResearchScore): a row
-- also needs confidence_reason + confidence to actually render as audited.
-- Low/open cells are intentionally NOT seeded (source-matrix §7/§133) — e.g.
-- eToro.extendedHours (confidence low, "offen — nicht verifiziert").
--
-- APPLICATION: manual, ONLY via this versioned file (no service-key DML path).
-- NOT auto-applied (deploy.yml runs no migrations). As of this commit: UNAPPLIED.
-- Regenerate with: node scripts/research/build-trading-research-sources.mjs

BEGIN;

-- fidelity: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://www.fidelity.com/trading/commissions-margin-rates","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.fidelity.com/trading/commissions-margin-rates","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.fidelity.com/trading/faqs-placing-orders","sourceType":"official","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.tradingview.com/brokers/","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'fidelity' AND market = 'us' AND topic = 'trading-platforms';

-- charles-schwab: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://disclosures.schwab.com/SchwabDashboard/61330/REG23060.pdf","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.schwab.com/pricing","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.stockbrokers.com/guides/24-hour-trading","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.tradingview.com/brokers/","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'charles-schwab' AND market = 'us' AND topic = 'trading-platforms';

-- interactive-brokers: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://www.interactivebrokers.com/en/pricing/commissions-options.php","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.interactivebrokers.com/en/general/compare-lite-pro.php","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.stockbrokers.com/guides/24-hour-trading","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.interactivebrokers.com/en/trading/tradingview-landing.php","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'interactive-brokers' AND market = 'us' AND topic = 'trading-platforms';

-- robinhood: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://robinhood.com/us/en/support/articles/trading-fees-on-robinhood/","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://robinhood.com/us/en/support/articles/trading-fees-on-robinhood/","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.stockbrokers.com/guides/24-hour-trading","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://brokerchooser.com/broker-reviews/robinhood-review/robinhood-tradingview","sourceType":"editorial","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'robinhood' AND market = 'us' AND topic = 'trading-platforms';

-- etoro: provisional (3/4 Tier-1 facts sourced; dropped low/open: extendedHours)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://www.etoro.com/en-us/trading/fees/","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.bestbrokers.com/reviews/etoro/account-opening/","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.forexbrokers.com/guides/tradingview-brokers","sourceType":"editorial","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'provisional'
WHERE slug = 'etoro' AND market = 'us' AND topic = 'trading-platforms';

-- webull: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://www.webull.com/pricing","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.webull.com/partners/tradingview","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.stockbrokers.com/guides/24-hour-trading","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.webull.com/partners/tradingview","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'webull' AND market = 'us' AND topic = 'trading-platforms';

-- etrade: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://us.etrade.com/what-we-offer/pricing-and-rates","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://us.etrade.com/what-we-offer/pricing-and-rates","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://us.etrade.com/l/f/disclosure-library/extended-hours-trading","sourceType":"official","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.tradingview.com/brokers/","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'etrade' AND market = 'us' AND topic = 'trading-platforms';

-- tastytrade: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://tastytrade.com/pricing/","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.bankrate.com/investing/brokerage-reviews/tastytrade/","sourceType":"editorial","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://support.tastytrade.com/support/s/solutions/articles/43000435382","sourceType":"official","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.forexbrokers.com/guides/tradingview-brokers","sourceType":"editorial","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'tastytrade' AND market = 'us' AND topic = 'trading-platforms';

-- merrill-edge: audited (4/4 Tier-1 facts sourced)
UPDATE public.product_attributes
SET research_sources    = '{"optionsFee":{"sourceUrl":"https://www.merrilledge.com/pricing","sourceType":"official","verifiedAt":"2026-07-03"},"minDeposit":{"sourceUrl":"https://www.merrilledge.com/pricing","sourceType":"official","verifiedAt":"2026-07-03"},"extendedHours":{"sourceUrl":"https://www.brokerage-review.com/investing-firm/extended-hours/merrill-edge-extended-hours-trading.aspx","sourceType":"editorial","verifiedAt":"2026-07-03"},"tradingview":{"sourceUrl":"https://www.tradingview.com/brokers/","sourceType":"official","verifiedAt":"2026-07-03"}}'::jsonb,
    methodology_version = 'trading-platforms-v1',
    research_status     = 'audited'
WHERE slug = 'merrill-edge' AND market = 'us' AND topic = 'trading-platforms';

COMMIT;

-- ── ROLLBACK (run manually) ──
-- BEGIN;
-- UPDATE public.product_attributes
-- SET research_sources = NULL, methodology_version = NULL, research_status = NULL
-- WHERE market = 'us' AND topic = 'trading-platforms'
--   AND slug IN ('fidelity', 'charles-schwab', 'interactive-brokers', 'robinhood', 'etoro', 'webull', 'etrade', 'tastytrade', 'merrill-edge');
-- COMMIT;
