-- Comparison Cockpit — seed CA forex-brokers (market='ca').
-- Visit-only launch (AU/CA/UK rollout, Stage 2 Slice CA-2): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- caForexBrokersAttributesSchema. Friedberg Direct and AvaTrade Canada share
-- the same CIRO dealer member (Friedberg Mercantile Group Ltd.) — disclosed
-- explicitly on both rows, not presented as two independently-regulated
-- firms. Several 2024-2026 NFA/FINRA/CFTC enforcement actions target the US
-- entities of these global brokers, not the CIRO-regulated CA entity —
-- disclosed with that scope caveat. Questrade's April 2025 Quebec class
-- action (currency-conversion fee non-disclosure) is a live CA-specific
-- matter, disclosed as such.
-- Provenance: live research 2026-07-11 against official pricing pages, CIRO,
-- CIPF, NFA BASIC.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'interactive-brokers-ca',
  'ca',
  'forex',
  'forex-brokers',
  'Interactive Brokers Canada',
  'The tightest pass-through pricing for active traders',
  9,
  3.5,
  5200,
  5200,
  0.003,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['Pass-through ECN pricing', '17+ liquidity providers', 'TWS, Client Portal, mobile']::text[],
  ARRAY['Aggregates 17+ liquidity providers for pass-through/ECN-style pricing with no markup on spread', 'Lowest all-in cost of any candidate researched for active traders', 'Direct CIRO and CIPF member with a long institutional track record']::text[],
  ARRAY['Trustpilot score (3.5/5, ~5,200 reviews) is a global brand page, not Canada-specific', 'Platform (TWS) has a steeper learning curve than simpler retail-focused competitors']::text[],
  '{"cost":9.8,"platforms":8.6,"trust":9,"support":7.6}'::jsonb,
  'The lowest all-in trading cost in this comparison, built for active traders.',
  '{"ciro_member":"Interactive Brokers Canada Inc.","avg_spread_eurusd_pips":0.1,"commission_round_turn_cad":2,"account_type_note":"Pass-through/ECN pricing aggregating 17+ liquidity providers; tiered commission ~0.08-0.20bps of trade value","max_leverage":"50:1","platforms":["TWS","IBKR Desktop","Client Portal","IBKR Mobile"],"trustpilot_rating":3.5,"trustpilot_count":5200,"trustpilot_note":"Global brand-level Trustpilot page, not Canada-entity-specific","regulatory_note":"FINRA fined Interactive Brokers LLC (the U.S. broker-dealer entity) $2.25M in December 2024 for failing to detect/prevent \"free-riding\" in cash accounts (2015-2022), a further $650,000 in August 2025 for options-approval supervisory failures, and $125,000 in September 2025 for municipal-bond disclosure lapses. These are U.S.-entity FINRA actions — no CIRO enforcement action against Interactive Brokers Canada Inc. specifically was found at research time."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.interactivebrokers.ca/en/trading/products-spot-currencies.php',
  true,
  'Active traders wanting the lowest all-in cost',
  1,
  'https://www.interactivebrokers.ca/en/pricing/commissions-spot-currencies.php',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'cmc-markets-ca',
  'ca',
  'forex',
  'forex-brokers',
  'CMC Markets Canada',
  '330+ FX pairs with no minimum deposit and no issues found',
  8.7,
  4,
  3230,
  3230,
  0.0065,
  0,
  '[{"type":"green","label":"Best overall"}]'::jsonb,
  ARRAY['330+ FX pairs', 'Funds at Canadian chartered banks', 'No minimum deposit']::text[],
  ARRAY['A direct CIRO dealer member (CMC Markets Canada Inc.) with funds segregated at a Canadian chartered bank', '330 FX pairs — the widest instrument range of any candidate researched', 'No minimum deposit and no Canada-specific regulatory issues found']::text[],
  ARRAY['Trustpilot score (4.0/5, ~3,230 reviews) is a global brand page, not Canada-specific', 'Alberta CFD access is restricted to Accredited Investors only']::text[],
  '{"cost":8.4,"platforms":8.2,"trust":9.4,"support":8.4}'::jsonb,
  'The best all-round choice — widest pair range, no minimum deposit, clean record.',
  '{"ciro_member":"CMC Markets Canada Inc.","avg_spread_eurusd_pips":0.3,"commission_round_turn_cad":3.5,"account_type_note":"FX Active account, spreads from 0.0 pip plus commission; standard account is commission-free with wider spreads","max_leverage":"50:1","platforms":["Next Generation","MT4"],"trustpilot_rating":4,"trustpilot_count":3230,"trustpilot_note":"Global brand-level Trustpilot page, not Canada-entity-specific","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.cmcmarkets.com/en-ca/',
  false,
  'Traders wanting the widest pair range',
  2,
  'https://www.cmcmarkets.com/en-ca/pricing',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'oanda-ca',
  'ca',
  'forex',
  'forex-brokers',
  'OANDA Canada',
  'Native CAD accounts with a genuine Toronto office',
  8.4,
  3.9,
  1200,
  1200,
  0.0095,
  0,
  '[{"type":"sky","label":"Best for beginners"}]'::jsonb,
  ARRAY['Native CAD accounts', 'Toronto head office', 'No minimum deposit']::text[],
  ARRAY['A direct CIRO dealer member (OANDA (Canada) Corporation ULC) with a genuine Toronto head office', 'Native CAD account support and simple, transparent spread-only pricing', 'No minimum deposit, with micro-lots available from 1 unit']::text[],
  ARRAY['Standard-account spreads are wider than a raw/ECN tier — active traders may prefer a commission-based competitor', 'Trustpilot figures vary by regional page (3.7-4.1/5, ~1,150-1,220 reviews) — not perfectly comparable across entities']::text[],
  '{"cost":7.4,"platforms":8,"trust":8.4,"support":8.2}'::jsonb,
  'The most "Canadian" broker experience — native CAD accounts and local presence.',
  '{"ciro_member":"OANDA (Canada) Corporation ULC","avg_spread_eurusd_pips":0.95,"commission_round_turn_cad":0,"account_type_note":"Standard account, spread-only, no commission; Core Pricing (raw spread + commission) requires a much larger balance","max_leverage":"50:1","platforms":["OANDA Trade","MT4","TradingView"],"trustpilot_rating":3.9,"trustpilot_count":1200,"trustpilot_note":"OANDA maintains multiple regional Trustpilot pages — figures are not perfectly comparable across entities","regulatory_note":"The U.S. NFA fined OANDA Corporation (OANDA''s U.S. entity) $600,000 in May 2025 for capital-adequacy deficiencies persisting 7+ months in 2023, a pricing/API error that harmed roughly 3,900 customers (with restitution agreed), and inadequate disclosure of a crypto-broker relationship. This action targets OANDA''s U.S. entity — no confirmed CIRO enforcement action against OANDA (Canada) Corporation ULC specifically was found at research time."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.oanda.com/ca-en/',
  false,
  'Beginners wanting native CAD accounts',
  3,
  'https://www.oanda.com/ca-en/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'questrade-global',
  'ca',
  'forex',
  'forex-brokers',
  'Questrade (Questrade Global)',
  'Canada''s largest independent broker''s FX arm',
  8,
  1.35,
  350,
  350,
  0.008,
  1000,
  '[]'::jsonb,
  ARRAY['110+ currency pairs', 'Saxo-powered platform', 'Largest independent CA broker']::text[],
  ARRAY['Canada''s largest independent broker (~$50B+ AUA), with an FX/CFD arm covering 110+ pairs', 'Saxo Bank-powered Questrade Global platform offers institutional-grade execution', 'Direct CIRO dealer member with supplemental private insurance beyond standard CIPF coverage']::text[],
  ARRAY['Recent Trustpilot score is poor (1.3-1.4/5, ~300-400 reviews) — a sharp divergence from older, more positive aggregator citations', '$0 to open, but a $1,000 CAD balance is required before trading is enabled']::text[],
  '{"cost":8.2,"platforms":8.6,"trust":5.6,"support":6}'::jsonb,
  'Canada''s largest independent broker''s FX arm, with real recent service complaints to weigh.',
  '{"ciro_member":"Questrade Inc.","avg_spread_eurusd_pips":0.8,"commission_round_turn_cad":0,"account_type_note":"Questrade Global (Saxo Bank-powered), spread-inclusive pricing, 110+ pairs","max_leverage":"50:1","platforms":["Questrade Global","Questrade Edge","IQ Edge"],"trustpilot_rating":1.35,"trustpilot_count":350,"trustpilot_note":"ca.trustpilot.com — recent snapshots show 1.3-1.4/5 (~300-400 reviews); older aggregator citations claim 4.2/5 (2,000+ reviews) — the low recent score is treated as the more reliable current read","regulatory_note":"Questrade was named, alongside five other Canadian financial institutions, in an April 2025 Quebec class action alleging non-disclosure of currency-conversion fees on self-directed accounts — an active, unresolved matter as of this page''s last verification."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.questrade.com/',
  false,
  'Existing Questrade customers wanting one platform',
  4,
  'https://www.questrade.com/pricing',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'forex-com-ca',
  'ca',
  'forex',
  'forex-brokers',
  'FOREX.com Canada',
  'Part of the NASDAQ-listed StoneX Group',
  7.6,
  4.3,
  2350,
  2350,
  0.012,
  0,
  '[]'::jsonb,
  ARRAY['Backed by NASDAQ-listed StoneX', 'Standard & RAW account tiers', 'Trading Central integration']::text[],
  ARRAY['Backed by StoneX Group Inc. (NASDAQ-listed parent), a large, well-capitalized institution', 'Choice of spread-only Standard account or commission-based RAW account for high-volume traders', 'Proprietary platform bundles Trading Central research alongside MT4/MT5']::text[],
  ARRAY['Minimum deposit for the Canadian entity specifically was not firmly confirmed — verify directly before opening', 'Trustpilot score (4.0-4.6/5, ~2,300-2,400 reviews) is a global/US brand page, not Canada-isolated']::text[],
  '{"cost":7,"platforms":8.4,"trust":8.2,"support":7.8}'::jsonb,
  'A well-capitalized global broker with a straightforward Standard account tier.',
  '{"ciro_member":"FOREX.com Canada (StoneX Group Inc.)","avg_spread_eurusd_pips":1.2,"commission_round_turn_cad":0,"account_type_note":"Standard account, spread-only, no commission; RAW account offers tighter spreads plus a per-lot commission for high-volume traders","max_leverage":"50:1","platforms":["FOREX.com Web/Mobile","MT4","MT5"],"trustpilot_rating":4.3,"trustpilot_count":2350,"trustpilot_note":"Global/US brand-level Trustpilot page, not Canada-entity-specific","regulatory_note":"The U.S. NFA fined StoneX Markets LLC (FOREX.com''s U.S. parent entity) $1,000,000 in January 2023 for margin-rule violations, and the CFTC separately fined StoneX Markets $650,000 for a disclosure breach. These target StoneX''s U.S. entity — no confirmed CIRO enforcement action against FOREX.com Canada specifically was found at research time."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.forex.com/en-ca/',
  false,
  'Traders wanting a large, well-capitalized parent',
  5,
  'https://www.forex.com/en-ca/pricing/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'avatrade-ca',
  'ca',
  'forex',
  'forex-brokers',
  'AvaTrade Canada',
  'A globally recognized brand, regulated in Canada via Friedberg',
  7.2,
  4.75,
  12000,
  12000,
  0.009,
  0,
  '[]'::jsonb,
  ARRAY['MT4, MT5, AvaOptions', 'Copy trading (ZuluTrade, DupliTrade)', 'Regulated via Friedberg Direct']::text[],
  ARRAY['High global brand recognition (4.7-4.8/5 on Trustpilot globally, 11,000+ reviews)', 'Broad platform choice including MT4, MT5, WebTrader and AvaOptions, plus copy-trading integrations', 'Canadian accounts are held under Friedberg Mercantile Group Ltd.''s CIRO membership, giving genuine CIPF coverage']::text[],
  ARRAY['Not independently CIRO-registered — operates in Canada solely via a technology/branding license with Friedberg Direct', 'Trustpilot figures are brand-level (global/UK pages), not Canada-entity-specific']::text[],
  '{"cost":7.8,"platforms":9,"trust":6.6,"support":7.4}'::jsonb,
  'A globally recognized platform — understand the Friedberg regulatory relationship first.',
  '{"ciro_member":"Friedberg Mercantile Group Ltd. (via AvaTrade Technology license)","avg_spread_eurusd_pips":0.9,"commission_round_turn_cad":0,"account_type_note":"Standard no-commission model, 50+ FX pairs","max_leverage":"50:1","platforms":["MT4","MT5","WebTrader","AvaOptions"],"trustpilot_rating":4.75,"trustpilot_count":12000,"trustpilot_note":"avatrade.com global page shows 4.7-4.8/5 (11,000-12,800+ reviews); avatrade.co.uk shows ~4.0/5 (2,700 reviews) — neither is Canada/Friedberg-specific","regulatory_note":"AvaTrade Canada is not independently CIRO-registered. Canadian accounts are opened and held by Friedberg Mercantile Group Ltd. (trading as Friedberg Direct), which licenses AvaTrade''s trading technology and branding for the Canadian market — see Friedberg Direct''s own row for the shared-entity relationship. Historically, AvaTrade paid a $244,000 fine in 2020 to settle allegations of operating as an unregistered entity in a Canadian province before this Friedberg-licensing structure was formalized — dated, and disclosed as context for why the current structure exists, not a current compliance issue."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.avatrade.ca/',
  false,
  'Traders wanting AvaTrade''s global platform in Canada',
  6,
  'https://www.avatrade.ca/about-friedberg/why-friedberg/regulation',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'friedberg-direct',
  'ca',
  'forex',
  'forex-brokers',
  'Friedberg Direct',
  'One of Canada''s oldest independent brokers, since 1971',
  7,
  0,
  0,
  0,
  0.011,
  0,
  '[]'::jsonb,
  ARRAY['Independent since 1971', 'Direct CIRO + CIPF member', 'MT4, MT5, WebTrader']::text[],
  ARRAY['One of the oldest independent Canadian brokers still operating (since 1971)', 'Direct CIRO dealer member and CIPF member in its own right — the same regulated entity that also holds AvaTrade Canada', 'Standard MetaTrader platform choice (MT4, MT5) plus its own WebTrader']::text[],
  ARRAY['No independent, reliable review-platform sample found specifically for the Friedberg Direct brand', 'Some Friedberg-branded pages reference a co-branding relationship with FXCM rather than AvaTrade — confirm which technology partner is current before opening an account']::text[],
  '{"cost":7.2,"platforms":7.6,"trust":8.2,"support":7}'::jsonb,
  'One of Canada''s longest-operating independent brokers, directly CIRO-regulated.',
  '{"ciro_member":"Friedberg Mercantile Group Ltd. (Friedberg Direct)","avg_spread_eurusd_pips":1.1,"commission_round_turn_cad":0,"account_type_note":"Standard no-commission model","max_leverage":"50:1","platforms":["MT4","MT5","Friedberg WebTrader"],"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No distinct, reliable Trustpilot page found for Friedberg Direct specifically — shown as not yet rated","regulatory_note":"Friedberg Mercantile Group Ltd. is the CIRO dealer member of record for both the Friedberg Direct and AvaTrade Canada brands (see AvaTrade Canada''s row for the shared-entity relationship). Some Friedberg-branded marketing pages reference \"powered by FXCM\" rather than AvaTrade, suggesting the current primary technology partner should be confirmed directly with Friedberg before opening an account. No independent CIRO enforcement action against Friedberg was found at research time."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.friedbergdirect.com/',
  false,
  'Traders wanting the longest-operating CA broker',
  7,
  'https://www.friedbergdirect.com/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
