-- Comparison Cockpit — seed CA gold-investing/platforms (market='ca').
-- Visit-only launch (AU/CA/UK rollout, Stage 2 Slice CA-2): affiliate_link_id
-- NULL, is_affiliate=false, review_slug NULL, external_url = provider
-- homepage. Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- caGoldInvestingAttributesSchema. product_type distinguishes direct bullion
-- dealers from BMG (an OSC-regulated fund wrapper) and the Royal Canadian
-- Mint's Gold ETR (a TSX-listed security) — see file header in
-- lib/comparison/topics/ca/gold-investing.ts. GoldMoney's 2024 BVI corporate
-- continuance is disclosed as a legitimate, shareholder-voted move (NOT a
-- fraud/shell red flag), alongside its real 2024-2025 account-freeze
-- complaints. Canadian Bullion Services carries active 2025-2026
-- non-delivery complaints — kept per the approved shortlist, ranked last,
-- disclosed in full.
-- Provenance: live research 2026-07-11 against official pricing pages,
-- BBB, Trustpilot, LBMA, FINTRAC.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee, account_minimum,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'silver-gold-bull-ca',
  'ca',
  'gold-investing',
  'platforms',
  'Silver Gold Bull',
  'The cleanest track record of any dealer researched',
  9,
  4.6,
  4700,
  4700,
  0,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['BBB A+, zero complaints in 3 years', 'LBMA Affiliate Member', 'RRSP/TFSA-eligible']::text[],
  ARRAY['BBB A+ accredited since 2012 with zero unresolved complaints', 'LBMA Affiliate Member — independently confirmed via LBMA''s own Alchemist magazine profile', 'Direct RRSP/TFSA-eligible gold products, operating since 2009']::text[],
  ARRAY['Exact current storage fee schedule was not independently confirmable at research time', 'Occasional shipping delays reported at high order volume']::text[],
  '{"trust":9.6,"cost":8.2,"rating":9.2}'::jsonb,
  'The cleanest complaint record and strongest independent accreditation in this comparison.',
  '{"product_type":"direct_bullion","premium_over_spot_pct":3.5,"premium_note":"Approximate — based on a CAD $50-150/oz premium range on coins cited on official pricing pages, converted using an estimated ~CAD $2,850/oz gold spot reference; bars carry a lower premium (CAD $30-80/oz). Get a live, dated quote before buying.","storage_note":"Fully insured, allocated vault storage available; exact fee schedule not independently confirmed at research time — request current fees directly.","buyback_available":true,"registered_account_note":"RRSP/TFSA-eligible gold products offered directly.","accreditation":"lbma_affiliate","accreditation_note":"LBMA Affiliate Member, confirmed via LBMA''s own Alchemist magazine profile.","years_in_business":17,"trustpilot_rating":4.6,"trustpilot_count":4700,"trustpilot_note":"Reported ratings ranged 4.5-4.9/5 across sources; BBB A+ accredited with zero unresolved complaints in the last 3 years.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.silvergoldbull.ca/',
  true,
  'Investors wanting the cleanest overall track record',
  1,
  'https://www.silvergoldbull.ca/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'bmg-bullionfund',
  'ca',
  'gold-investing',
  'platforms',
  'BMG (Bullion Management Group)',
  'The only Canadian gold product built for registered accounts',
  8.6,
  0,
  0,
  0,
  1.25,
  1000,
  '[{"type":"sky","label":"Best for RRSP/TFSA"}]'::jsonb,
  ARRAY['OSC-regulated mutual fund', 'RRSP/RRIF/TFSA/RESP/RDSP eligible', 'LBMA Good Delivery bars (per fund materials)']::text[],
  ARRAY['The only Canadian gold product structured as an OSC-regulated mutual fund holding allocated bullion', 'Purpose-built for every major registered account type: RRSP, RRIF, TFSA, RESP and RDSP', 'Regulated like any other Canadian mutual fund — clearer oversight than an unregulated bullion dealer']::text[],
  ARRAY['Management fees (1.25%-2.74% depending on unit class) are materially higher than a one-time dealer premium over a long holding period', 'No Trustpilot/BBB consumer-review data exists for a fund-structured product']::text[],
  '{"trust":9,"cost":6.4,"rating":0}'::jsonb,
  'The clearest, most regulated route to RRSP/TFSA gold exposure — at an ongoing fee.',
  '{"product_type":"fund_wrapper","premium_over_spot_pct":null,"premium_note":"Not applicable — priced at fund NAV, not a per-oz premium. Management fee: Class D 1.25% total, Class A MER 2.74% (varies by unit class).","storage_note":"Professional vault custody via the fund; specific custodian not disclosed in the fund materials reviewed.","buyback_available":true,"registered_account_note":"Purpose-built for registered accounts — RRSP, RRIF, TFSA, RESP and RDSP all eligible.","accreditation":"osc_regulated_fund","accreditation_note":"OSC-regulated mutual fund; fund materials state holdings are LBMA Good Delivery bars (not independently re-verified beyond the fund''s own disclosures).","years_in_business":null,"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No Trustpilot/BBB data found for this fund-structured product — mutual funds are not typically reviewed on consumer platforms.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://bmgfunds.com/',
  false,
  'RRSP/TFSA investors wanting fund-wrapped bullion',
  2,
  'https://bmgfunds.com/bmg-mutual-fund-frequently-asked-questions/canadian-investor-faqs/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'rcm-gold-etr',
  'ca',
  'gold-investing',
  'platforms',
  'Royal Canadian Mint Gold ETR',
  'A direct obligation of the Government of Canada',
  8.4,
  0,
  0,
  0,
  0.35,
  66,
  '[{"type":"sky","label":"Most trust-anchored"}]'::jsonb,
  ARRAY['TSX-listed (MNT / MNT.U)', 'Direct claim on Mint-vaulted gold', '0.35% p.a. service fee']::text[],
  ARRAY['The strongest sovereign-trust signal of any option researched — a direct obligation of the Government of Canada', 'Trades on the TSX like any other security, through any brokerage — no dealer relationship needed', 'A single flat 0.35% p.a. service fee, with no separate storage fee']::text[],
  ARRAY['Physical bullion redemption requires a minimum of 10,000 ETRs (~CAD $664,000) — effectively inaccessible for retail-sized physical delivery', 'Purity figures showed a minor discrepancy across sources (99.9% vs. 99.99%) — confirm against the Mint''s own information statement']::text[],
  '{"trust":10,"cost":8.6,"rating":0}'::jsonb,
  'The most trust-anchored option in this comparison — a listed security, not a dealer relationship.',
  '{"product_type":"etr_security","premium_over_spot_pct":null,"premium_note":"Not applicable — a TSX-listed security (symbols MNT in CAD, MNT.U in USD) representing a direct legal and beneficial interest in Mint-vaulted gold. 0.35% p.a. service fee; no separate premium or storage fee.","storage_note":"Held at the Royal Canadian Mint''s Ottawa vault; storage cost is built into the 0.35% p.a. service fee.","buyback_available":true,"registered_account_note":"RRSP/TFSA-eligible through any self-directed brokerage, since it trades as a normal listed security.","accreditation":"government_mint","accreditation_note":"A direct obligation of the Government of Canada, issued and vaulted by the Royal Canadian Mint — the strongest sovereign-trust signal of any option on this page.","years_in_business":null,"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"Not applicable — a listed security, not a dealer; no consumer review platform coverage.","regulatory_note":"Physical bullion redemption requires a minimum of 10,000 ETRs (~CAD $664,000) — effectively inaccessible for retail-sized physical delivery, though the security itself is fully liquid on the TSX. Purity is stated as high-purity, though sources showed a minor 99.9%/99.99% discrepancy — confirm against the Mint''s own information statement before relying on a specific figure."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.reserves.mint.ca/tsx_gold',
  false,
  'Investors wanting the strongest sovereign backing',
  3,
  'https://www.reserves.mint.ca/media/1521/gold-etr-information-statement.pdf',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'sprott-money',
  'ca',
  'gold-investing',
  'platforms',
  'Sprott Money',
  'A well-established Toronto dealer with a BBB A+ rating',
  8,
  3.7,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['BBB A+ since 2011, 0 complaints (3 yrs)', 'ShopperApproved 4.8/5 (2,600+)', 'RRSP/TFSA via Questrade']::text[],
  ARRAY['BBB A+ accredited since 2011 with 0 complaints in the last 3 years', 'Strong ShopperApproved score (4.8/5, 2,600+ verified reviews) alongside a smaller, mixed Trustpilot sample', 'Part of the broader, well-known Sprott brand, operating since 2008']::text[],
  ARRAY['RRSP/TFSA purchases require opening a separate Questrade account first as third-party custodian — a real extra step', 'No flat published premium rate — pricing requires a live quote, and storage fees scale up to ~1.5%/yr on smaller holdings']::text[],
  '{"trust":8.6,"cost":7,"rating":7.4}'::jsonb,
  'A well-established, well-reviewed dealer — plan for the Questrade custodian step on registered accounts.',
  '{"product_type":"direct_bullion","premium_over_spot_pct":5.24,"premium_note":"Not published as a flat rate — one example found a 1oz gold coin priced ~5.24% over spot; premiums are described as lower on bars than coins and scale with order size. Call for live pricing.","storage_note":"Held via third-party depository International Depository Services (IDS) in Canada, the US and other jurisdictions, with allocated and segregated options. Minimum storage fee $200/yr (~$16.67/mo) plus tax; IDS reportedly charges up to ~1.5%/yr of value on smaller holdings — exact tiered pricing requires a quote.","buyback_available":true,"registered_account_note":"RRSP/TFSA-eligible via a required third-party custodian — a Questrade account must be opened first before Sprott Money can process a registered-account order.","accreditation":"retail_dealer","accreditation_note":"States FINTRAC AML/CTF compliance obligations on its own FAQ; specific MSB registration number not independently confirmed. Accepts LBMA-accredited bullion products for registered-account purchases; no explicit LBMA membership independently confirmed.","years_in_business":18,"trustpilot_rating":3.7,"trustpilot_count":null,"trustpilot_note":"Trustpilot 3.7/5 (smaller sample); ShopperApproved 4.8/5 from 2,600+ verified reviews; BBB A+ accredited since 2011 with 0 complaints in the last 3 years.","regulatory_note":"Individual reviews mention billing friction with the vault/storage program and occasional shipping delays — customer-service-level issues, not regulatory findings."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.sprottmoney.com/',
  false,
  'Investors already using Questrade for RRSP/TFSA gold',
  4,
  'https://www.sprottmoney.com/faq',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'kitco',
  'ca',
  'gold-investing',
  'platforms',
  'Kitco',
  'One of the longest-operating dealers in Canada, since 1977',
  7.2,
  0,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Operating since 1977', 'Storage at the Royal Canadian Mint', '⚠ Pool product not fully backed — see detail']::text[],
  ARRAY['One of the longest-operating precious-metals dealers in Canada (since 1977)', 'Three distinct storage tiers, including allocated storage at the Royal Canadian Mint', 'VaultChain blockchain-tracked ownership option, custodied at the Mint']::text[],
  ARRAY['Kitco Pool is unallocated (pooled, not individually segregated) — a materially different and lower-protection structure than the allocated tier, and a 2014 report found it was not 100% physically backed at the time', 'No reliable Trustpilot/BBB score found; pricing requires direct contact']::text[],
  '{"trust":6.6,"cost":6,"rating":0}'::jsonb,
  'A long-established name — understand the Pool product''s different (lower) protection level before choosing it.',
  '{"product_type":"direct_bullion","premium_over_spot_pct":null,"premium_note":"Not publicly disclosed — Kitco requires direct contact for quotes.","storage_note":"Three tiers: Allocated Storage (KAS, segregated physical, at the Royal Canadian Mint/COMEX-approved depository/Hong Kong), Kitco Pool (UNALLOCATED, pooled — not individually segregated, a materially different structure), and VaultChain (blockchain-tracked, custodied at the Royal Canadian Mint).","buyback_available":true,"registered_account_note":"Registered-account eligibility not independently confirmed at research time — confirm directly before assuming RRSP/TFSA support.","accreditation":"retail_dealer","accreditation_note":"Storage partnership with the Royal Canadian Mint (a Crown corporation); no explicit public LBMA membership confirmation found. Founded 1977, one of the longest-operating dealers on this page.","years_in_business":49,"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No reliable Trustpilot/BBB score found for Kitco''s bullion business specifically at research time.","regulatory_note":"A 2011 creditor-protection (CCAA) filing tied to a Revenue Québec tax dispute involving suppliers was resolved in Kitco''s favor by the Quebec Superior Court in 2016, with no wrongdoing found — historical, disclosed for transparency. Separately, a 2014 report noted the Kitco Pool product was not 100% physically backed at the time and pool holders were not treated as creditors in the 2011 proceeding — relevant specifically to the Pool (unallocated) product, not the allocated storage program."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://online.kitco.com/',
  false,
  'Buyers wanting the longest-established Canadian name',
  5,
  'https://online.kitco.com/storage/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'goldmoney',
  'ca',
  'gold-investing',
  'platforms',
  'GoldMoney',
  'A TSX-listed public company with real, recent account complaints',
  6.4,
  2.6,
  1800,
  1800,
  0,
  0,
  '[]'::jsonb,
  ARRAY['TSX: XAU, 22,000+ customers', '$1.4B+ partner-vault holdings', '⚠ 2024-25 account-freeze complaints — see detail']::text[],
  ARRAY['A currently-operating, TSX-listed public company (TSX: XAU) with 22,000+ customers and $1.4B+ in partner-vault holdings', 'Long operating history and public financial disclosures (unusual transparency for a bullion dealer)']::text[],
  ARRAY['Real, recent (2024-2025) customer complaints describe account freezes demanding decade-old documentation and at least one case of unilateral liquidation of a customer''s holdings', 'Trustpilot score is poor (2.6/5, ~1,800 reviews), with a suspicious cluster of 5-star reviews after a long period of ~2-star averages']::text[],
  '{"trust":5,"cost":6,"rating":5.2}'::jsonb,
  'A legitimate public company — but weigh the real, recent account-freeze complaints carefully.',
  '{"product_type":"direct_bullion","premium_over_spot_pct":null,"premium_note":"Not independently confirmed at research time — request a live quote.","storage_note":"Partner-vault custody; ~$1.4B in partner-vault holdings across 22,000+ customers per company disclosures.","buyback_available":true,"registered_account_note":"Registered-account eligibility not independently confirmed at research time.","accreditation":"retail_dealer","accreditation_note":"Goldmoney Inc. is a currently-operating, TSX-listed public company (TSX: XAU); not independently confirmed as an LBMA member.","years_in_business":null,"trustpilot_rating":2.6,"trustpilot_count":1800,"trustpilot_note":"trustpilot.com — of the most recent 20 reviews only 2 were 4-5 stars; a sudden cluster of 5-star reviews after roughly a year of ~2-star averages reads as a possible review-manipulation pattern and should be treated skeptically.","regulatory_note":"Goldmoney Inc. shifted its corporate registration from British Columbia to the British Virgin Islands in September 2024 — a disclosed, shareholder-approved move (over 90% of share capital held by non-Canadian beneficial owners) by a real, currently-operating public company, not a covert shell restructuring; stated rationale was capital-return efficiency. Separately, the Jersey Financial Services Commission required Goldmoney to agree not to operate in Jersey for 10 years (2021-2022), tied to an undisclosed 2016-2018 matter in its Jersey subsidiary. More relevant to a retail buyer: real, recent (2024-2025) customer complaints describe repeated account freezes demanding decade-old documentation from already-verified accounts, accounts frozen without notification, and at least one case of unilateral liquidation of a customer''s gold holdings in early 2025."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.goldmoney.com/',
  false,
  'Investors weighing real account-freeze complaints',
  6,
  'https://www.goldmoney.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'canadian-bullion-services',
  'ca',
  'gold-investing',
  'platforms',
  'Canadian Bullion Services',
  'Active, recent non-delivery complaints — disclosed, ranked last',
  4.8,
  0,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Not BBB-accredited', '⚠ Active 2025-2026 non-delivery complaints — see detail']::text[],
  ARRAY['Frequently listed on Canadian comparison portals']::text[],
  ARRAY['Multiple recent (2025-2026) customer reports describe months-long non-delivery after payment, unreturned calls, and unanswered refund requests', 'Not BBB-accredited, with no reliable positive-sentiment review base found']::text[],
  '{"trust":2,"cost":5,"rating":0}'::jsonb,
  'Kept on this list per the approved shortlist — but the disclosed complaint pattern is serious. Read the detail below.',
  '{"product_type":"direct_bullion","premium_over_spot_pct":null,"premium_note":"Not independently confirmed at research time.","storage_note":"Not independently confirmed at research time.","buyback_available":false,"registered_account_note":"Not independently confirmed at research time.","accreditation":"retail_dealer","accreditation_note":"Not BBB-accredited.","years_in_business":null,"trustpilot_rating":null,"trustpilot_count":null,"trustpilot_note":"No reliable positive-sentiment review base found — see regulatory note for the specific, recent complaint pattern.","regulatory_note":"Multiple recent (2025-2026, including March 2026 and June 2025) customer reports describe months-long non-delivery after payment, unreturned phone calls with full voicemail boxes, and refund requests going unanswered after cancellation — the most concerning, active complaint pattern of any of the 7 dealers researched for this page. The company is not BBB-accredited. An unverified allegation (via a consumer-complaint site) claims prior operation under a different company name — treated as an allegation, not confirmed fact. Ranked last with this disclosure rather than excluded, per the approved candidate shortlist; consider the disclosed risk carefully before ordering."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.canadianbullion.ca/',
  false,
  'Buyers who have weighed the active complaint pattern',
  7,
  'https://www.canadianbullion.ca/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee, account_minimum = EXCLUDED.account_minimum,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
