-- Comparison Cockpit — seed UK remortgage-brokers (market='uk',
-- category='remortgaging', UK-exclusive topic). Visit-only launch (AU/CA/UK
-- rollout, Stage 3 Slice UK-2): affiliate_link_id NULL, is_affiliate=false,
-- review_slug NULL, external_url = provider homepage. Idempotent (ON
-- CONFLICT DO UPDATE). Attributes validated against
-- ukRemortgageBrokersAttributesSchema. costModel uses a flatFeeAccessor
-- returning the real, disclosed broker fee (£0 for 6 of 7; Tembo Money's
-- remortgage service is also free, though its new-purchase service charges
-- up to £499-749, disclosed but not applied here). MoneySuperMarket and
-- Uswitch are disclosed as pure comparison/lead-gen tools that hand off to
-- L&C and Mojo respectively -- Uswitch and Mojo share the same RVU/Zoopla/
-- Silver Lake Partners ownership, disclosed as a material independence
-- caveat. Habito's April 2026 Monzo acquisition and Better.co.uk's 2025
-- sale from its financially-troubled US parent to UK proptech OneDome are
-- both disclosed in full.
-- Provenance: live research 2026-07-11 against official pricing pages, FCA
-- Register, Trustpilot, British Bank Awards.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, management_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'lc-mortgages',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'L&C (London & Country) Mortgages',
  'The UK''s largest fee-free broker',
  9,
  4.6,
  18000,
  18000,
  0,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['£33M+ saved for customers in 2025', '65,000+ completions in 2025', 'B Corp certified']::text[],
  ARRAY['The UK''s largest fee-free mortgage broker, with a transparent "how we''re paid" disclosure', 'Saved customers £33m+ in 2025 across 65,000+ completions', 'British Bank Awards 2026 — Customer Service Champion + Best Broker (highly commended)']::text[],
  ARRAY['Recurring complaint theme is slow or unclear communication, per Trustpilot review analysis', 'Not owned by a bank — majority-owned by its founder since 2000, with Experian holding a minority stake since 2017 (a real but not concerning ownership structure)']::text[],
  '{"independence":9.4,"panel":8.6,"cost":10,"rating":9.2}'::jsonb,
  'The UK''s largest, most-trusted fee-free remortgage broker.',
  '{"business_model":"whole_of_market_broker","business_model_note":"Independent whole-of-market broker; not owned by a bank or comparison-site conglomerate — majority-owned by founder Michael Edge since 2000, with Experian holding a minority stake since 2017","lender_panel_note":"~90+ lenders per third-party review; L&C''s own \"whole-of-market\" marketing claim is not independently verified against every UK lender","broker_fee_gbp":0,"consumer_fee_note":"Fee-free for mortgage advice; exceptions apply for conveyancing (referral fee, paid to the conveyancer) and optional life/protection cover (commission-based)","trustpilot_rating":4.6,"trustpilot_count":18000,"trustpilot_note":"uk.trustpilot.com/review/landc.co.uk","regulatory_note":"No FCA fines or enforcement action found for 2024-2026 — only routine service-delay complaints on consumer forums."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.landc.co.uk/',
  true,
  'Borrowers wanting the largest fee-free broker',
  1,
  'https://www.landc.co.uk/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'habito',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'Habito',
  'A fully digital, whole-of-market broker — now backed by Monzo',
  8.7,
  4.9,
  10000,
  10000,
  0,
  '[{"type":"green","label":"Best digital, whole-of-market broker"}]'::jsonb,
  ARRAY['95+ lenders', 'Acquired by Monzo (completed 30 Apr 2026)', 'Still operates under its own brand']::text[],
  ARRAY['A whole-of-market digital broker with a 95+ lender panel', 'Strong Trustpilot rating (~4.9/5)', 'Now backed by Monzo''s resources following an April 2026 acquisition, while continuing to operate under its own brand and FCA authorisation']::text[],
  ARRAY['You do not need a Monzo account to use Habito, but the acquisition is a genuine, recent ownership change worth knowing about']::text[],
  '{"independence":8,"panel":9.4,"cost":10,"rating":9.6}'::jsonb,
  'The best fully digital, whole-of-market broker — now with Monzo''s backing.',
  '{"business_model":"whole_of_market_broker","business_model_note":"Digital-first, whole-of-market broker; acquired by Monzo (Monzo''s first-ever acquisition), completed 30 April 2026, but continues operating under its own brand and FCA authorisation (Hey Habito Ltd, FRN 714187) — a Monzo account is not required to use Habito","lender_panel_note":"95+ lenders — current figure supersedes an older \"90+\" claim","broker_fee_gbp":0,"consumer_fee_note":"Free — paid via an approximate 0.35% lender procuration fee","trustpilot_rating":4.9,"trustpilot_count":10000,"trustpilot_note":"Trustpilot \"Excellent\" rating; exact current review count not independently re-confirmed live at research time","regulatory_note":"Monzo announced its first-ever acquisition of Habito in December 2025; the deal completed 30 April 2026. Habito continues operating under its own brand, own site and own FCA authorisation. No FCA fines or enforcement action found for 2024-2026."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.habito.com/',
  false,
  'Borrowers wanting a fully digital, whole-of-market broker',
  2,
  'https://www.habito.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'better-co-uk',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'Better.co.uk',
  'Digital broker, now under new UK ownership (OneDome)',
  8.3,
  4.85,
  9000,
  9000,
  0,
  '[]'::jsonb,
  ARRAY['90-100+ lenders (RateWatch monitoring)', 'Sold to UK proptech OneDome (2025)', 'Free for most customers']::text[],
  ARRAY['A digital broker with a "RateWatch" rate-monitoring tool and a 90-100+ lender panel', 'Strong Trustpilot rating ("Excellent", 4.8-4.9/5)', 'Sold in mid-2025 by its struggling US parent to UK proptech firm OneDome — now genuinely decoupled from that parent''s financial turmoil']::text[],
  ARRAY['Free "for most customers," but the site notes fees can apply depending on individual circumstances', 'Excludes some direct-only lenders (e.g. Lloyds, First Direct) from its panel']::text[],
  '{"independence":8.2,"panel":8.6,"cost":9.6,"rating":9.4}'::jsonb,
  'A well-reviewed digital broker, now under new, more stable UK ownership.',
  '{"business_model":"whole_of_market_broker","business_model_note":"Digital broker (formerly Trussle, launched 2015; rebranded Better.co.uk in January 2023 after acquisition by US-based Better Home & Finance Holding); in May-June 2025 the UK entity (Trussle Lab Ltd) was sold by its US parent to UK proptech firm OneDome — Trustpilot now lists it as \"Better.co.uk — trading as ONEDOME\"","lender_panel_note":"90-100+ lenders (the \"100+\" figure on-site carries a January 2023 disclaimer, treat as approximate); excludes some direct-only lenders (Lloyds, First Direct)","broker_fee_gbp":0,"consumer_fee_note":"Free for most customers; the site notes fees can apply depending on individual circumstances","trustpilot_rating":4.85,"trustpilot_count":9000,"trustpilot_note":"Trustpilot \"Excellent\", 4.8-4.9/5, figure fluctuated across pages","regulatory_note":"Better.co.uk''s former US parent, Better Home and Finance Holding (Nasdaq: BETR), saw its stock fall approximately 93% after its August 2024 Nasdaq debut, underwent a 1-for-50 reverse stock split, and completed an April 2025 debt restructuring exchanging $534m of SoftBank debt for $110m cash plus $155m in new notes — separately from a widely-reported December 2021 mass-layoff incident (~900 staff let go via a single Zoom call). None of this directly affected the UK entity, which was sold to UK-based OneDome in May-June 2025 and now operates independently of the US parent''s ongoing situation — disclosed for transparency, not as a current risk to the UK service."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://better.co.uk/',
  false,
  'Borrowers wanting ongoing rate-monitoring after applying',
  3,
  'https://better.co.uk/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'tembo-money',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'Tembo Money',
  'The best specialist choice for complex remortgage cases',
  8,
  4.7,
  6000,
  6000,
  0,
  '[{"type":"sky","label":"Best for complex/specialist cases"}]'::jsonb,
  ARRAY['British Bank Awards winner, 5 years running', '100+ lenders', 'Free remortgage service']::text[],
  ARRAY['Best Mortgage Broker at the British Bank Awards for 5 consecutive years (2026), beating L&C, Habito and Mojo per Tembo''s own announcement', 'Human advisers specializing in affordability-boosting products (guarantor mortgages, shared ownership, income-boosting schemes) that generalist brokers often can''t place', 'Remortgage service is free, like the other whole-of-market brokers on this page']::text[],
  ARRAY['Its standard (new-purchase) mortgage service charges a £499 fee, rising to £749 for complex cases — a genuine exception versus the fully fee-free brokers, though not applicable to remortgaging specifically', 'Smaller review base than the largest brokers on this page (~6,000+ reviews)']::text[],
  '{"independence":8.8,"panel":8.6,"cost":9.4,"rating":9}'::jsonb,
  'The best specialist option for complex cases — genuinely free for remortgages specifically.',
  '{"business_model":"specialist_broker","business_model_note":"Whole-of-market broker with human advisers, specializing in affordability-boosting products (Deposit Boost, Income/Family Boost, guarantor mortgages, shared ownership, key-worker schemes) for buyers who don''t qualify with generalist brokers","lender_panel_note":"100+ lenders claimed","broker_fee_gbp":0,"consumer_fee_note":"Free for remortgages; its standard (new-purchase) mortgage service charges £499, rising to £749 for complex/specialist cases (capped at 1% of loan value), waived for HomeSaver/savings-account holders — not applicable to this remortgage-specific comparison","trustpilot_rating":4.7,"trustpilot_count":6000,"trustpilot_note":"Trustpilot \"Excellent\", ~4.8/5 per one source, ~4.6/5 per another — figure shown is a midpoint, verify live","regulatory_note":"No FCA enforcement found for Tembo Money Ltd or Tembo Savings Ltd. Minor MoneySavingExpert complaint threads exist about FSCS-protection clarity for its savings products, and some 1-star Trustpilot complaints about missed appointments — service-quality issues, not regulatory findings. Raised £15m+ in February 2026 (led by Gresham House Ventures with Aviva Investors and British Business Bank), with savings AUA reaching £3bn in 2025."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.tembomoney.com/',
  false,
  'Borrowers with complex cases generalist brokers can''t place',
  4,
  'https://www.tembomoney.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'mojo-mortgages',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'Mojo Mortgages',
  'A whole-of-market fintech broker, part of the RVU group',
  7.6,
  4.8,
  9945,
  9945,
  0,
  '[]'::jsonb,
  ARRAY['60+ lenders (per Mojo''s own site)', 'Trustpilot 4.8/5 (9,945 reviews)', 'Owned by RVU (with Uswitch)']::text[],
  ARRAY['Strong Trustpilot rating (4.8/5, 9,945 reviews)', 'Free advice, paid via lender commission']::text[],
  ARRAY['Mojo''s own site states 60+ lenders — a narrower confirmed panel than L&C, Habito, Better.co.uk or Tembo (though some third-party sites cite higher, unverified figures)', 'Owned by RVU (part of Zoopla Property Group, majority-owned by Silver Lake Partners) — the same parent that owns Uswitch, which feeds referrals directly to Mojo']::text[],
  '{"independence":7,"panel":7.4,"cost":10,"rating":9.6}'::jsonb,
  'A well-reviewed broker with a narrower confirmed lender panel and notable corporate ownership ties.',
  '{"business_model":"whole_of_market_broker","business_model_note":"Fintech-style whole-of-market broker; acquired by RVU in July 2021 — RVU also owns Uswitch, Confused.com, Money.co.uk and Tempcover, and is itself part of Zoopla Property Group, majority-owned by US private-equity firm Silver Lake Partners since 2018","lender_panel_note":"60+ lenders per Mojo''s own site; some third-party sites cite 70-90+, unverified against a primary source","broker_fee_gbp":0,"consumer_fee_note":"Free — no fees for advice, paid via lender commission","trustpilot_rating":4.8,"trustpilot_count":9945,"trustpilot_note":"Per Mojo''s own broker page (via Uswitch)","regulatory_note":"No FCA enforcement found for Mojo Mortgages or parent RVU. Two individual Financial Ombudsman rulings on delayed-communication complaints were found — routine, not systemic."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://mojomortgages.com/',
  false,
  'Borrowers wanting a fintech-style broker experience',
  5,
  'https://mojomortgages.com/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'moneysupermarket-mortgages',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'MoneySuperMarket Mortgages',
  'A comparison tool, not a broker — hands off to L&C',
  6.8,
  4.9,
  54000,
  54000,
  0,
  '[]'::jsonb,
  ARRAY['Pure comparison tool, not a broker', 'Hands off to L&C for advice', '90+ lenders covered']::text[],
  ARRAY['A large, well-known comparison hub (site-wide Trustpilot ~5-star, 52,000-56,500+ reviews) covering 90+ lenders', 'Hands off to L&C (a genuinely strong, independent broker) for actual advice and completion']::text[],
  ARRAY['Not itself a broker — gives no advice directly, so the "MoneySuperMarket" experience is really just the L&C experience downstream', 'L&C''s own fee applies downstream if you''re switching lender (free if staying with your current lender, £195 if switching, payable on completion only)']::text[],
  '{"independence":6,"panel":8.4,"cost":9.6,"rating":9.8}'::jsonb,
  'A large comparison hub — understand you''re really getting the L&C experience downstream.',
  '{"business_model":"comparison_lead_gen","business_model_note":"Pure comparison/lead-gen tool, not a broker — for actual advice and completion, hands consumers off primarily to L&C (non-exclusive; Fluent Mortgages also partners); MoneySuperMarket earns referral commission when a user completes via a partner","lender_panel_note":"Comparison tool covers 90+ lenders; the broker it feeds into (L&C) covers 80+","broker_fee_gbp":0,"consumer_fee_note":"Free to use; L&C''s own downstream fee applies if switching lender (free if staying with your current lender, £195 payable on completion if switching)","trustpilot_rating":4.9,"trustpilot_count":54000,"trustpilot_note":"Site-wide rating (not mortgage-specific), ~52,000-56,500 reviews","regulatory_note":"No FCA action found against the genuine company (ultimate parent: MONY Group plc, LSE-listed FTSE 250, renamed from Moneysupermarket.com Group plc in May 2024). The FCA has separately warned about clone-firm scams impersonating the \"Money Supermarket\" name — this is fraud against the brand, not a finding against the real company."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.moneysupermarket.com/mortgages/',
  false,
  'Borrowers wanting a large, well-known comparison hub',
  6,
  'https://www.moneysupermarket.com/mortgages/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'uswitch-mortgages',
  'uk',
  'remortgaging',
  'remortgage-brokers',
  'Uswitch Mortgages',
  'A comparison tool that hands off to its own sister company',
  6.2,
  4,
  39000,
  39000,
  0,
  '[]'::jsonb,
  ARRAY['Pure comparison tool, not a broker', 'Hands off to Mojo — same RVU parent', '60+ lenders covered']::text[],
  ARRAY['A well-known comparison brand (site-wide Trustpilot ~4/5, 39,000+ reviews)', 'Free to use']::text[],
  ARRAY['Not itself a broker — hands consumers off to Mojo Mortgages, a corporate sister company under the same RVU/Zoopla/Silver Lake Partners ownership structure, materially limiting how independent the recommendation really is', 'The narrowest confirmed lender panel of the 7 (60+, via Mojo)']::text[],
  '{"independence":5,"panel":7,"cost":10,"rating":8}'::jsonb,
  'A well-known brand — but understand its mortgage tool structurally feeds its own sister company.',
  '{"business_model":"comparison_lead_gen","business_model_note":"Pure comparison/lead-gen tool — Uswitch does not give mortgage advice itself, and hands consumers to Mojo Mortgages for actual advice/completion. Both Uswitch and Mojo are owned by RVU (part of Zoopla Property Group, majority-owned by Silver Lake Partners since 2018) — Uswitch states it does not earn money directly from these referrals, but the two are corporate affiliates, not independently competing services","lender_panel_note":"60+ lenders (via Mojo)","broker_fee_gbp":0,"consumer_fee_note":"Free to use","trustpilot_rating":4,"trustpilot_count":39000,"trustpilot_note":"Uswitch overall (site-wide, not mortgage-specific)","regulatory_note":"No FCA enforcement found against Uswitch Limited (FRN 312850) or RVU/Mojo. The shared RVU/Zoopla/Silver Lake Partners ownership with Mojo Mortgages (the broker Uswitch refers customers to) is disclosed as a material relationship affecting independence, not a compliance violation."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.uswitch.com/mortgages/',
  false,
  'Existing Uswitch users comparing energy/broadband too',
  7,
  'https://www.uswitch.com/mortgages/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  management_fee = EXCLUDED.management_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
