-- Comparison Cockpit — seed UK ai-tools-finance (market='uk').
-- Visit-only launch (AU/CA/UK rollout, Stage 3 Slice UK-3, completes UK
-- 9/9 and the ENTIRE 26-topic AU/CA/UK rollout): affiliate_link_id NULL,
-- is_affiliate=false, review_slug NULL, external_url = provider homepage.
-- Idempotent (ON CONFLICT DO UPDATE). Attributes validated against
-- ukAiToolsFinanceAttributesSchema. Cleo's US parent's $17M March 2025 FTC
-- settlement (deceptive cash-advance marketing) is disclosed with the
-- US-vs-UK scope distinction preserved. Snoop's July 2023 acquisition by
-- Vanquis Banking Group and ANNA Money's e-money-safeguarding-not-FSCS
-- structure are both disclosed. Emma's dual-FRN FCA registration is flagged
-- for direct verification rather than asserted with false confidence.
-- Provenance: live research 2026-07-11 against official pricing pages, FCA
-- Register, Open Banking registry, App Store, Trustpilot.

INSERT INTO public.product_attributes (
  affiliate_link_id, slug, market, category, topic, display_name, tagline,
  score, rating, review_count, clicks, monthly_fee,
  badges, chips, pros, cons, sub_scores, verdict,
  attributes, source_type, confidence,
  is_affiliate, review_slug, external_url, is_top_pick, best_for, display_order,
  source_url, data_verified_at, active
) VALUES
(
  NULL,
  'emma',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Emma',
  'AI subscription detection with a clean regulatory record',
  8.9,
  4.3,
  8800,
  8800,
  4.99,
  '[{"type":"gold","label":"Editor''s pick"}]'::jsonb,
  ARRAY['AI subscription/duplicate-payment detection', 'FCA-registered AISP', 'Free tier available']::text[],
  ARRAY['Genuinely useful AI subscription and duplicate-payment detection across 50+ linked accounts', 'FCA-registered as an Account Information Service Provider under Open Banking', 'Free core tier with paid Plus/Pro/Ultimate tiers for deeper features']::text[],
  ARRAY['Recurring complaints about unexpected charges after free-trial periods and difficulty cancelling paid subscriptions', 'Emma holds two separate FCA FRNs (AISP registration and a separate investment/consumer-credit permission) — confirm current mapping directly on the FCA Register before relying on either number']::text[],
  '{"fees":8.4,"features":9.2,"ux":8.8,"support":7.4}'::jsonb,
  'The most broadly useful AI budgeting app researched, with a clean regulatory record.',
  '{"pricing_model":"freemium","starting_price_note":"Free core tier. Paid: Plus £4.99/month, Pro £9.99/month, Ultimate £14.99/month (7-day free trial, ~30% off if paid annually).","target_segment":"budgeting","ai_features_note":"Automated subscription/recurring-payment detection (\"Who Charged Me\" lookup engine), transaction categorisation, and an AI investing feature (in-app ETF access) added in 2026.","free_tier_or_trial":true,"review_score":4.3,"review_count":8800,"review_source":"Google Play","review_note":"Trustpilot figures conflict between sources (3.5-4.1/5) — treat as unverified/volatile pending a fresh pull.","regulatory_note":"Emma Technologies Ltd holds two separate FCA registrations: FRN 794952 for its AISP (Open Banking) registration under the Payment Services Regulations 2017, and a separate FRN, 1042167, covering investment services and consumer-credit broking permissions. Verify the current FRN-to-permission mapping directly on the FCA Register before relying on either number for a specific claim."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://emma-app.com/',
  true,
  'Most UK users wanting broad AI budgeting help',
  1,
  'https://help.emma-app.com/en/article/how-much-does-emma-plusproultimate-cost-1ywhulq/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'plum',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Plum',
  'Automated saving & investing — FSCS-protected, no disclosed issues',
  8.7,
  4.4,
  4200,
  4200,
  0,
  '[{"type":"green","label":"Best for automated saving & investing"}]'::jsonb,
  ARRAY['AI-driven automated saving', 'FSCS-protected investments (£85K)', 'No disclosed regulatory issues']::text[],
  ARRAY['The "Plum brain" AI analyses income/spending patterns to automatically move small, affordable amounts into savings and investments', 'Investments held via GIA/Stocks & Shares ISA/SIPP are FSCS-protected up to £85,000', 'No confirmed regulatory issues found for 2024-2026']::text[],
  ARRAY['Exact current paid-tier pricing was not independently confirmed at research time — verify on withplum.com/pricing', 'FSCS protection covers firm insolvency, not market losses on investments']::text[],
  '{"fees":8.6,"features":8.8,"ux":8.6,"support":8.2}'::jsonb,
  'The cleanest regulatory record of the 7, with genuine FSCS-protected automated investing.',
  '{"pricing_model":"freemium","starting_price_note":"Free tier exists; paid subscription tiers (Plus/Pro) confirmed to exist but exact current 2026 pricing was not independently confirmed in this research pass — verify directly on withplum.com/pricing.","target_segment":"budgeting","ai_features_note":"Algorithmic automated saving that analyses income/spending patterns and moves small, affordable amounts into savings/investments; automated investment portfolio rebalancing.","free_tier_or_trial":true,"review_score":4.4,"review_count":4200,"review_source":"Trustpilot","review_note":"App Store 4.7/5, Google Play 4.6/5 also cited.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://withplum.com/',
  false,
  'Savers wanting automated, FSCS-protected investing',
  2,
  'https://withplum.com/legal/money-protections',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'anna-money',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'ANNA Money',
  'AI receipt scanning + live HMRC tax estimate for sole traders',
  8.4,
  4.4,
  4000,
  4000,
  14.9,
  '[{"type":"sky","label":"Best for sole traders"}]'::jsonb,
  ARRAY['AI receipt-to-transaction matching', 'Live HMRC tax-liability estimate', 'HMRC-recognised for Making Tax Digital']::text[],
  ARRAY['AI receipt-to-transaction matching, automatic tax categorisation and a live running HMRC tax-liability estimate', 'Officially recognised by HMRC for Making Tax Digital (MTD)', '100,000+ UK business customers, with a free PAYG tier available']::text[],
  ARRAY['Funds are e-money safeguarded via PayrNet (not FSCS-protected) — a materially different, lower-assurance protection than the FSCS-backed apps on this page', 'Recurring 2024-2026 reviews describe account freezes/suspensions tied to fraud/AML checks with limited communication during investigation']::text[],
  '{"fees":8,"features":8.8,"ux":8.4,"support":7.6}'::jsonb,
  'The best AI tax-automation tool for sole traders — understand the safeguarding-not-FSCS distinction.',
  '{"pricing_model":"bundle_tier","starting_price_note":"PAYG: £0/month (20 free transfers, then 20p each). ANNA Business: ~£14.90/month (50 free transfers). ANNA Big Business: ~£49.90/month (unlimited transfers). AI tax automation (Auto Accountant) tier around £24+VAT/month.","target_segment":"tax_compliance","ai_features_note":"AI receipt-to-transaction matching, automatic tax categorisation, a live running HMRC tax-liability estimate, and a \"Smart Tax Pot\" that auto-sets aside funds for tax.","free_tier_or_trial":true,"review_score":4.4,"review_count":4000,"review_source":"Trustpilot","review_note":"\"Excellent\" rating, 83% five-star / 11% one-star split.","regulatory_note":"ANNA''s funds are e-money safeguarded (not FSCS-protected) via PayrNet Limited, an FCA-authorised EMI — a materially different, lower-assurance protection than the FSCS-backed apps on this page. In June 2020, ANNA suspended all cards when its then-payment processor Wirecard UK was frozen by the FCA — a historical, resolved third-party-risk incident. Recurring 2024-2026 reviews describe account freezes/suspensions tied to fraud/AML checks with limited communication during investigation — a pattern common to EMI-based business accounts generally, not unique to ANNA."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://anna.money/',
  false,
  'Sole traders wanting AI-assisted tax compliance',
  3,
  'https://anna.money/help/articles/6811441-how-anna-protects-your-money/',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'moneybox',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Moneybox',
  'Round-up investing — the weakest AI positioning of the 7',
  7.4,
  4,
  4778,
  4778,
  1,
  '[]'::jsonb,
  ARRAY['1M+ UK customers', 'Round-up investing + savings-goal suggestions', 'Weaker AI positioning than peers']::text[],
  ARRAY['A well-established UK brand (over 1 million customers) combining round-up investing with algorithmic savings-goal suggestions', 'No confirmed regulatory issues found for 2024-2026', 'Subscription fee waived above £5,000 in cash savings, free for the first 3 months']::text[],
  ARRAY['Its AI positioning is thinner than Emma, Plum or Cleo — round-up investing with basic algorithmic suggestions, not a headline AI feature', '£1/month subscription plus a 0.45% annual platform fee on investments']::text[],
  '{"fees":8,"features":6.6,"ux":8,"support":7.4}'::jsonb,
  'A well-established, reliable round-up investing app — disclosed as having the weakest AI claim of the 7.',
  '{"pricing_model":"flat_subscription","starting_price_note":"£1/month app subscription plus a 0.45% annual platform fee on investments; subscription free for the first 3 months and waived above £5,000 in cash savings.","target_segment":"budgeting","ai_features_note":"Round-up (spare-change) investing with algorithmic savings-goal suggestions — a less AI-branded feature set than Emma, Plum or Cleo, disclosed rather than inflated.","free_tier_or_trial":true,"review_score":4,"review_count":4778,"review_source":"Trustpilot","review_note":"","regulatory_note":"No confirmed 2024-2026 breach or FCA fine found; individual Financial Ombudsman complaints exist but are routine customer disputes, not systemic incidents."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.moneyboxapp.com/',
  false,
  'Beginners wanting simple round-up investing',
  4,
  'https://www.moneyboxapp.com/fees-and-charges',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'microsoft-copilot-finance',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Microsoft Copilot for Finance',
  'Excel reconciliation agents for enterprise finance teams',
  7.2,
  0,
  0,
  0,
  24.7,
  '[]'::jsonb,
  ARRAY['Financial Reconciliation agent in Excel', 'From £24.70/user/month (base licence)', 'Enterprise / B2B tool']::text[],
  ARRAY['The Financial Reconciliation agent in Excel matches datasets and auto-suggests reconciliation rules in assistive or autonomous mode', 'Backed by Microsoft''s enterprise scale and integration with the existing Microsoft 365 ecosystem']::text[],
  ARRAY['The £24.70/user/month figure is the entry price for the base Copilot licence that includes Finance agents, not a standalone "Copilot for Finance" product price — realistic all-in cost for UK SMEs is closer to £35-55/user/month once governance and rollout costs are included', 'No dedicated G2/Capterra review listing exists specifically for the Finance agents']::text[],
  '{"fees":6.4,"features":8.4,"ux":7.6,"support":7}'::jsonb,
  'A genuinely capable enterprise tool for finance teams already on Microsoft 365 — understand the real all-in cost.',
  '{"pricing_model":"bundle_tier","starting_price_note":"£24.70/user/month (ex-VAT, annual commitment) is the list price for the base Microsoft 365 Copilot licence that includes Finance agents, not a separately-priced \"Copilot for Finance\" SKU. Realistic all-in cost for UK SMEs is estimated at £35-55/user/month once base-licence uplift and governance costs are included.","target_segment":"enterprise_finance","ai_features_note":"Financial Reconciliation agent in Excel matches two datasets, auto-suggests reconciliation rules, and categorises transactions as matched/unmatched/potentially-matched, running in assistive or fully autonomous mode.","free_tier_or_trial":false,"review_score":null,"review_count":null,"review_source":"Not applicable","review_note":"No dedicated G2/Capterra listing exists specifically for \"Microsoft Copilot for Finance\" as a distinct product — reviews exist for Microsoft 365 Copilot generally, not the finance agent specifically, so no finance-specific score is published here.","regulatory_note":""}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.microsoft.com/en-gb/microsoft-365-copilot/pricing',
  false,
  'Enterprise finance teams already on Microsoft 365',
  5,
  'https://learn.microsoft.com/en-us/copilot/finance',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'cleo',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Cleo',
  'A relaunched AI money coach — with a disclosed US FTC settlement',
  6.8,
  4.1,
  3700,
  3700,
  0,
  '[]'::jsonb,
  ARRAY['UK relaunch Feb 2026', '850K+ paying subscribers globally', '⚠ $17M US FTC settlement — see detail']::text[],
  ARRAY['A confirmed UK relaunch (5 February 2026) with an engaging "Money Coach" chatbot personality (Roast Mode/Hype Mode) and subscription-detection features', 'Large global scale (850,000+ paying subscribers as of mid-2026 company reporting)']::text[],
  ARRAY['The US FTC secured a $17 million settlement against Cleo AI in March 2025 over deceptive cash-advance marketing, undisclosed express fees and subscription-cancellation dark patterns', 'No parallel UK/FCA enforcement action identified, but the settlement concerns a product (cash advances) that remains part of Cleo''s offering']::text[],
  '{"fees":8.6,"features":8,"ux":8.2,"support":6.4}'::jsonb,
  'An engaging, freshly-relaunched AI coach — weigh the disclosed US FTC settlement carefully.',
  '{"pricing_model":"freemium","starting_price_note":"Freemium chat assistant; Cleo Plus/Builder subscriptions plus an optional cash-advance product with express fees (e.g. approximately $3.99 for a same-day advance).","target_segment":"coaching_chatbot","ai_features_note":"Conversational \"Money Coach\" chatbot with personality modes (Roast Mode/Hype Mode), subscription/spend detection, and financial coaching tuned to user goals.","free_tier_or_trial":true,"review_score":4.1,"review_count":3700,"review_source":"Trustpilot","review_note":"App Store 4.7/5 (2,600+ reviews); Google Play 4.0/5 (77,500+ reviews).","regulatory_note":"In March 2025, the US FTC secured a $17 million settlement against Cleo AI over deceptive cash-advance marketing (advertising \"up to $250\" when most users received far less), undisclosed express fees, and subscription-cancellation dark patterns. This is a US enforcement action; no evidence of a parallel UK/FCA action was found, but it directly concerns Cleo''s cash-advance product, which remains part of its offering, so we disclose it in full rather than treat it as irrelevant to the UK service."}'::jsonb,
  'official',
  'medium',
  false,
  NULL,
  'https://www.meetcleo.com/',
  false,
  'Users wanting an engaging AI coaching personality',
  6,
  'https://www.prnewswire.co.uk/news-releases/cleo-brings-ai-powered-money-management-back-to-the-uk-302679663.html',
  DATE '2026-07-11',
  true
),
(
  NULL,
  'snoop',
  'uk',
  'ai-tools',
  'ai-tools-finance',
  'Snoop',
  'Free AI spend analysis — now part of Vanquis Banking Group',
  6.4,
  0,
  0,
  0,
  0,
  '[]'::jsonb,
  ARRAY['Completely free', 'AI + human-curated bill optimisation', 'Acquired by Vanquis Banking Group (2023)']::text[],
  ARRAY['Completely free AI + human-curated spend analysis, bill/tariff comparison and "rip-off alerts" via Open Banking', 'FCA-registered as an RAISP since 2019/2020 launch']::text[],
  ARRAY['No longer an independent company — acquired by Vanquis Banking Group in July 2023, though it continues under its own brand', 'Trustpilot rating is genuinely conflicting across sources on a small sample (~120 reviews) — shown as not yet rated rather than an unreliable figure']::text[],
  '{"fees":9.4,"features":7.2,"ux":7.4,"support":6.6}'::jsonb,
  'A genuinely free AI spend-optimisation tool — now owned by a banking group, disclosed for transparency.',
  '{"pricing_model":"freemium","starting_price_note":"Completely free.","target_segment":"budgeting","ai_features_note":"AI plus human-curated spending analysis, bill/tariff comparison and \"rip-off alerts\" via Open Banking account aggregation.","free_tier_or_trial":true,"review_score":null,"review_count":null,"review_source":"Conflicting sources","review_note":"App Store shows 4.6/5 (6,900+ reviews); Trustpilot figures conflict significantly between sources (3.2 vs 4.4/5) on a small sample (~120 reviews) — shown as not yet rated rather than an unreliable specific number.","regulatory_note":"Snoop was acquired by Vanquis Banking Group in July 2023 and is no longer an independent company, though it continues operating as its own branded app within the group rather than being absorbed or renamed. Q1 2026 reporting shows active users up 7% year-over-year to 344,000."}'::jsonb,
  'official',
  'low',
  false,
  NULL,
  'https://www.snoop.app/',
  false,
  'Users wanting a genuinely free bill-optimisation tool',
  7,
  'https://www.vanquis.com/money-saving-app-snoop/',
  DATE '2026-07-11',
  true
)
ON CONFLICT (market, category, topic, slug) DO UPDATE SET
  display_name = EXCLUDED.display_name, tagline = EXCLUDED.tagline, score = EXCLUDED.score,
  rating = EXCLUDED.rating, review_count = EXCLUDED.review_count, clicks = EXCLUDED.clicks,
  monthly_fee = EXCLUDED.monthly_fee,
  badges = EXCLUDED.badges, chips = EXCLUDED.chips, pros = EXCLUDED.pros, cons = EXCLUDED.cons,
  sub_scores = EXCLUDED.sub_scores, verdict = EXCLUDED.verdict, attributes = EXCLUDED.attributes,
  source_type = EXCLUDED.source_type, confidence = EXCLUDED.confidence,
  is_affiliate = EXCLUDED.is_affiliate, review_slug = EXCLUDED.review_slug,
  external_url = EXCLUDED.external_url, is_top_pick = EXCLUDED.is_top_pick,
  best_for = EXCLUDED.best_for, display_order = EXCLUDED.display_order,
  source_url = EXCLUDED.source_url, data_verified_at = EXCLUDED.data_verified_at, active = EXCLUDED.active;
