// scripts/research/normalize-logos.mjs
// One-shot, reproducible normaliser for the Research Library broker logos.
//
// PROBLEM it fixes: the source display assets were all placed on a uniform
// 360x112 transparent canvas, but the actual wordmark inside each only filled
// 40-64% of the canvas HEIGHT (measured). At any given slot height the glyph
// therefore rendered ~1.5-2.5x smaller than the slot — the "logos are far too
// small" report.
//
// WHAT it does: trims the transparent margin off every logo (tight crop to the
// non-transparent bounding box) and re-encodes lossless WebP, so the glyph now
// fills ~100% of its own asset. It then emits components/research/logo-dims.ts
// with each trimmed asset's real width/height, which BrokerLogo feeds to
// next/image as intrinsic dimensions (assets no longer share one aspect ratio,
// so a hard-coded canvas ratio would distort them). Display size is then a
// pure function of the CSS slot height + max-width in BrokerLogo.
//
// Idempotent: re-running trims already-trimmed assets to the same box (nothing
// left to trim) and rewrites an identical manifest. Originals were backed up
// before the first run; the trim is deterministic and re-derivable.
//
//   node scripts/research/normalize-logos.mjs

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';

const DIR = path.join('public', 'images', 'brokers', 'research', 'display');
const MANIFEST = path.join('components', 'research', 'logo-dims.ts');

const files = fs.readdirSync(DIR).filter((f) => f.endsWith('.webp')).sort();
const dims = {};

for (const file of files) {
  const slug = file.replace('.webp', '');
  const src = path.join(DIR, file);
  // trim() with an explicit fully-transparent background removes the alpha
  // border on every side without touching the glyph.
  const trimmed = await sharp(src)
    .trim({ background: { r: 0, g: 0, b: 0, alpha: 0 }, threshold: 8 })
    .webp({ lossless: true })
    .toBuffer();
  const meta = await sharp(trimmed).metadata();
  fs.writeFileSync(src, trimmed);
  dims[slug] = { w: meta.width, h: meta.height };
  console.log(`${slug.padEnd(22)} -> ${meta.width}x${meta.height}`);
}

const body =
  '// components/research/logo-dims.ts\n' +
  '// AUTO-GENERATED by scripts/research/normalize-logos.mjs — do not edit by hand.\n' +
  '// Intrinsic pixel dimensions of each TRIMMED broker logo asset (transparent\n' +
  '// margin removed), fed to next/image so a logo with any aspect ratio renders\n' +
  '// undistorted. Display size is set by the CSS slot in BrokerLogo, not here.\n\n' +
  'export interface LogoDim {\n  w: number;\n  h: number;\n}\n\n' +
  'export const LOGO_DIMS: Record<string, LogoDim> = {\n' +
  Object.entries(dims)
    .map(([slug, d]) => `  ${JSON.stringify(slug)}: { w: ${d.w}, h: ${d.h} },`)
    .join('\n') +
  '\n};\n';

fs.writeFileSync(MANIFEST, body);
console.log(`\nWrote ${MANIFEST} (${Object.keys(dims).length} logos).`);
